// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0aefa76b98e7db2674b316d7cc7ce071a9f909a4863556b07fc20f909bdecfc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata about an LLM extraction pass.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ExtractionMetaBuilder {

    @JsonProperty("cost")
    private Optional<Double> cost = Optional.empty();
    @JsonProperty("prompt_tokens")
    private Optional<Long> promptTokens = Optional.empty();
    @JsonProperty("completion_tokens")
    private Optional<Long> completionTokens = Optional.empty();
    @JsonProperty("model")
    private Optional<String> model = Optional.empty();
    @JsonProperty("chunks_processed")
    private long chunksProcessed = 0;

    /** Sets the cost field. */
    @JsonProperty("cost")
    public ExtractionMetaBuilder withCost(final Optional<Double> value) {
        this.cost = value;
        return this;
    }

    /** Sets the promptTokens field. */
    @JsonProperty("prompt_tokens")
    public ExtractionMetaBuilder withPromptTokens(final Optional<Long> value) {
        this.promptTokens = value;
        return this;
    }

    /** Sets the completionTokens field. */
    @JsonProperty("completion_tokens")
    public ExtractionMetaBuilder withCompletionTokens(final Optional<Long> value) {
        this.completionTokens = value;
        return this;
    }

    /** Sets the model field. */
    @JsonProperty("model")
    public ExtractionMetaBuilder withModel(final Optional<String> value) {
        this.model = value;
        return this;
    }

    /** Sets the chunksProcessed field. */
    @JsonProperty("chunks_processed")
    public ExtractionMetaBuilder withChunksProcessed(final long value) {
        this.chunksProcessed = value;
        return this;
    }

    /** Builds the ExtractionMeta instance. */
    public ExtractionMeta build() {
        return new ExtractionMeta(
            cost.orElse(null),
            promptTokens.orElse(null),
            completionTokens.orElse(null),
            model.orElse(null),
            chunksProcessed
        );
    }
}
