# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: content
defmodule E2e.ContentTest do
  use ExUnit.Case, async: true

  describe "content_204_no_content" do
    test "Handles 204 No Content response gracefully" do
      {:ok, engine} = Kreuzcrawl.create_engine(nil)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_204_no_content"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.status_code == 204
      assert is_nil(result.html) or String.trim(result.html) == ""
    end
  end

  describe "content_charset_iso8859" do
    test "Handles ISO-8859-1 encoded page correctly" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_charset_iso8859"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert String.trim(result.detected_charset) == "iso-8859-1"
    end
  end

  describe "content_empty_body" do
    test "Handles 200 response with empty body gracefully" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_empty_body"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.status_code == 200
    end
  end

  describe "content_gzip_compressed" do
    test "Handles response with Accept-Encoding gzip negotiation" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_gzip_compressed"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
      assert result.status_code == 200
    end
  end

  describe "content_large_page_limit" do
    test "Respects max body size limit and truncates or skips oversized pages" do
      engine_config = "{\"max_body_size\":1024,\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_large_page_limit"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.body_size < 1025
    end
  end

  describe "content_main_only" do
    test "Extracts content with aggressive preprocessing, excluding nav, sidebar, footer" do
      engine_config = "{\"content\":{\"preprocessing_preset\":\"aggressive\"},\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_main_only"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
    end
  end

  describe "content_pdf_no_extension" do
    test "Detects PDF content by Content-Type header when URL has no .pdf extension" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_pdf_no_extension"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.is_pdf == true
    end
  end

  describe "content_remove_tags" do
    test "Removes specified HTML elements by CSS selector before processing" do
      engine_config = "{\"remove_tags\":[\"nav\",\"aside\",\"footer\"],\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_remove_tags"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
    end
  end

  describe "content_utf8_bom" do
    test "Handles UTF-8 content with BOM marker correctly" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_URL") <> "/fixtures/content_utf8_bom"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert String.trim(result.detected_charset) == "utf-8"
      assert result.html != ""
    end
  end
end
