# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6bdc3fa3a0fd95b46a96130d4a94f1bda81bd9b1d8c0e2af23893036023579ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: encoding
defmodule E2e.EncodingTest do
  use ExUnit.Case, async: false

  describe "encoding_double_encoded" do
    test "encoding_double_encoded" do
      {:ok, engine} = Kreuzcrawl.create_engine(nil)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/encoding_double_encoded"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
      assert length(result.links) >= 1
    end
  end

  describe "encoding_mixed_charset_page" do
    test "encoding_mixed_charset_page" do
      {:ok, engine} = Kreuzcrawl.create_engine(nil)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/encoding_mixed_charset_page"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
    end
  end

  describe "encoding_percent_encoded_path" do
    test "encoding_percent_encoded_path" do
      {:ok, engine} = Kreuzcrawl.create_engine(nil)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/encoding_percent_encoded_path"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
      assert length(result.links) >= 2
    end
  end

  describe "encoding_unicode_url" do
    test "encoding_unicode_url" do
      {:ok, engine} = Kreuzcrawl.create_engine(nil)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/encoding_unicode_url"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.html != ""
    end
  end
end
