# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33740c3463cb1ebffb31ee370f5fcd1f0214187f5c475b5ef80530c34af65dec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: redirect
defmodule E2e.RedirectTest do
  use ExUnit.Case, async: false

  describe "redirect_301_permanent" do
    test "redirect_301_permanent" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_301_PERMANENT") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_301_permanent"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_302_found" do
    test "redirect_302_found" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_302_FOUND") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_302_found"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_303_see_other" do
    test "redirect_303_see_other" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_303_SEE_OTHER") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_303_see_other"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_307_temporary" do
    test "redirect_307_temporary" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_307_TEMPORARY") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_307_temporary"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_308_permanent" do
    test "redirect_308_permanent" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_308_PERMANENT") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_308_permanent"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_chain" do
    test "redirect_chain" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_CHAIN") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_chain"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_cross_domain" do
    test "redirect_cross_domain" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_CROSS_DOMAIN") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_cross_domain"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_loop" do
    test "redirect_loop" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_LOOP") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_loop"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'is_error' not available on result type
    end
  end

  describe "redirect_max_exceeded" do
    test "redirect_max_exceeded" do
      engine_config = "{\"max_redirects\":2,\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_MAX_EXCEEDED") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_max_exceeded"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'is_error' not available on result type
    end
  end

  describe "redirect_meta_refresh" do
    test "redirect_meta_refresh" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_meta_refresh"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_refresh_header" do
    test "redirect_refresh_header" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_REFRESH_HEADER") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_refresh_header"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
    end
  end

  describe "redirect_to_404" do
    test "redirect_to_404" do
      engine_config = "{\"respect_robots_txt\":false}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = System.get_env("MOCK_SERVER_REDIRECT_TO_404") || (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/redirect_to_404"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'final_url' not available on result type
      # skipped: field 'redirect_count' not available on result type
      # skipped: field 'is_error' not available on result type
    end
  end
end
