# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb03dc0b181d35e373fa913faf2f620f60ce2fbc7fa4dc6123ba14a7634e6540
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: stealth
defmodule E2e.StealthTest do
  use ExUnit.Case, async: false

  describe "stealth_ua_rotation_config" do
    test "stealth_ua_rotation_config" do
      engine_config = "{\"user_agents\":[\"Mozilla/5.0 (Windows NT 10.0)\",\"Chrome/120.0.0.0\"]}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/stealth_ua_rotation_config"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.status_code == 200
    end
  end

  describe "stealth_ua_rotation_round_robin" do
    test "stealth_ua_rotation_round_robin" do
      engine_config = "{\"max_depth\":1,\"max_pages\":3,\"user_agents\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) TestAgent-1\",\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) TestAgent-2\"]}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/stealth_ua_rotation_round_robin"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      # skipped: field 'pages.length' not available on result type
    end
  end

  describe "stealth_ua_rotation_single_domain" do
    test "stealth_ua_rotation_single_domain" do
      engine_config = "{\"max_depth\":0,\"stay_on_domain\":true,\"user_agents\":[\"Mozilla/5.0 TestBot/1.0 (+http://example.com/bot)\"]}"
      {:ok, engine} = Kreuzcrawl.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/stealth_ua_rotation_single_domain"
      {:ok, result} = Kreuzcrawl.scrape_async(engine, url)
      assert result.status_code == 200
      # skipped: field 'pages.length' not available on result type
    end
  end
end
