// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc01a1c094d3c52a5b52b4a912620f9a716410d5ef08dea3520ea2a80cd328ad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.crawlberg.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import io.xberg.crawlberg.CrawlConfig;
import io.xberg.crawlberg.Crawlberg;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/** E2e tests for category: content. */
public class ContentTest {
  private static final ObjectMapper MAPPER = new ObjectMapper()
      .registerModule(new Jdk8Module())
      .setPropertyNamingStrategy(
          com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE);

  @BeforeAll
  static void initEnv() {
    if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
      System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
    }
  }

  @Test
  void testContent204NoContent() throws Exception {
    // Handles 204 No Content response gracefully
    var engine = Crawlberg.createEngine(null);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_204_no_content";
    var result = Crawlberg.scrape(engine, url);
    assertEquals(204, result.statusCode());
    assertTrue(result.html().isEmpty(), "expected empty value");
  }

  @Test
  void testContentCharsetIso8859() throws Exception {
    // Handles ISO-8859-1 encoded page correctly
    var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_charset_iso8859";
    var result = Crawlberg.scrape(engine, url);
    assertEquals(
        "iso-8859-1",
        java.util.Optional.ofNullable(result.detectedCharset())
            .map(java.util.Objects::toString)
            .orElse("")
            .trim());
  }

  @Test
  void testContentEmptyBody() throws Exception {
    // Handles 200 response with empty body gracefully
    var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_empty_body";
    var result = Crawlberg.scrape(engine, url);
    assertEquals(200, result.statusCode());
  }

  @Test
  void testContentGzipCompressed() throws Exception {
    // Handles response with Accept-Encoding gzip negotiation
    var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_gzip_compressed";
    var result = Crawlberg.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
    assertEquals(200, result.statusCode());
  }

  @Test
  void testContentLargePageLimit() throws Exception {
    // Respects max body size limit and truncates or skips oversized pages
    var engineConfig = MAPPER.readValue(
        "{\"max_body_size\":1024,\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_large_page_limit";
    var result = Crawlberg.scrape(engine, url);
    assertTrue(result.bodySize() < 1025, "expected < 1025");
  }

  @Test
  void testContentMainOnly() throws Exception {
    // Extracts content with aggressive preprocessing, excluding nav, sidebar, footer
    var engineConfig = MAPPER.readValue(
        "{\"content\":{\"preprocessing_preset\":\"aggressive\"},\"respect_robots_txt\":false}",
        CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_main_only";
    var result = Crawlberg.scrape(engine, url);
  }

  @Test
  void testContentPdfNoExtension() throws Exception {
    // Detects PDF content by Content-Type header when URL has no .pdf extension
    var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_pdf_no_extension";
    var result = Crawlberg.scrape(engine, url);
    assertEquals(true, result.isPdf());
  }

  @Test
  void testContentRemoveTags() throws Exception {
    // Removes specified HTML elements by CSS selector before processing
    var engineConfig = MAPPER.readValue(
        "{\"remove_tags\":[\"nav\",\"aside\",\"footer\"],\"respect_robots_txt\":false}",
        CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_remove_tags";
    var result = Crawlberg.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
  }

  @Test
  void testContentUtf8Bom() throws Exception {
    // Handles UTF-8 content with BOM marker correctly
    var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
    var engine = Crawlberg.createEngine(engineConfig);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/content_utf8_bom";
    var result = Crawlberg.scrape(engine, url);
    assertEquals(
        "utf-8",
        java.util.Optional.ofNullable(result.detectedCharset())
            .map(java.util.Objects::toString)
            .orElse("")
            .trim());
    assertFalse(result.html().isEmpty(), "expected non-empty value");
  }
}
