// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3254b39f9e5169cce0caacc0ea8033f529cc4cf9269a69c09f2922a2de9995bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzcrawl;
using static Kreuzcrawl.KreuzcrawlLib;

namespace Kreuzcrawl
{
    /// <summary>E2e tests for category: crawl.</summary>
    public class CrawlTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_ContentBinarySkip()
        {
            // Skips image and video content types gracefully
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/content_binary_skip";
            var result = await KreuzcrawlLib.Scrape(engine, url);
    Assert.True(result.WasSkipped);

        }

        [Fact]
        public async Task Test_ContentPdfLinkSkip()
        {
            // Encounters PDF link and skips or marks as document type
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/content_pdf_link_skip";
            var result = await KreuzcrawlLib.Scrape(engine, url);
    Assert.True(result.WasSkipped);

        }

        [Fact]
        public async Task Test_CrawlConcurrentDepth()
        {
            // Concurrent crawl respects max_depth limit
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":3,\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_concurrent_depth";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'stayed_on_domain' not available on result type
        }

        [Fact]
        public async Task Test_CrawlConcurrentLimit()
        {
            // Respects max concurrent requests limit during crawl
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":2,\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_concurrent_limit";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlConcurrentMaxPages()
        {
            // Concurrent crawl respects max_pages budget
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":4,\"max_depth\":1,\"max_pages\":3,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_concurrent_max_pages";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlCustomHeaders()
        {
            // Sends custom headers on all crawl requests
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"custom_headers\":{\"Accept-Language\":\"en-US\",\"X-Custom-Header\":\"test-value\"},\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_custom_headers";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlDepthOne()
        {
            // Follows links one level deep from start page
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_depth_one";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'stayed_on_domain' not available on result type
        }

        [Fact]
        public async Task Test_CrawlDepthPriority()
        {
            // Crawls in breadth-first order, processing depth-0 pages before depth-1
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":2,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_depth_priority";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlDepthTwo()
        {
            // Crawls 3 levels deep (depth 0, 1, 2)
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":2,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_depth_two";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlDepthTwoChain()
        {
            // Depth=2 crawl follows a chain of links across three levels
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":2}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_depth_two_chain";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlDoubleSlashNormalization()
        {
            // Normalizes double slashes in URL paths (//page to /page)
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_double_slash_normalization";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'unique_urls.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlEmptyPageNoLinks()
        {
            // Crawl completes when child page has no outgoing links
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":2}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_empty_page_no_links";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlExcludePathPattern()
        {
            // Skips URLs matching the exclude path pattern
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"exclude_paths\":[\"/admin/.*\"],\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_exclude_path_pattern";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlExternalLinksIgnored()
        {
            // External links are discovered but not followed when stay_on_domain is true
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":1,\"stay_on_domain\":true}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_external_links_ignored";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'stayed_on_domain' not available on result type
        }

        [Fact]
        public async Task Test_CrawlFragmentStripping()
        {
            // Strips #fragment from URLs for deduplication
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_fragment_stripping";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'unique_urls.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlIncludePathPattern()
        {
            // Only follows URLs matching the include path pattern
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"include_paths\":[\"/blog/.*\"],\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_include_path_pattern";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlMaxDepthZero()
        {
            // max_depth=0 crawls only the seed page with no link following
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":0}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_max_depth_zero";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlMaxPages()
        {
            // Stops crawling at page budget limit
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_pages\":3,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_max_pages";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlMixedContentTypes()
        {
            // Crawl handles links to non-HTML content types gracefully
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":1}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_mixed_content_types";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlMultipleRedirectsInTraversal()
        {
            // Multiple linked pages with redirects are handled during crawl traversal
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":1}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var _pfUrl_url = Environment.GetEnvironmentVariable("MOCK_SERVER_CRAWL_MULTIPLE_REDIRECTS_IN_TRAVERSAL");
            var url = !string.IsNullOrEmpty(_pfUrl_url) ? _pfUrl_url : Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_multiple_redirects_in_traversal";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlQueryParamDedup()
        {
            // Deduplicates URLs with same query params in different order
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_query_param_dedup";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'unique_urls.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlRedirectInTraversal()
        {
            // Links that redirect are followed during crawl traversal
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":1}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var _pfUrl_url = Environment.GetEnvironmentVariable("MOCK_SERVER_CRAWL_REDIRECT_IN_TRAVERSAL");
            var url = !string.IsNullOrEmpty(_pfUrl_url) ? _pfUrl_url : Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_redirect_in_traversal";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlSelfLinkNoLoop()
        {
            // Page linking to itself does not cause infinite crawl loop
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_concurrent\":1,\"max_depth\":1}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_self_link_no_loop";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlSinglePageNoLinks()
        {
            // Crawling a page with no links returns only the seed page
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":2}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_single_page_no_links";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlStayOnDomain()
        {
            // Does not follow external links when stay_on_domain is true
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false,\"stay_on_domain\":true}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_stay_on_domain";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'stayed_on_domain' not available on result type
        }

        [Fact]
        public async Task Test_CrawlSubdomainExclusion()
        {
            // Stays on exact domain and skips subdomain links
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"allow_subdomains\":false,\"max_depth\":1,\"respect_robots_txt\":false,\"stay_on_domain\":true}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_subdomain_exclusion";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type        // skipped: field 'stayed_on_domain' not available on result type
        }

        [Fact]
        public async Task Test_CrawlSubdomainInclusion()
        {
            // Crawls subdomains when allow_subdomains is enabled
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"allow_subdomains\":true,\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_subdomain_inclusion";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlTrailingSlashDedup()
        {
            // Deduplicates /page and /page/ as the same URL
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_trailing_slash_dedup";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'unique_urls.length' not available on result type
        }

        [Fact]
        public async Task Test_CrawlUrlDeduplication()
        {
            // Deduplicates URLs that differ only by fragment or query params
            var engineConfig = JsonSerializer.Deserialize<CrawlConfig>("{\"max_depth\":1,\"respect_robots_txt\":false}", ConfigOptions)!;
            var engine = KreuzcrawlLib.CreateEngine(engineConfig);
            var url = Environment.GetEnvironmentVariable("MOCK_SERVER_URL") + "/fixtures/crawl_url_deduplication";
            var result = await KreuzcrawlLib.Scrape(engine, url);
            // skipped: field 'pages.length' not available on result type
        }


    }
}
