# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb48077729ec4754b6fb3ee0fc50e083f9e26e5c75a7f6fc8fa7f080658f2531
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ArticleMetadata do
  @moduledoc "Article metadata extracted from `article:*` Open Graph tags."

  defstruct published_time: "",
            modified_time: "",
            author: "",
            section: "",
            tags: []
end
