# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ba927fedb193da697a0c28a4daac1722416be2cd8934e54222921ac9084b0c3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Kreuzcrawl-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
