# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72558e3430fe432c0d196559cdd4f37d88e83d0ce5f9df21ac48756b891a02cb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Kreuzcrawl-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
