# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:627df458d99f198411c8a1236750ee49e27550d736add77533745144f6e9b565
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.BrowserConfig do
  @moduledoc "Browser fallback configuration."

  @typedoc "Browser fallback configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          backend: String.t() | nil,
          endpoint: String.t() | nil,
          timeout: non_neg_integer(),
          wait: String.t() | nil,
          wait_selector: String.t() | nil,
          extra_wait: non_neg_integer() | nil,
          stealth: boolean(),
          proxy: map() | nil,
          block_url_patterns: [String.t()],
          eval_script: String.t() | nil,
          robots_user_agent: String.t() | nil,
          capture_network_events: boolean()
        }

  defstruct mode: :auto,
            backend: :chromiumoxide,
            endpoint: nil,
            timeout: 30_000,
            wait: :network_idle,
            wait_selector: nil,
            extra_wait: nil,
            stealth: false,
            proxy: nil,
            block_url_patterns: [],
            eval_script: nil,
            robots_user_agent: nil,
            capture_network_events: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
