# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a51ab2ff8c1572afa532410ae5910674adf22744a2540d453879b03abff63781
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzcrawl.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          domain: String.t() | nil,
          path: String.t() | nil
        }

  defstruct name: nil,
            value: nil,
            domain: nil,
            path: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
