# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:982f58eb9282aa661e1f38fb23a84a0878503f6e0db1253bf3e7f9c0949ad25a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  defstruct name: "",
            value: "",
            domain: "",
            path: ""
end
