# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f339ee58bf166931f45e9b2077dcb4db9bd7a6d715dc3c13261da9e136d4b4f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.DownloadedAsset do
  @moduledoc "A downloaded asset from a page."

  @type t :: %__MODULE__{
          url: String.t() | nil,
          content_hash: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer(),
          asset_category: String.t() | nil,
          html_tag: String.t() | nil
        }

  defstruct url: nil,
            content_hash: nil,
            mime_type: nil,
            size: 0,
            asset_category: :image,
            html_tag: nil
end
