# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3d333248d4bba1b4803198fda1afed8adcd86ced3bfab4a8ddcf4094c5056f16
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.DownloadedAsset do
  @moduledoc "A downloaded asset from a page."

  defstruct url: "",
            content_hash: "",
            mime_type: "",
            size: 0,
            asset_category: :image,
            html_tag: ""
end
