# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba38af1cb8741e4f3841dd66c2861e4cdd146c375d4b87359f97f44b3a8d2438
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzcrawl.ExtractionMeta do
  @moduledoc "Metadata about an LLM extraction pass."

  @typedoc "Metadata about an LLM extraction pass."
  @type t :: %__MODULE__{
          cost: float() | nil,
          prompt_tokens: non_neg_integer() | nil,
          completion_tokens: non_neg_integer() | nil,
          model: String.t() | nil,
          chunks_processed: non_neg_integer()
        }

  defstruct cost: nil,
            prompt_tokens: nil,
            completion_tokens: nil,
            model: nil,
            chunks_processed: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
