# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c97bf7763a99579a9bf195b4fed65aa1bcb1090f6b81d8c4f375743cc63960c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.FaviconInfo do
  @moduledoc "Information about a favicon or icon link."

  defstruct url: "",
            rel: "",
            sizes: "",
            mime_type: ""
end
