# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6ec063724487c30cefb9b18b86f8c42ae41ccb64a289aa93928e71dd96bb354b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.HeadingInfo do
  @moduledoc "A heading element extracted from the page."

  defstruct level: 0,
            text: ""
end
