# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba70a01a586541dccdbf38c838198188e996eca59bb24d2648a980aeec0bcfbc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.HreflangEntry do
  @moduledoc "An hreflang alternate link entry."

  @typedoc "An hreflang alternate link entry."
  @type t :: %__MODULE__{
          lang: String.t() | nil,
          url: String.t() | nil
        }

  defstruct lang: nil,
            url: nil
end
