# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb5ef773b82ae3f7fd31d9f321e52d3d13e7e043bc3e53cb9a495e09921de614
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ImageInfo do
  @moduledoc "Information about an image found on a page."

  defstruct url: "",
            alt: "",
            width: 0,
            height: 0,
            source: :img
end
