# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a78bf0c2777b1a8e9570cbb68de04e0d50454bc856f80a5ae470abc3dca3fd29
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.ImageInfo do
  @moduledoc "Information about an image found on a page."

  @typedoc "Information about an image found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          alt: String.t() | nil,
          width: non_neg_integer() | nil,
          height: non_neg_integer() | nil,
          source: String.t() | nil
        }

  defstruct url: nil,
            alt: nil,
            width: nil,
            height: nil,
            source: :img

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
