# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb58373a6afe22f0d403287dc9f29e308e42bac427a68afee7aa2f11bb597f48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.JsonLdEntry do
  @moduledoc "A JSON-LD structured data entry found on a page."

  @typedoc "A JSON-LD structured data entry found on a page."
  @type t :: %__MODULE__{
          schema_type: String.t() | nil,
          name: String.t() | nil,
          raw: String.t() | nil
        }

  defstruct schema_type: nil,
            name: nil,
            raw: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
