# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a372093a5312fe597652931a276c589e93c507d3c4f2cce756f5b9ecd0ea1da4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.LinkInfo do
  @moduledoc "Information about a link found on a page."

  defstruct url: "",
            text: "",
            link_type: :internal,
            rel: "",
            nofollow: false
end
