# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b77a9cb2a85dc39c0291e44b961a33680e408e03aec0e385f12100b3f17108e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.LinkType do
  @moduledoc "The classification of a link."

  @type t :: :internal | :external | :anchor | :document

  @internal :internal
  @external :external
  @anchor :anchor
  @document :document

  @spec internal() :: t()
  def internal, do: @internal
  @spec external() :: t()
  def external, do: @external
  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec document() :: t()
  def document, do: @document
end
