# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8198d0b32361ac078e65a08979ac1179628882de1969d6ec407d69bb82d23c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.LinkInfo do
  @moduledoc "Information about a link found on a page."

  defstruct url: "",
            text: "",
            link_type: :internal,
            rel: "",
            nofollow: false
end
