# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b00cca269004c70455b5d1d27ccca88fd0d1e6d8eb32938e29376ff0c4836691
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzcrawl.LinkInfo do
  @moduledoc "Information about a link found on a page."

  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          link_type: String.t() | nil,
          rel: String.t() | nil,
          nofollow: boolean()
        }

  defstruct url: nil,
            text: nil,
            link_type: :internal,
            rel: nil,
            nofollow: false
end
