# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92094be909eaa8d7a849e5e509f7bfa38e1f8ffa645d629a39e005c4a93526ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzcrawl
  VERSION = '0.3.0.pre.rc.7'
end
