// Code generated by kreuzcrawl-e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

use e2e_rust::helpers;

#[tokio::test]
async fn test_cookies_per_domain() {
    // Isolates cookies per domain during crawl
    let mock = helpers::setup_mock_server().await;
    let body_0 = "<html><body><a href=\"/local\">Local</a></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/",
        200,
        &[
            ("content-type", "text/html; charset=utf-8"),
            ("set-cookie", "domain_cookie=value1; Path=/"),
        ],
        &body_0,
    )
    .await;
    let body_1 = "<html><body><h1>Local Page</h1></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/local",
        200,
        &[("content-type", "text/html; charset=utf-8")],
        &body_1,
    )
    .await;

    let config = kreuzcrawl::CrawlConfig {
        max_depth: Some(1),
        respect_robots_txt: false,
        cookies_enabled: true,
        ..Default::default()
    };

    let result = kreuzcrawl::crawl(&mock.uri(), &config).await;
    let result = result.expect("request should succeed");
    assert_eq!(result.cookies.len(), 1);
    assert!(result.cookies.iter().any(|c| c.name == "domain_cookie"));
}

#[tokio::test]
async fn test_cookies_persistence() {
    // Maintains cookies across multiple crawl requests
    let mock = helpers::setup_mock_server().await;
    let body_0 = "<html><body><a href=\"/page2\">Page 2</a></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/",
        200,
        &[
            ("content-type", "text/html; charset=utf-8"),
            ("set-cookie", "session=abc123; Path=/"),
        ],
        &body_0,
    )
    .await;
    let body_1 = "<html><body><h1>Page 2</h1></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/page2",
        200,
        &[("content-type", "text/html; charset=utf-8")],
        &body_1,
    )
    .await;

    let config = kreuzcrawl::CrawlConfig {
        max_depth: Some(1),
        respect_robots_txt: false,
        cookies_enabled: true,
        ..Default::default()
    };

    let result = kreuzcrawl::crawl(&mock.uri(), &config).await;
    let result = result.expect("request should succeed");
    assert!(result.cookies.iter().any(|c| c.name == "session"));
}

#[tokio::test]
async fn test_cookies_set_cookie_response() {
    // Respects Set-Cookie header from server responses
    let mock = helpers::setup_mock_server().await;
    let body_0 = "<html><body><a href=\"/next\">Next</a></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/",
        200,
        &[
            ("content-type", "text/html; charset=utf-8"),
            ("set-cookie", "tracking=xyz789; Path=/; HttpOnly"),
        ],
        &body_0,
    )
    .await;
    let body_1 = "<html><body><h1>Next Page</h1></body></html>".to_owned();
    helpers::register_mock(
        &mock,
        "GET",
        "/next",
        200,
        &[("content-type", "text/html; charset=utf-8")],
        &body_1,
    )
    .await;

    let config = kreuzcrawl::CrawlConfig {
        max_depth: Some(1),
        respect_robots_txt: false,
        cookies_enabled: true,
        ..Default::default()
    };

    let result = kreuzcrawl::crawl(&mock.uri(), &config).await;
    let result = result.expect("request should succeed");
    assert!(result.cookies.iter().any(|c| c.name == "tracking"));
}
