// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fe5337c4bde99ef92e7919a22279adb51e71bed18e93fee81f65f90927a602e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: rate_limit

use kreuzcrawl::create_engine;
use kreuzcrawl::CrawlConfig;
use kreuzcrawl::{crawl, scrape};
mod common;
mod mock_server;
#[allow(unused_imports)]
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_rate_limit_adaptive_backoff() {
    // Exponential backoff retry succeeds after 429 Too Many Requests
    let engine_config: CrawlConfig =
        serde_json::from_str("{\"respect_robots_txt\":false,\"retry_codes\":[429],\"retry_count\":2}")
            .expect("config should parse");
    let engine = create_engine(Some(engine_config)).expect("handle creation should succeed");
    let url = std::env::var("MOCK_SERVER_RATE_LIMIT_ADAPTIVE_BACKOFF").unwrap_or_else(|_| {
        let _ = common::mock_server_url();
        std::env::var("MOCK_SERVER_RATE_LIMIT_ADAPTIVE_BACKOFF").unwrap_or_else(|_| {
            format!(
                "{}/fixtures/{}",
                common::mock_server_url(),
                "rate_limit_adaptive_backoff"
            )
        })
    });
    let result = scrape(&engine, &url).await.expect("should succeed");
    assert_eq!(result.status_code, 200, "equals assertion failed");
}

#[tokio::test]
async fn test_rate_limit_basic_delay() {
    // Rate limiter adds delay between requests to the same domain
    let engine_config: CrawlConfig = serde_json::from_str("{\"max_depth\":1}").expect("config should parse");
    let engine = create_engine(Some(engine_config)).expect("handle creation should succeed");
    let url = std::env::var("MOCK_SERVER_RATE_LIMIT_BASIC_DELAY").unwrap_or_else(|_| {
        let _ = common::mock_server_url();
        std::env::var("MOCK_SERVER_RATE_LIMIT_BASIC_DELAY")
            .unwrap_or_else(|_| format!("{}/fixtures/{}", common::mock_server_url(), "rate_limit_basic_delay"))
    });
    let result = crawl(&engine, &url).await.expect("should succeed");
    assert_eq!(
        result.pages.len(),
        3,
        "expected exactly 3 elements, got {}",
        result.pages.len()
    );
    // skipped: field 'rate_limit.min_duration_ms' not available on result type
}

#[tokio::test]
async fn test_rate_limit_per_domain() {
    // Per-domain rate limiting applies delay between requests to same domain
    let engine_config: CrawlConfig =
        serde_json::from_str("{\"max_concurrent\":1,\"max_depth\":1}").expect("config should parse");
    let engine = create_engine(Some(engine_config)).expect("handle creation should succeed");
    let url = std::env::var("MOCK_SERVER_RATE_LIMIT_PER_DOMAIN").unwrap_or_else(|_| {
        let _ = common::mock_server_url();
        std::env::var("MOCK_SERVER_RATE_LIMIT_PER_DOMAIN")
            .unwrap_or_else(|_| format!("{}/fixtures/{}", common::mock_server_url(), "rate_limit_per_domain"))
    });
    let result = crawl(&engine, &url).await.expect("should succeed");
    assert!(result.pages.len() >= 2, "expected >= 2");
    assert_eq!(result.pages[0].status_code, 200, "equals assertion failed");
}

#[tokio::test]
async fn test_rate_limit_robots_crawl_delay() {
    // Respects Crawl-delay directive in robots.txt
    let engine_config: CrawlConfig =
        serde_json::from_str("{\"max_depth\":1,\"respect_robots_txt\":true,\"user_agent\":\"TestBot\"}")
            .expect("config should parse");
    let engine = create_engine(Some(engine_config)).expect("handle creation should succeed");
    let url = std::env::var("MOCK_SERVER_RATE_LIMIT_ROBOTS_CRAWL_DELAY").unwrap_or_else(|_| {
        let _ = common::mock_server_url();
        std::env::var("MOCK_SERVER_RATE_LIMIT_ROBOTS_CRAWL_DELAY").unwrap_or_else(|_| {
            format!(
                "{}/fixtures/{}",
                common::mock_server_url(),
                "rate_limit_robots_crawl_delay"
            )
        })
    });
    let result = crawl(&engine, &url).await.expect("should succeed");
    assert!(!result.pages.is_empty(), "expected >= 1");
    assert_eq!(result.pages[0].status_code, 200, "equals assertion failed");
}

#[tokio::test]
async fn test_rate_limit_zero_no_delay() {
    // Rate limiter with zero delay does not slow crawling
    let engine_config: CrawlConfig = serde_json::from_str("{\"max_depth\":1}").expect("config should parse");
    let engine = create_engine(Some(engine_config)).expect("handle creation should succeed");
    let url = std::env::var("MOCK_SERVER_RATE_LIMIT_ZERO_NO_DELAY").unwrap_or_else(|_| {
        let _ = common::mock_server_url();
        std::env::var("MOCK_SERVER_RATE_LIMIT_ZERO_NO_DELAY")
            .unwrap_or_else(|_| format!("{}/fixtures/{}", common::mock_server_url(), "rate_limit_zero_no_delay"))
    });
    let result = crawl(&engine, &url).await.expect("should succeed");
    assert_eq!(
        result.pages.len(),
        2,
        "expected exactly 2 elements, got {}",
        result.pages.len()
    );
}
