// Generated by alef. Do not edit by hand.

package dev.kreuzberg.kreuzcrawl.android

/** Result of citation conversion. */
data class CitationResult(
    /** Markdown with links replaced by numbered citations. */
    val content: String,
    /** Numbered reference list: (index, url, text). */
    val references: List<CitationReference>,
)
