// Generated by alef. Do not edit by hand.
// alef:hash:a51ab2ff8c1572afa532410ae5910674adf22744a2540d453879b03abff63781
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.kreuzcrawl.android

/** The type of a feed (RSS, Atom, or JSON Feed). */
enum class FeedType {
    /** RSS feed. */
    @com.fasterxml.jackson.annotation.JsonProperty("rss") RSS,
    /** Atom feed. */
    @com.fasterxml.jackson.annotation.JsonProperty("atom") ATOM,
    /** JSON Feed. */
    @com.fasterxml.jackson.annotation.JsonProperty("json_feed") JSON_FEED;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            RSS -> "rss"
            ATOM -> "atom"
            JSON_FEED -> "json_feed"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): FeedType =
            when (value) {
                "rss" -> RSS
                "atom" -> ATOM
                "json_feed" -> JSON_FEED
                else -> throw IllegalArgumentException("Unknown FeedType value: $value")
            }
    }
}
