// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
)

package dev.kreuzberg.kreuzcrawl.android

import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

object Kreuzcrawl {
    private val mapper = jacksonObjectMapper()

    /**
     * Convert markdown links to numbered citations.
     *
     * `[Example](https://example.com)` becomes `Example[1]` with `[1]: https://example.com` in the
     * reference list. Images `![alt](url)` are preserved unchanged.
     */
    fun generateCitations(markdown: String): CitationResult {
        val resultJson = KreuzcrawlBridge.nativeGenerateCitations(markdown)
        return mapper.readValue(resultJson, CitationResult::class.java)
    }

    /**
     * Convert markdown links to numbered citations.
     *
     * `[Example](https://example.com)` becomes `Example[1]` with `[1]: https://example.com` in the
     * reference list. Images `![alt](url)` are preserved unchanged.
     */
    suspend fun generateCitationsAsync(markdown: String): CitationResult =
        withContext(Dispatchers.IO) { generateCitations(markdown) }

    /**
     * Create a new crawl engine with the given configuration.
     *
     * If `config` is `null`, uses `CrawlConfig.default()`. Returns an error if the configuration is
     * invalid.
     */
    fun createEngine(config: CrawlConfig? = null): CrawlEngineHandle =
        CrawlEngineHandle(
            KreuzcrawlBridge.nativeCreateEngine(config?.let { mapper.writeValueAsString(it) } ?: "")
        )

    /** Scrape a single URL, returning extracted page data. */
    fun scrape(engine: CrawlEngineHandle, url: String): ScrapeResult {
        val resultJson = KreuzcrawlBridge.nativeScrape(engine.handle, url)
        return mapper.readValue(resultJson, ScrapeResult::class.java)
    }

    /** Scrape a single URL, returning extracted page data. */
    suspend fun scrapeAsync(engine: CrawlEngineHandle, url: String): ScrapeResult =
        withContext(Dispatchers.IO) { scrape(engine, url) }

    /** Crawl a website starting from `url`, following links up to the configured depth. */
    fun crawl(engine: CrawlEngineHandle, url: String): CrawlResult {
        val resultJson = KreuzcrawlBridge.nativeCrawl(engine.handle, url)
        return mapper.readValue(resultJson, CrawlResult::class.java)
    }

    /** Crawl a website starting from `url`, following links up to the configured depth. */
    suspend fun crawlAsync(engine: CrawlEngineHandle, url: String): CrawlResult =
        withContext(Dispatchers.IO) { crawl(engine, url) }

    /** Discover all pages on a website by following links and sitemaps. */
    fun mapUrls(engine: CrawlEngineHandle, url: String): MapResult {
        val resultJson = KreuzcrawlBridge.nativeMapUrls(engine.handle, url)
        return mapper.readValue(resultJson, MapResult::class.java)
    }

    /** Discover all pages on a website by following links and sitemaps. */
    suspend fun mapUrlsAsync(engine: CrawlEngineHandle, url: String): MapResult =
        withContext(Dispatchers.IO) { mapUrls(engine, url) }

    /** Execute browser actions on a single page. */
    fun interact(
        engine: CrawlEngineHandle,
        url: String,
        actions: List<PageAction>,
    ): InteractionResult {
        val resultJson =
            KreuzcrawlBridge.nativeInteract(engine.handle, url, mapper.writeValueAsString(actions))
        return mapper.readValue(resultJson, InteractionResult::class.java)
    }

    /** Execute browser actions on a single page. */
    suspend fun interactAsync(
        engine: CrawlEngineHandle,
        url: String,
        actions: List<PageAction>,
    ): InteractionResult = withContext(Dispatchers.IO) { interact(engine, url, actions) }

    /** Scrape multiple URLs concurrently. */
    fun batchScrape(engine: CrawlEngineHandle, urls: List<String>): List<BatchScrapeResult> {
        val resultJson =
            KreuzcrawlBridge.nativeBatchScrape(engine.handle, mapper.writeValueAsString(urls))
        return mapper.readValue(resultJson, object : TypeReference<List<BatchScrapeResult>>() {})
    }

    /** Scrape multiple URLs concurrently. */
    suspend fun batchScrapeAsync(
        engine: CrawlEngineHandle,
        urls: List<String>,
    ): List<BatchScrapeResult> = withContext(Dispatchers.IO) { batchScrape(engine, urls) }

    /** Crawl multiple seed URLs concurrently, each following links to configured depth. */
    fun batchCrawl(engine: CrawlEngineHandle, urls: List<String>): List<BatchCrawlResult> {
        val resultJson =
            KreuzcrawlBridge.nativeBatchCrawl(engine.handle, mapper.writeValueAsString(urls))
        return mapper.readValue(resultJson, object : TypeReference<List<BatchCrawlResult>>() {})
    }

    /** Crawl multiple seed URLs concurrently, each following links to configured depth. */
    suspend fun batchCrawlAsync(
        engine: CrawlEngineHandle,
        urls: List<String>,
    ): List<BatchCrawlResult> = withContext(Dispatchers.IO) { batchCrawl(engine, urls) }
}
