// Generated by alef. Do not edit by hand.

package dev.kreuzberg.kreuzcrawl.android

/** The classification of a link. */
enum class LinkType {
    /** A link to the same domain. */
    INTERNAL,
    /** A link to a different domain. */
    EXTERNAL,
    /** A fragment-only link (e.g., `#section`). */
    ANCHOR,
    /** A link to a downloadable document (PDF, DOC, etc.). */
    DOCUMENT,
}
