<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b65ef3b7bb21557243ac509edbae13a2cc6da7a2d109b0283fa4cc005be39cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzcrawl\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzcrawl\Kreuzcrawl;
use Kreuzcrawl\CrawlConfig;
use Kreuzcrawl\CrawlStreamRequest;

/** E2e tests for category: engine. */
final class EngineTest extends TestCase
{
    /** CrawlEngine with defaults batch scrapes like the free function */
    public function test_engine_batch_basic(): void
    {
        $engine = Kreuzcrawl::createEngine(null);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/engine_batch_basic';
        $this->expectNotToPerformAssertions();
        $result = Kreuzcrawl::scrape($engine, $url);

        // skipped: field 'batch.completed_count' not available on result type        // skipped: field 'batch.total_count' not available on result type
    }


    /** CrawlEngine with defaults crawls multiple pages like the free function */
    public function test_engine_crawl_basic(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["maxDepth" => 1]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_ENGINE_CRAWL_BASIC') ?: getenv('MOCK_SERVER_URL') . '/fixtures/engine_crawl_basic';
        $result = Kreuzcrawl::crawl($engine, $url);
        $pages = $result->getPages();

        $this->assertCount(3, $pages);
        $this->assertGreaterThanOrEqual(3, count($pages));

    }


    /** CrawlEngine with defaults discovers URLs like the free function */
    public function test_engine_map_basic(): void
    {
        $engine = Kreuzcrawl::createEngine(null);
        $url = getenv('MOCK_SERVER_ENGINE_MAP_BASIC') ?: getenv('MOCK_SERVER_URL') . '/fixtures/engine_map_basic';
        $this->expectNotToPerformAssertions();
        $result = Kreuzcrawl::mapUrls($engine, $url);

        // skipped: field 'map.min_urls' not available on result type
    }


    /** CrawlEngine with defaults scrapes a page identically to the free function */
    public function test_engine_scrape_basic(): void
    {
        $engine = Kreuzcrawl::createEngine(null);
        $url = getenv('MOCK_SERVER_ENGINE_SCRAPE_BASIC') ?: getenv('MOCK_SERVER_URL') . '/fixtures/engine_scrape_basic';
        $result = Kreuzcrawl::scrape($engine, $url);

        $this->assertEquals(200, $result->statusCode);
        $this->assertEquals("text/html", trim($result->contentType));
        $this->assertEquals("Engine Test", trim(($result->getMetadata()->title ?? null)));
        $this->assertStringContainsString("Testing the engine", ($result->getMetadata()->description ?? null));
        $this->assertGreaterThanOrEqual(1, count($result->getLinks()));
        $this->assertGreaterThanOrEqual(1, count($result->getMetadata()->getHeadings()));

    }


    /** CrawlEngine with defaults streams events like the free function */
    public function test_engine_stream_basic(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["maxDepth" => 1]));
        $engine = Kreuzcrawl::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_ENGINE_STREAM_BASIC') ?: getenv('MOCK_SERVER_URL') . '/fixtures/engine_stream_basic';
        $url_req = new CrawlStreamRequest($url);
        $result = $engine->crawlStream($url_req);
        $__camel = function ($v) use (&$__camel) {
            if (is_array($v)) {
                $out = [];
                foreach ($v as $k => $vv) {
                    $key = is_string($k) ? lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $k)))) : $k;
                    $out[$key] = $__camel($vv);
                } return (array_keys($out) === range(0, count($out) - 1)) ? $out : (object) $out;
            } if (is_object($v)) {
                $out = new \stdClass();
                foreach (get_object_vars($v) as $k => $vv) {
                    $key = lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $k))));
                    $out->{$key} = $__camel($vv);
                } return $out;
            } return $v;
        };
        $__decode_chunk = fn ($c) => $__camel(is_string($c) ? json_decode($c, true) : (is_array($c) || is_object($c) ? json_decode(json_encode($c), true) : $c));
        $chunks = is_string($result) ? array_map($__decode_chunk, (array)(json_decode($result, true) ?: [])) : (is_array($result) ? array_map($__decode_chunk, $result) : array_map($__decode_chunk, iterator_to_array($result)));

        $this->assertGreaterThanOrEqual(3, count($chunks));

    }

}
