// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1dd20e5f8a1b41f9529cd62bb9747b8f97bc6c473a20dc3fe6c9148c61f33a72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Article metadata extracted from {@code article:*} Open Graph tags.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ArticleMetadata.Builder.class)
public record ArticleMetadata(
    /**
     * The article publication time.
     */
    @Nullable @JsonProperty("published_time") String publishedTime,
    /**
     * The article modification time.
     */
    @Nullable @JsonProperty("modified_time") String modifiedTime,
    /**
     * The article author.
     */
    @Nullable String author,
    /**
     * The article section.
     */
    @Nullable String section,
    /**
     * The article tags.
     */
    List<String> tags
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("published_time")
        private Optional<String> publishedTime = Optional.empty();
        @JsonProperty("modified_time")
        private Optional<String> modifiedTime = Optional.empty();
        @JsonProperty("author")
        private Optional<String> author = Optional.empty();
        @JsonProperty("section")
        private Optional<String> section = Optional.empty();
        @JsonProperty("tags")
        private List<String> tags = List.of();

        /** Sets the publishedTime field. */
        @JsonProperty("published_time")
        public Builder withPublishedTime(final @Nullable String value) {
            this.publishedTime = Optional.ofNullable(value);
            return this;
        }

        /** Sets the modifiedTime field. */
        @JsonProperty("modified_time")
        public Builder withModifiedTime(final @Nullable String value) {
            this.modifiedTime = Optional.ofNullable(value);
            return this;
        }

        /** Sets the author field. */
        @JsonProperty("author")
        public Builder withAuthor(final @Nullable String value) {
            this.author = Optional.ofNullable(value);
            return this;
        }

        /** Sets the section field. */
        @JsonProperty("section")
        public Builder withSection(final @Nullable String value) {
            this.section = Optional.ofNullable(value);
            return this;
        }

        /** Sets the tags field. */
        @JsonProperty("tags")
        public Builder withTags(final List<String> value) {
            this.tags = value;
            return this;
        }

        /** Builds the ArticleMetadata instance. */
        public ArticleMetadata build() {
            return new ArticleMetadata(
                publishedTime.orElse(null),
                modifiedTime.orElse(null),
                author.orElse(null),
                section.orElse(null),
                tags
            );
        }
    }
    // CPD-ON
}
