// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23f89d208d722679f63c61a2da42e50197f2c8feba85dae9bf91b39e614cb7bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;

/**
 * Result from a single URL in a batch crawl operation.
 */
public class BatchCrawlResultBuilder {

	private String url = "";
	private Optional<CrawlResult> result = Optional.empty();
	private Optional<String> error = Optional.empty();

	/** Sets the url field. */
	public BatchCrawlResultBuilder withUrl(final String value) {
		this.url = value;
		return this;
	}

	/** Sets the result field. */
	public BatchCrawlResultBuilder withResult(final Optional<CrawlResult> value) {
		this.result = value;
		return this;
	}

	/** Sets the error field. */
	public BatchCrawlResultBuilder withError(final Optional<String> value) {
		this.error = value;
		return this;
	}

	/** Builds the BatchCrawlResult instance. */
	public BatchCrawlResult build() {
		return new BatchCrawlResult(url, result, error);
	}
}
