// DO NOT EDIT - auto-generated by alef
// alef:hash:8b715a92d8f7e00abc0f5ad99eb17c63cda2ab5b6932f99af1336aae814ba6df
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser page load or rendering timed out.
 */
public class BrowserTimeoutException extends CrawlErrorException {
  /** Creates a new BrowserTimeoutException with the given message. */
  public BrowserTimeoutException(final String message) {
    super(message);
  }

  /** Creates a new BrowserTimeoutException with the given message and cause. */
  public BrowserTimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
