// DO NOT EDIT - auto-generated by alef
// alef:hash:1b8133c651d50b545b9af5f9327fdb12c0fa8433650afdda529be90b6337c810
package dev.kreuzberg.kreuzcrawl;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
    /** Creates a new BrowserErrorException with the given message. */
    public BrowserErrorException(final String message) {
        super(message);
    }

    /** Creates a new BrowserErrorException with the given message and cause. */
    public BrowserErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
