// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1c734fe0bebc5e4a0f8eaa3d8b99e351c01df94b5a6a0aa401900f1a0f8c6c32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Browser backend used for JavaScript rendering.
 */
@SuppressWarnings("PMD")
public enum BrowserBackend {
  /**
   * Existing Chromium/CDP backend powered by chromiumoxide.
   */
  Chromiumoxide("chromiumoxide"),
  /**
   * Kreuzcrawl-owned native browser backend derived from Obscura.
   */
  Native("native");

  /** The string value. */
  private final String value;

  BrowserBackend(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static BrowserBackend fromValue(final String value) {
    for (BrowserBackend e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown BrowserBackend value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
