// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6017696fc4488c841563dc2f16b1eb53ceae6b2045edbe8606fb7a7a1299559c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Result of citation conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CitationResultBuilder.class)
public record CitationResult(String content, List<CitationReference> references) {
    public static CitationResultBuilder builder() {
        return new CitationResultBuilder();
    }

    /**
     * Parse a {@code CitationResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzcrawlRsException if the JSON cannot be deserialised.
     */
    public static CitationResult fromJson(String json) throws KreuzcrawlRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, CitationResult.class);
        } catch (Exception e) {
            throw new KreuzcrawlRsException("Failed to parse CitationResult from JSON: " + e.getMessage(), e);
        }
    }
}
