// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ba927fedb193da697a0c28a4daac1722416be2cd8934e54222921ac9084b0c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Content extraction and conversion configuration.
 *
 * Controls how HTML is converted to the output format. Uses
 * html-to-markdown-rs as the conversion engine for all formats
 * (markdown, plain text, djot).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ContentConfig.Builder.class)
public record ContentConfig(
    /**
     * Output format: {@code "markdown"} (default), {@code "plain"}, {@code "djot"}.
     */
    @JsonProperty("output_format") String outputFormat,
    /**
     * Preprocessing aggressiveness: {@code "minimal"}, {@code "standard"} (default), {@code "aggressive"}.
     *
     * - Minimal: only scripts/styles removed.
     * - Standard: also removes nav, nav-hinted headers/footers/asides, forms.
     * - Aggressive: removes all footers/asides unconditionally.
     */
    @JsonProperty("preprocessing_preset") String preprocessingPreset,
    /**
     * Remove navigation elements (nav, breadcrumbs, menus). Default: {@code true}.
     */
    @JsonProperty("remove_navigation") boolean removeNavigation,
    /**
     * Remove form elements. Default: {@code true}.
     */
    @JsonProperty("remove_forms") boolean removeForms,
    /**
     * HTML tag names to strip (render children only, remove the tag wrapper).
     * Default: {@code ["noscript"]}.
     */
    @Nullable @JsonProperty("strip_tags") List<String> stripTags,
    /**
     * HTML tag names to preserve as raw HTML in output.
     */
    @Nullable @JsonProperty("preserve_tags") List<String> preserveTags,
    /**
     * CSS selectors for elements to exclude entirely (element + all content).
     *
     * Unlike {@code strip_tags} (which removes the wrapper but keeps children),
     * excluded elements and all descendants are dropped. Supports CSS selectors:
     * {@code .class}, {@code #id}, {@code [attribute]}, compound selectors.
     *
     * Example: {@code [".cookie-banner", "#ad-container", "[role='complementary']"]}
     */
    @Nullable @JsonProperty("exclude_selectors") List<String> excludeSelectors,
    /**
     * Skip image elements in output. Default: {@code false}.
     */
    @JsonProperty("skip_images") boolean skipImages,
    /**
     * Max DOM traversal depth. Prevents stack overflow on deeply nested HTML.
     */
    @Nullable @JsonProperty("max_depth") Long maxDepth,
    /**
     * Enable line wrapping. Default: {@code false}.
     */
    @JsonProperty("wrap") boolean wrap,
    /**
     * Wrap width when {@code wrap} is enabled. Default: {@code 80}.
     */
    @JsonProperty("wrap_width") long wrapWidth,
    /**
     * Include document structure tree in output. Default: {@code true}.
     */
    @JsonProperty("include_document_structure") boolean includeDocumentStructure
) {
    public static Builder builder() {
        return new Builder();
    }
    public ContentConfig{
        if (wrapWidth == 0) wrapWidth = 80;
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("output_format")
private String outputFormat = "markdown";
        @JsonProperty("preprocessing_preset")
private String preprocessingPreset = "standard";
        @JsonProperty("remove_navigation")
private boolean removeNavigation = true;
        @JsonProperty("remove_forms")
private boolean removeForms = true;
        @JsonProperty("strip_tags")
private List<String> stripTags = null;
        @JsonProperty("preserve_tags")
private List<String> preserveTags = null;
        @JsonProperty("exclude_selectors")
private List<String> excludeSelectors = null;
        @JsonProperty("skip_images")
private boolean skipImages = false;
        @JsonProperty("max_depth")
private Long maxDepth = null;
private boolean wrap = false;
        @JsonProperty("wrap_width")
private long wrapWidth = 0;
        @JsonProperty("include_document_structure")
private boolean includeDocumentStructure = true;

        /** Sets the outputFormat field. */
        @JsonProperty("output_format")
        public Builder withOutputFormat(final String value) {
            this.outputFormat = value;
            return this;
        }

        /** Sets the preprocessingPreset field. */
        @JsonProperty("preprocessing_preset")
        public Builder withPreprocessingPreset(final String value) {
            this.preprocessingPreset = value;
            return this;
        }

        /** Sets the removeNavigation field. */
        @JsonProperty("remove_navigation")
        public Builder withRemoveNavigation(final boolean value) {
            this.removeNavigation = value;
            return this;
        }

        /** Sets the removeForms field. */
        @JsonProperty("remove_forms")
        public Builder withRemoveForms(final boolean value) {
            this.removeForms = value;
            return this;
        }

        /** Sets the stripTags field. */
        @JsonProperty("strip_tags")
        public Builder withStripTags(final @Nullable List<String> value) {
            this.stripTags = value;
            return this;
        }

        /** Sets the preserveTags field. */
        @JsonProperty("preserve_tags")
        public Builder withPreserveTags(final @Nullable List<String> value) {
            this.preserveTags = value;
            return this;
        }

        /** Sets the excludeSelectors field. */
        @JsonProperty("exclude_selectors")
        public Builder withExcludeSelectors(final @Nullable List<String> value) {
            this.excludeSelectors = value;
            return this;
        }

        /** Sets the skipImages field. */
        @JsonProperty("skip_images")
        public Builder withSkipImages(final boolean value) {
            this.skipImages = value;
            return this;
        }

        /** Sets the maxDepth field. */
        @JsonProperty("max_depth")
        public Builder withMaxDepth(final @Nullable long value) {
            this.maxDepth = value;
            return this;
        }

        /** Sets the wrap field. */
        @JsonProperty("wrap")
        public Builder withWrap(final boolean value) {
            this.wrap = value;
            return this;
        }

        /** Sets the wrapWidth field. */
        @JsonProperty("wrap_width")
        public Builder withWrapWidth(final long value) {
            this.wrapWidth = value;
            return this;
        }

        /** Sets the includeDocumentStructure field. */
        @JsonProperty("include_document_structure")
        public Builder withIncludeDocumentStructure(final boolean value) {
            this.includeDocumentStructure = value;
            return this;
        }

        /** Builds the ContentConfig instance. */
        public ContentConfig build() {
            return new ContentConfig(
                outputFormat,
                preprocessingPreset,
                removeNavigation,
                removeForms,
                stripTags,
                preserveTags,
                excludeSelectors,
                skipImages,
                maxDepth,
                wrap,
                wrapWidth,
                includeDocumentStructure
            );
        }
    }
    // CPD-ON
    public static ContentConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
