// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7ff11be8bb8916742ab41c5dcb4f7955cf8a5f075c3a1b00066b48ef913fc5f7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import java.util.Optional;

/**
 * The result of a multi-page crawl operation.
 */
public class CrawlResultBuilder {

	private List<CrawlPageResult> pages = List.of();
	private String finalUrl = "";
	private long redirectCount = 0;
	private boolean wasSkipped = false;
	private Optional<String> error = Optional.empty();
	private List<CookieInfo> cookies = List.of();
	private List<String> normalizedUrls = List.of();

	/** Sets the pages field. */
	public CrawlResultBuilder withPages(final List<CrawlPageResult> value) {
		this.pages = value;
		return this;
	}

	/** Sets the finalUrl field. */
	public CrawlResultBuilder withFinalUrl(final String value) {
		this.finalUrl = value;
		return this;
	}

	/** Sets the redirectCount field. */
	public CrawlResultBuilder withRedirectCount(final long value) {
		this.redirectCount = value;
		return this;
	}

	/** Sets the wasSkipped field. */
	public CrawlResultBuilder withWasSkipped(final boolean value) {
		this.wasSkipped = value;
		return this;
	}

	/** Sets the error field. */
	public CrawlResultBuilder withError(final Optional<String> value) {
		this.error = value;
		return this;
	}

	/** Sets the cookies field. */
	public CrawlResultBuilder withCookies(final List<CookieInfo> value) {
		this.cookies = value;
		return this;
	}

	/** Sets the normalizedUrls field. */
	public CrawlResultBuilder withNormalizedUrls(final List<String> value) {
		this.normalizedUrls = value;
		return this;
	}

	/** Builds the CrawlResult instance. */
	public CrawlResult build() {
		return new CrawlResult(pages, finalUrl, redirectCount, wasSkipped, error, cookies, normalizedUrls);
	}
}
