// DO NOT EDIT - auto-generated by alef
// alef:hash:86fe27b0025198cfc2831ba33343c2204e8b7c49bbae8eb5f850127a99124bfd
package dev.kreuzberg.kreuzcrawl;

/**
 * Errors that can occur during crawling, scraping, or mapping operations.
 */
public class CrawlErrorException extends Exception {
    /** Creates a new CrawlErrorException with the given message. */
    public CrawlErrorException(final String message) {
        super(message);
    }

    /** Creates a new CrawlErrorException with the given message and cause. */
    public CrawlErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
