// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:157e9b496c17495435d30c16de4ce749eb6b55d26769c7876a389ae12fcf44ba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata about an LLM extraction pass.
 */
public record ExtractionMeta(
		/** Estimated cost of the LLM call in USD. */
		Optional<Double> cost,
		/** Number of prompt (input) tokens consumed. */
		@JsonProperty("prompt_tokens") Optional<Long> promptTokens,
		/** Number of completion (output) tokens generated. */
		@JsonProperty("completion_tokens") Optional<Long> completionTokens,
		/** The model identifier used for extraction. */
		Optional<String> model, /** Number of content chunks sent to the LLM. */
		@JsonProperty("chunks_processed") long chunksProcessed) {
	public static ExtractionMetaBuilder builder() {
		return new ExtractionMetaBuilder();
	}
}
