// DO NOT EDIT - auto-generated by alef
// alef:hash:8b715a92d8f7e00abc0f5ad99eb17c63cda2ab5b6932f99af1336aae814ba6df
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was forbidden (HTTP 403).
 */
public class ForbiddenException extends CrawlErrorException {
  /** Creates a new ForbiddenException with the given message. */
  public ForbiddenException(final String message) {
    super(message);
  }

  /** Creates a new ForbiddenException with the given message and cause. */
  public ForbiddenException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
