// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc914c28abe3a106c0a659306be7c739d76eca1afdd9b46838a60ee8f5ed0fb3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * Result of executing a sequence of page interaction actions.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InteractionResult.Builder.class)
public record InteractionResult(
    @JsonProperty("action_results") List<ActionResult> actionResults,
    @JsonProperty("final_html") String finalHtml,
    @JsonProperty("final_url") String finalUrl) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  /** Jackson builder for InteractionResult deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    @JsonProperty("action_results")
    private List<ActionResult> actionResults = List.of();

    @JsonProperty("final_html")
    private String finalHtml;

    @JsonProperty("final_url")
    private String finalUrl;

    /** Sets the actionResults field. */
    @JsonProperty("action_results")
    public Builder withActionResults(final List<ActionResult> value) {
      this.actionResults = value;
      return this;
    }

    /** Sets the finalHtml field. */
    @JsonProperty("final_html")
    public Builder withFinalHtml(final String value) {
      this.finalHtml = value;
      return this;
    }

    /** Sets the finalUrl field. */
    @JsonProperty("final_url")
    public Builder withFinalUrl(final String value) {
      this.finalUrl = value;
      return this;
    }

    /** Constructs a InteractionResult instance from the builder's current state. */
    public InteractionResult build() {
      return new InteractionResult(actionResults, finalHtml, finalUrl);
    }
  }
  // CPD-ON
}
