// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9f527fe9e864e8aebf50f2da46f1aa3d4a30f14fc2fc7f2b7629db2239d93fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends KreuzcrawlRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
