// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23d31ab870eb0cac4479aca89bfda2e39ab76ed038e3c6bc183485227ef1d77d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

/** Exception thrown when input validation fails. */
@SuppressWarnings("checkstyle:LineLength")
public class InvalidInputException extends KreuzcrawlRsException {
  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) {
    super(1, message);
  }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
