// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:84c3728ef08dcd3c1cdac2271822b22503a0f38541fec50b01ec4c6d27882337
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.kreuzcrawl;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
public final class KreuzcrawlRs {
    private KreuzcrawlRs() { }

    public static CrawlEngineHandle createEngine(final CrawlConfig config) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.KCRAWL_CRAWL_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_CREATE_ENGINE.invoke(cconfig);
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.KCRAWL_CRAWL_CONFIG_FREE.invoke(cconfig);
            }
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            return new CrawlEngineHandle(resultPtr);
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static ScrapeResult scrape(final CrawlEngineHandle engine, final String url) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cengine = engine.handle();
            var curl = arena.allocateFrom(url);
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_SCRAPE.invoke(cengine, curl);
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            var jsonPtr = (MemorySegment) NativeLib.KCRAWL_SCRAPE_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.KCRAWL_SCRAPE_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                return null;
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.KCRAWL_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, ScrapeResult.class);
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static CompletableFuture<ScrapeResult> scrapeAsync(final CrawlEngineHandle engine, final String url) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return scrape(engine, url);
            } catch (Throwable e) {
                throw new CompletionException(e);
            }
        });
    }

    public static CrawlResult crawl(final CrawlEngineHandle engine, final String url) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cengine = engine.handle();
            var curl = arena.allocateFrom(url);
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_CRAWL.invoke(cengine, curl);
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            var jsonPtr = (MemorySegment) NativeLib.KCRAWL_CRAWL_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.KCRAWL_CRAWL_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                return null;
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.KCRAWL_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, CrawlResult.class);
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static CompletableFuture<CrawlResult> crawlAsync(final CrawlEngineHandle engine, final String url) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return crawl(engine, url);
            } catch (Throwable e) {
                throw new CompletionException(e);
            }
        });
    }

    public static MapResult mapUrls(final CrawlEngineHandle engine, final String url) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cengine = engine.handle();
            var curl = arena.allocateFrom(url);
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_MAP_URLS.invoke(cengine, curl);
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            var jsonPtr = (MemorySegment) NativeLib.KCRAWL_MAP_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.KCRAWL_MAP_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                return null;
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.KCRAWL_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, MapResult.class);
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static CompletableFuture<MapResult> mapUrlsAsync(final CrawlEngineHandle engine, final String url) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return mapUrls(engine, url);
            } catch (Throwable e) {
                throw new CompletionException(e);
            }
        });
    }

    public static List<BatchScrapeResult> batchScrape(
        final CrawlEngineHandle engine,
        final List<String> urls
    ) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cengine = engine.handle();
            var curlsJson = MAPPER.writeValueAsString(urls);
            var curls = arena.allocateFrom(curlsJson);
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_BATCH_SCRAPE.invoke(cengine, curls);
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<BatchScrapeResult>>() { });
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static CompletableFuture<List<BatchScrapeResult>> batchScrapeAsync(final CrawlEngineHandle engine, final List<String> urls) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return batchScrape(engine, urls);
            } catch (Throwable e) {
                throw new CompletionException(e);
            }
        });
    }

    public static List<BatchCrawlResult> batchCrawl(final CrawlEngineHandle engine, final List<String> urls) throws KreuzcrawlRsException {
        try (var arena = Arena.ofConfined()) {
            var cengine = engine.handle();
            var curlsJson = MAPPER.writeValueAsString(urls);
            var curls = arena.allocateFrom(curlsJson);
            var resultPtr = (MemorySegment) NativeLib.KCRAWL_BATCH_CRAWL.invoke(cengine, curls);
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<BatchCrawlResult>>() { });
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }

    public static CompletableFuture<List<BatchCrawlResult>> batchCrawlAsync(final CrawlEngineHandle engine, final List<String> urls) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return batchCrawl(engine, urls);
            } catch (Throwable e) {
                throw new CompletionException(e);
            }
        });
    }

    // Helper methods for FFI marshalling

    private static void checkLastError() throws Throwable {
        int errCode = (int) NativeLib.KCRAWL_LAST_ERROR_CODE.invoke();
        if (errCode != 0) {
            var ctxPtr = (MemorySegment) NativeLib.KCRAWL_LAST_ERROR_CONTEXT.invoke();
            String msg = ctxPtr.reinterpret(Long.MAX_VALUE).getString(0);
            switch (errCode) {
                case 1 -> throw new InvalidInputException(msg);
                case 2 -> throw new ConversionErrorException(msg);
                default -> throw new KreuzcrawlRsException(errCode, msg);
            }
        }
    }
    private static com.fasterxml.jackson.databind.ObjectMapper createObjectMapper() {
        return new com.fasterxml.jackson.databind.ObjectMapper()
            .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
            .findAndRegisterModules()
            .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
            .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
            .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true);
    }

    private static final com.fasterxml.jackson.databind.ObjectMapper MAPPER = createObjectMapper();
    private static <T> java.util.List<T> readJsonList(
        MemorySegment resultPtr,
        com.fasterxml.jackson.core.type.TypeReference<java.util.List<T>> typeRef
    ) throws KreuzcrawlRsException {
        try {
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                return java.util.List.of();
            }
            String json = resultPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.KCRAWL_FREE_STRING.invoke(resultPtr);
            return MAPPER.readValue(json, typeRef);
        } catch (Throwable e) {
            throw new KreuzcrawlRsException("FFI call failed", e);
        }
    }
}
