// DO NOT EDIT - auto-generated by alef
// alef:hash:ba38af1cb8741e4f3841dd66c2861e4cdd146c375d4b87359f97f44b3a8d2438
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
