// DO NOT EDIT - auto-generated by alef
// alef:hash:a4a7ee13a4704d794ac931a9082c0e65ba8635cbaac284ebcfa47f64add9f65d
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
