// DO NOT EDIT - auto-generated by alef
// alef:hash:13c3b0bae227ebc92916178410867c90c90c7f99b8098d992138fd28a54ae635
package dev.kreuzberg.kreuzcrawl;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
