// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:242eaadf9db6f6fbef20a12c259ef6f879200480a82013d4871832b1bbba8b97
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.kreuzcrawl;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The result of a single-page scrape operation.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ScrapeResultBuilder {

	@JsonProperty("status_code")
	private short statusCode = 0;
	@JsonProperty("content_type")
	private String contentType = "";
	private String html = "";
	@JsonProperty("body_size")
	private long bodySize = 0;
	private PageMetadata metadata = null;
	private List<LinkInfo> links = List.of();
	private List<ImageInfo> images = List.of();
	private List<FeedInfo> feeds = List.of();
	@JsonProperty("json_ld")
	private List<JsonLdEntry> jsonLd = List.of();
	@JsonProperty("is_allowed")
	private boolean isAllowed = false;
	@JsonProperty("crawl_delay")
	private Optional<Long> crawlDelay = Optional.empty();
	@JsonProperty("noindex_detected")
	private boolean noindexDetected = false;
	@JsonProperty("nofollow_detected")
	private boolean nofollowDetected = false;
	@JsonProperty("x_robots_tag")
	private Optional<String> xRobotsTag = Optional.empty();
	@JsonProperty("is_pdf")
	private boolean isPdf = false;
	@JsonProperty("was_skipped")
	private boolean wasSkipped = false;
	@JsonProperty("detected_charset")
	private Optional<String> detectedCharset = Optional.empty();
	@JsonProperty("auth_header_sent")
	private boolean authHeaderSent = false;
	@JsonProperty("response_meta")
	private Optional<ResponseMeta> responseMeta = Optional.empty();
	private List<DownloadedAsset> assets = List.of();
	@JsonProperty("js_render_hint")
	private boolean jsRenderHint = false;
	@JsonProperty("browser_used")
	private boolean browserUsed = false;
	private Optional<MarkdownResult> markdown = Optional.empty();
	@JsonProperty("extracted_data")
	private Optional<Object> extractedData = Optional.empty();
	@JsonProperty("extraction_meta")
	private Optional<ExtractionMeta> extractionMeta = Optional.empty();
	private Optional<byte[]> screenshot = Optional.empty();
	@JsonProperty("downloaded_document")
	private Optional<DownloadedDocument> downloadedDocument = Optional.empty();

	/** Sets the statusCode field. */
	public ScrapeResultBuilder withStatusCode(final short value) {
		this.statusCode = value;
		return this;
	}

	/** Sets the contentType field. */
	public ScrapeResultBuilder withContentType(final String value) {
		this.contentType = value;
		return this;
	}

	/** Sets the html field. */
	public ScrapeResultBuilder withHtml(final String value) {
		this.html = value;
		return this;
	}

	/** Sets the bodySize field. */
	public ScrapeResultBuilder withBodySize(final long value) {
		this.bodySize = value;
		return this;
	}

	/** Sets the metadata field. */
	public ScrapeResultBuilder withMetadata(final PageMetadata value) {
		this.metadata = value;
		return this;
	}

	/** Sets the links field. */
	public ScrapeResultBuilder withLinks(final List<LinkInfo> value) {
		this.links = value;
		return this;
	}

	/** Sets the images field. */
	public ScrapeResultBuilder withImages(final List<ImageInfo> value) {
		this.images = value;
		return this;
	}

	/** Sets the feeds field. */
	public ScrapeResultBuilder withFeeds(final List<FeedInfo> value) {
		this.feeds = value;
		return this;
	}

	/** Sets the jsonLd field. */
	public ScrapeResultBuilder withJsonLd(final List<JsonLdEntry> value) {
		this.jsonLd = value;
		return this;
	}

	/** Sets the isAllowed field. */
	public ScrapeResultBuilder withIsAllowed(final boolean value) {
		this.isAllowed = value;
		return this;
	}

	/** Sets the crawlDelay field. */
	public ScrapeResultBuilder withCrawlDelay(final Optional<Long> value) {
		this.crawlDelay = value;
		return this;
	}

	/** Sets the noindexDetected field. */
	public ScrapeResultBuilder withNoindexDetected(final boolean value) {
		this.noindexDetected = value;
		return this;
	}

	/** Sets the nofollowDetected field. */
	public ScrapeResultBuilder withNofollowDetected(final boolean value) {
		this.nofollowDetected = value;
		return this;
	}

	/** Sets the xRobotsTag field. */
	public ScrapeResultBuilder withXRobotsTag(final Optional<String> value) {
		this.xRobotsTag = value;
		return this;
	}

	/** Sets the isPdf field. */
	public ScrapeResultBuilder withIsPdf(final boolean value) {
		this.isPdf = value;
		return this;
	}

	/** Sets the wasSkipped field. */
	public ScrapeResultBuilder withWasSkipped(final boolean value) {
		this.wasSkipped = value;
		return this;
	}

	/** Sets the detectedCharset field. */
	public ScrapeResultBuilder withDetectedCharset(final Optional<String> value) {
		this.detectedCharset = value;
		return this;
	}

	/** Sets the authHeaderSent field. */
	public ScrapeResultBuilder withAuthHeaderSent(final boolean value) {
		this.authHeaderSent = value;
		return this;
	}

	/** Sets the responseMeta field. */
	public ScrapeResultBuilder withResponseMeta(final Optional<ResponseMeta> value) {
		this.responseMeta = value;
		return this;
	}

	/** Sets the assets field. */
	public ScrapeResultBuilder withAssets(final List<DownloadedAsset> value) {
		this.assets = value;
		return this;
	}

	/** Sets the jsRenderHint field. */
	public ScrapeResultBuilder withJsRenderHint(final boolean value) {
		this.jsRenderHint = value;
		return this;
	}

	/** Sets the browserUsed field. */
	public ScrapeResultBuilder withBrowserUsed(final boolean value) {
		this.browserUsed = value;
		return this;
	}

	/** Sets the markdown field. */
	public ScrapeResultBuilder withMarkdown(final Optional<MarkdownResult> value) {
		this.markdown = value;
		return this;
	}

	/** Sets the extractedData field. */
	public ScrapeResultBuilder withExtractedData(final Optional<Object> value) {
		this.extractedData = value;
		return this;
	}

	/** Sets the extractionMeta field. */
	public ScrapeResultBuilder withExtractionMeta(final Optional<ExtractionMeta> value) {
		this.extractionMeta = value;
		return this;
	}

	/** Sets the screenshot field. */
	public ScrapeResultBuilder withScreenshot(final Optional<byte[]> value) {
		this.screenshot = value;
		return this;
	}

	/** Sets the downloadedDocument field. */
	public ScrapeResultBuilder withDownloadedDocument(final Optional<DownloadedDocument> value) {
		this.downloadedDocument = value;
		return this;
	}

	/** Builds the ScrapeResult instance. */
	public ScrapeResult build() {
		return new ScrapeResult(statusCode, contentType, html, bodySize, metadata, links, images, feeds, jsonLd,
				isAllowed, crawlDelay.orElse(null), noindexDetected, nofollowDetected, xRobotsTag.orElse(null), isPdf,
				wasSkipped, detectedCharset.orElse(null), authHeaderSent, responseMeta.orElse(null), assets,
				jsRenderHint, browserUsed, markdown.orElse(null), extractedData.orElse(null),
				extractionMeta.orElse(null), screenshot.orElse(null), downloadedDocument.orElse(null));
	}
}
