// DO NOT EDIT - auto-generated by alef
// alef:hash:0252fa87915ae9a1608199bdd0eaca84849af234f3be0d85bd246b077c2847e4
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
    /** Creates a new ServerErrorException with the given message. */
    public ServerErrorException(final String message) {
        super(message);
    }

    /** Creates a new ServerErrorException with the given message and cause. */
    public ServerErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
