// DO NOT EDIT - auto-generated by alef
// alef:hash:8eae86c36839b50d908ee9293bb951de8f2586fa943ded8ef7529c875438c31a
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
    /** Creates a new ServerErrorException with the given message. */
    public ServerErrorException(final String message) {
        super(message);
    }

    /** Creates a new ServerErrorException with the given message and cause. */
    public ServerErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
