// DO NOT EDIT - auto-generated by alef
// alef:hash:7d1e18e5dc8e403750c0732534a7bd3739707ca6d08a80e31947af72cacb578d
package dev.kreuzberg.kreuzcrawl;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
    /** Creates a new ServerErrorException with the given message. */
    public ServerErrorException(final String message) {
        super(message);
    }

    /** Creates a new ServerErrorException with the given message and cause. */
    public ServerErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
