// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4a7ee13a4704d794ac931a9082c0e65ba8635cbaac284ebcfa47f64add9f65d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A URL entry from a sitemap.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SitemapUrl.Builder.class)
public record SitemapUrl(
    /**
     * The URL.
     */
    @JsonProperty("url") String url,
    /**
     * The last modification date, if present.
     */
    @Nullable @JsonProperty("lastmod") String lastmod,
    /**
     * The change frequency, if present.
     */
    @Nullable @JsonProperty("changefreq") String changefreq,
    /**
     * The priority, if present.
     */
    @Nullable @JsonProperty("priority") String priority
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String url = "";
private String lastmod = null;
private String changefreq = null;
private String priority = null;

        /** Sets the url field. */
        @JsonProperty("url")
        public Builder withUrl(final String value) {
            this.url = value;
            return this;
        }

        /** Sets the lastmod field. */
        @JsonProperty("lastmod")
        public Builder withLastmod(final @Nullable String value) {
            this.lastmod = value;
            return this;
        }

        /** Sets the changefreq field. */
        @JsonProperty("changefreq")
        public Builder withChangefreq(final @Nullable String value) {
            this.changefreq = value;
            return this;
        }

        /** Sets the priority field. */
        @JsonProperty("priority")
        public Builder withPriority(final @Nullable String value) {
            this.priority = value;
            return this;
        }

        /** Builds the SitemapUrl instance. */
        public SitemapUrl build() {
            return new SitemapUrl(
                url,
                lastmod,
                changefreq,
                priority
            );
        }
    }
    // CPD-ON
}
