// DO NOT EDIT - auto-generated by alef
// alef:hash:0ba927fedb193da697a0c28a4daac1722416be2cd8934e54222921ac9084b0c3
package dev.kreuzberg.kreuzcrawl;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
