// DO NOT EDIT - auto-generated by alef
// alef:hash:fc914c28abe3a106c0a659306be7c739d76eca1afdd9b46838a60ee8f5ed0fb3
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnauthorizedException with the given message. */
  public UnauthorizedException(final String message) {
    super(message);
  }

  /** Creates a new UnauthorizedException with the given message and cause. */
  public UnauthorizedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
