// DO NOT EDIT - auto-generated by alef
// alef:hash:1dae80dec968fb99d1b7b43dfca11bb89983c23bba3fd199d417e01a76145f00
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnauthorizedException with the given message. */
  public UnauthorizedException(final String message) {
    super(message);
  }

  /** Creates a new UnauthorizedException with the given message and cause. */
  public UnauthorizedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
