// DO NOT EDIT - auto-generated by alef
// alef:hash:dfcd400ebcbd70fe59d894a4deb2d9c6d54b101986adcb05b753fa1bac517a4f
package dev.kreuzberg.kreuzcrawl;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
    /** Creates a new UnsupportedException with the given message. */
    public UnsupportedException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedException with the given message and cause. */
    public UnsupportedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
