// DO NOT EDIT - auto-generated by alef
// alef:hash:947a0eb405eb19814a1855da9e0c9f63bd53b260875bfe706b270d0df095eb3b
package dev.kreuzberg.kreuzcrawl;

/**
 * The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
 */
public class WafBlockedException extends CrawlErrorException {
    /** Creates a new WafBlockedException with the given message. */
    public WafBlockedException(final String message) {
        super(message);
    }

    /** Creates a new WafBlockedException with the given message and cause. */
    public WafBlockedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
