// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb0e8866906d064363d33b84f75db75d497d64e12fc395ba7b5a174804b3918a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    globalSetup: "./globalSetup.ts",
  },
});
