// Generated by alef. Do not edit by hand.
// alef:hash:cc01a1c094d3c52a5b52b4a912620f9a716410d5ef08dea3520ea2a80cd328ad
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/**
 * Aggregate result of a batch crawl, exposing per-URL results plus precomputed counts.
 *
 * The counts are derived once at construction so every binding language can read them as plain
 * integer fields without re-iterating the `results` vector.
 */
data class BatchCrawlResults(
    /** Per-URL crawl results, in the order seed URLs were submitted. */
    val results: List<BatchCrawlResult> = emptyList(),
    /** Total number of seed URLs in the batch (equal to `results.len()`). */
    val totalCount: Long = 0L,
    /** Number of seed URLs whose crawl succeeded (`error` is `null`). */
    val completedCount: Long = 0L,
    /** Number of seed URLs whose crawl failed (`error` is `Some`). */
    val failedCount: Long = 0L,
)
