// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Create a new crawl engine with the given configuration.
///
/// If `config` is `null`, uses `CrawlConfig.default()`.
/// Returns an error if the configuration is invalid.
Future<CrawlEngineHandle> createEngine({CrawlConfig? config}) =>
    RustLib.instance.api.crateCreateEngine(config: config);

/// Scrape a single URL, returning extracted page data.
Future<ScrapeResult> scrape(
        {required CrawlEngineHandle engine, required String url}) =>
    RustLib.instance.api.crateScrape(engine: engine, url: url);

/// Crawl a website starting from `url`, following links up to the configured depth.
Future<CrawlResult> crawl(
        {required CrawlEngineHandle engine, required String url}) =>
    RustLib.instance.api.crateCrawl(engine: engine, url: url);

/// Discover all pages on a website by following links and sitemaps.
Future<MapResult> mapUrls(
        {required CrawlEngineHandle engine, required String url}) =>
    RustLib.instance.api.crateMapUrls(engine: engine, url: url);

/// Scrape multiple URLs concurrently.
Future<List<BatchScrapeResult>> batchScrape(
        {required CrawlEngineHandle engine, required List<String> urls}) =>
    RustLib.instance.api.crateBatchScrape(engine: engine, urls: urls);

/// Crawl multiple seed URLs concurrently, each following links to configured depth.
Future<List<BatchCrawlResult>> batchCrawl(
        {required CrawlEngineHandle engine, required List<String> urls}) =>
    RustLib.instance.api.crateBatchCrawl(engine: engine, urls: urls);

Future<ExtractionMeta> createExtractionMetaFromJson({required String json}) =>
    RustLib.instance.api.crateCreateExtractionMetaFromJson(json: json);

Future<ProxyConfig> createProxyConfigFromJson({required String json}) =>
    RustLib.instance.api.crateCreateProxyConfigFromJson(json: json);

Future<ContentConfig> createContentConfigFromJson({required String json}) =>
    RustLib.instance.api.crateCreateContentConfigFromJson(json: json);

Future<BrowserConfig> createBrowserConfigFromJson({required String json}) =>
    RustLib.instance.api.crateCreateBrowserConfigFromJson(json: json);

Future<CrawlConfig> createCrawlConfigFromJson({required String json}) =>
    RustLib.instance.api.crateCreateCrawlConfigFromJson(json: json);

Future<DownloadedDocument> createDownloadedDocumentFromJson(
        {required String json}) =>
    RustLib.instance.api.crateCreateDownloadedDocumentFromJson(json: json);

Future<ScrapeResult> createScrapeResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateScrapeResultFromJson(json: json);

Future<CrawlPageResult> createCrawlPageResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateCrawlPageResultFromJson(json: json);

Future<CrawlResult> createCrawlResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateCrawlResultFromJson(json: json);

Future<SitemapUrl> createSitemapUrlFromJson({required String json}) =>
    RustLib.instance.api.crateCreateSitemapUrlFromJson(json: json);

Future<MapResult> createMapResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateMapResultFromJson(json: json);

Future<MarkdownResult> createMarkdownResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateMarkdownResultFromJson(json: json);

Future<LinkInfo> createLinkInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateLinkInfoFromJson(json: json);

Future<ImageInfo> createImageInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateImageInfoFromJson(json: json);

Future<FeedInfo> createFeedInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateFeedInfoFromJson(json: json);

Future<JsonLdEntry> createJsonLdEntryFromJson({required String json}) =>
    RustLib.instance.api.crateCreateJsonLdEntryFromJson(json: json);

Future<CookieInfo> createCookieInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateCookieInfoFromJson(json: json);

Future<DownloadedAsset> createDownloadedAssetFromJson({required String json}) =>
    RustLib.instance.api.crateCreateDownloadedAssetFromJson(json: json);

Future<ArticleMetadata> createArticleMetadataFromJson({required String json}) =>
    RustLib.instance.api.crateCreateArticleMetadataFromJson(json: json);

Future<HreflangEntry> createHreflangEntryFromJson({required String json}) =>
    RustLib.instance.api.crateCreateHreflangEntryFromJson(json: json);

Future<FaviconInfo> createFaviconInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateFaviconInfoFromJson(json: json);

Future<HeadingInfo> createHeadingInfoFromJson({required String json}) =>
    RustLib.instance.api.crateCreateHeadingInfoFromJson(json: json);

Future<ResponseMeta> createResponseMetaFromJson({required String json}) =>
    RustLib.instance.api.crateCreateResponseMetaFromJson(json: json);

Future<PageMetadata> createPageMetadataFromJson({required String json}) =>
    RustLib.instance.api.crateCreatePageMetadataFromJson(json: json);

Future<CitationResult> createCitationResultFromJson({required String json}) =>
    RustLib.instance.api.crateCreateCitationResultFromJson(json: json);

Future<CitationReference> createCitationReferenceFromJson(
        {required String json}) =>
    RustLib.instance.api.crateCreateCitationReferenceFromJson(json: json);

Future<BatchScrapeResult> createBatchScrapeResultFromJson(
        {required String json}) =>
    RustLib.instance.api.crateCreateBatchScrapeResultFromJson(json: json);

Future<BatchCrawlResult> createBatchCrawlResultFromJson(
        {required String json}) =>
    RustLib.instance.api.crateCreateBatchCrawlResultFromJson(json: json);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CrawlEngineHandle>>
abstract class CrawlEngineHandle implements RustOpaqueInterface {}

class ArticleMetadata {
  final String? publishedTime;
  final String? modifiedTime;
  final String? author;
  final String? section;
  final List<String> tags;

  const ArticleMetadata({
    this.publishedTime,
    this.modifiedTime,
    this.author,
    this.section,
    required this.tags,
  });

  @override
  int get hashCode =>
      publishedTime.hashCode ^
      modifiedTime.hashCode ^
      author.hashCode ^
      section.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArticleMetadata &&
          runtimeType == other.runtimeType &&
          publishedTime == other.publishedTime &&
          modifiedTime == other.modifiedTime &&
          author == other.author &&
          section == other.section &&
          tags == other.tags;
}

enum AssetCategory {
  document,
  image,
  audio,
  video,
  font,
  stylesheet,
  script,
  archive,
  data,
  other,
  ;
}

@freezed
sealed class AuthConfig with _$AuthConfig {
  const AuthConfig._();

  const factory AuthConfig.basic({
    required String username,
    required String password,
  }) = AuthConfig_Basic;
  const factory AuthConfig.bearer({
    required String token,
  }) = AuthConfig_Bearer;
  const factory AuthConfig.header({
    required String name,
    required String value,
  }) = AuthConfig_Header;
}

class BatchCrawlResult {
  final String url;
  final CrawlResult? result;
  final String? error;

  const BatchCrawlResult({
    required this.url,
    this.result,
    this.error,
  });

  @override
  int get hashCode => url.hashCode ^ result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchCrawlResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          result == other.result &&
          error == other.error;
}

class BatchScrapeResult {
  final String url;
  final ScrapeResult? result;
  final String? error;

  const BatchScrapeResult({
    required this.url,
    this.result,
    this.error,
  });

  @override
  int get hashCode => url.hashCode ^ result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchScrapeResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          result == other.result &&
          error == other.error;
}

class BrowserConfig {
  final BrowserMode mode;
  final String? endpoint;
  final PlatformInt64 timeout;
  final BrowserWait wait;
  final String? waitSelector;
  final PlatformInt64? extraWait;

  const BrowserConfig({
    required this.mode,
    this.endpoint,
    required this.timeout,
    required this.wait,
    this.waitSelector,
    this.extraWait,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      endpoint.hashCode ^
      timeout.hashCode ^
      wait.hashCode ^
      waitSelector.hashCode ^
      extraWait.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BrowserConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          endpoint == other.endpoint &&
          timeout == other.timeout &&
          wait == other.wait &&
          waitSelector == other.waitSelector &&
          extraWait == other.extraWait;
}

enum BrowserMode {
  auto,
  always,
  never,
  ;
}

enum BrowserWait {
  networkIdle,
  selector,
  fixed,
  ;
}

class CitationReference {
  final PlatformInt64 index;
  final String url;
  final String text;

  const CitationReference({
    required this.index,
    required this.url,
    required this.text,
  });

  @override
  int get hashCode => index.hashCode ^ url.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CitationReference &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          url == other.url &&
          text == other.text;
}

class CitationResult {
  final String content;
  final List<CitationReference> references;

  const CitationResult({
    required this.content,
    required this.references,
  });

  @override
  int get hashCode => content.hashCode ^ references.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CitationResult &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          references == other.references;
}

class ContentConfig {
  final String outputFormat;
  final String preprocessingPreset;
  final bool removeNavigation;
  final bool removeForms;
  final List<String> stripTags;
  final List<String> preserveTags;
  final List<String> excludeSelectors;
  final bool skipImages;
  final PlatformInt64? maxDepth;
  final bool wrap;
  final PlatformInt64 wrapWidth;
  final bool includeDocumentStructure;

  const ContentConfig({
    required this.outputFormat,
    required this.preprocessingPreset,
    required this.removeNavigation,
    required this.removeForms,
    required this.stripTags,
    required this.preserveTags,
    required this.excludeSelectors,
    required this.skipImages,
    this.maxDepth,
    required this.wrap,
    required this.wrapWidth,
    required this.includeDocumentStructure,
  });

  @override
  int get hashCode =>
      outputFormat.hashCode ^
      preprocessingPreset.hashCode ^
      removeNavigation.hashCode ^
      removeForms.hashCode ^
      stripTags.hashCode ^
      preserveTags.hashCode ^
      excludeSelectors.hashCode ^
      skipImages.hashCode ^
      maxDepth.hashCode ^
      wrap.hashCode ^
      wrapWidth.hashCode ^
      includeDocumentStructure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentConfig &&
          runtimeType == other.runtimeType &&
          outputFormat == other.outputFormat &&
          preprocessingPreset == other.preprocessingPreset &&
          removeNavigation == other.removeNavigation &&
          removeForms == other.removeForms &&
          stripTags == other.stripTags &&
          preserveTags == other.preserveTags &&
          excludeSelectors == other.excludeSelectors &&
          skipImages == other.skipImages &&
          maxDepth == other.maxDepth &&
          wrap == other.wrap &&
          wrapWidth == other.wrapWidth &&
          includeDocumentStructure == other.includeDocumentStructure;
}

class CookieInfo {
  final String name;
  final String value;
  final String? domain;
  final String? path;

  const CookieInfo({
    required this.name,
    required this.value,
    this.domain,
    this.path,
  });

  @override
  int get hashCode =>
      name.hashCode ^ value.hashCode ^ domain.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CookieInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value &&
          domain == other.domain &&
          path == other.path;
}

class CrawlConfig {
  final PlatformInt64? maxDepth;
  final PlatformInt64? maxPages;
  final PlatformInt64? maxConcurrent;
  final bool respectRobotsTxt;
  final bool softHttpErrors;
  final String? userAgent;
  final bool stayOnDomain;
  final bool allowSubdomains;
  final List<String> includePaths;
  final List<String> excludePaths;
  final Map<String, String> customHeaders;
  final PlatformInt64 requestTimeout;
  final PlatformInt64? rateLimitMs;
  final PlatformInt64 maxRedirects;
  final PlatformInt64 retryCount;
  final Int64List retryCodes;
  final bool cookiesEnabled;
  final AuthConfig? auth;
  final PlatformInt64? maxBodySize;
  final List<String> removeTags;
  final ContentConfig content;
  final PlatformInt64? mapLimit;
  final String? mapSearch;
  final bool downloadAssets;
  final List<AssetCategory> assetTypes;
  final PlatformInt64? maxAssetSize;
  final BrowserConfig browser;
  final ProxyConfig? proxy;
  final List<String> userAgents;
  final bool captureScreenshot;
  final bool downloadDocuments;
  final PlatformInt64? documentMaxSize;
  final List<String> documentMimeTypes;
  final String? warcOutput;
  final String? browserProfile;
  final bool saveBrowserProfile;

  const CrawlConfig({
    this.maxDepth,
    this.maxPages,
    this.maxConcurrent,
    required this.respectRobotsTxt,
    required this.softHttpErrors,
    this.userAgent,
    required this.stayOnDomain,
    required this.allowSubdomains,
    required this.includePaths,
    required this.excludePaths,
    required this.customHeaders,
    required this.requestTimeout,
    this.rateLimitMs,
    required this.maxRedirects,
    required this.retryCount,
    required this.retryCodes,
    required this.cookiesEnabled,
    this.auth,
    this.maxBodySize,
    required this.removeTags,
    required this.content,
    this.mapLimit,
    this.mapSearch,
    required this.downloadAssets,
    required this.assetTypes,
    this.maxAssetSize,
    required this.browser,
    this.proxy,
    required this.userAgents,
    required this.captureScreenshot,
    required this.downloadDocuments,
    this.documentMaxSize,
    required this.documentMimeTypes,
    this.warcOutput,
    this.browserProfile,
    required this.saveBrowserProfile,
  });

  @override
  int get hashCode =>
      maxDepth.hashCode ^
      maxPages.hashCode ^
      maxConcurrent.hashCode ^
      respectRobotsTxt.hashCode ^
      softHttpErrors.hashCode ^
      userAgent.hashCode ^
      stayOnDomain.hashCode ^
      allowSubdomains.hashCode ^
      includePaths.hashCode ^
      excludePaths.hashCode ^
      customHeaders.hashCode ^
      requestTimeout.hashCode ^
      rateLimitMs.hashCode ^
      maxRedirects.hashCode ^
      retryCount.hashCode ^
      retryCodes.hashCode ^
      cookiesEnabled.hashCode ^
      auth.hashCode ^
      maxBodySize.hashCode ^
      removeTags.hashCode ^
      content.hashCode ^
      mapLimit.hashCode ^
      mapSearch.hashCode ^
      downloadAssets.hashCode ^
      assetTypes.hashCode ^
      maxAssetSize.hashCode ^
      browser.hashCode ^
      proxy.hashCode ^
      userAgents.hashCode ^
      captureScreenshot.hashCode ^
      downloadDocuments.hashCode ^
      documentMaxSize.hashCode ^
      documentMimeTypes.hashCode ^
      warcOutput.hashCode ^
      browserProfile.hashCode ^
      saveBrowserProfile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrawlConfig &&
          runtimeType == other.runtimeType &&
          maxDepth == other.maxDepth &&
          maxPages == other.maxPages &&
          maxConcurrent == other.maxConcurrent &&
          respectRobotsTxt == other.respectRobotsTxt &&
          softHttpErrors == other.softHttpErrors &&
          userAgent == other.userAgent &&
          stayOnDomain == other.stayOnDomain &&
          allowSubdomains == other.allowSubdomains &&
          includePaths == other.includePaths &&
          excludePaths == other.excludePaths &&
          customHeaders == other.customHeaders &&
          requestTimeout == other.requestTimeout &&
          rateLimitMs == other.rateLimitMs &&
          maxRedirects == other.maxRedirects &&
          retryCount == other.retryCount &&
          retryCodes == other.retryCodes &&
          cookiesEnabled == other.cookiesEnabled &&
          auth == other.auth &&
          maxBodySize == other.maxBodySize &&
          removeTags == other.removeTags &&
          content == other.content &&
          mapLimit == other.mapLimit &&
          mapSearch == other.mapSearch &&
          downloadAssets == other.downloadAssets &&
          assetTypes == other.assetTypes &&
          maxAssetSize == other.maxAssetSize &&
          browser == other.browser &&
          proxy == other.proxy &&
          userAgents == other.userAgents &&
          captureScreenshot == other.captureScreenshot &&
          downloadDocuments == other.downloadDocuments &&
          documentMaxSize == other.documentMaxSize &&
          documentMimeTypes == other.documentMimeTypes &&
          warcOutput == other.warcOutput &&
          browserProfile == other.browserProfile &&
          saveBrowserProfile == other.saveBrowserProfile;
}

class CrawlPageResult {
  final String url;
  final String normalizedUrl;
  final PlatformInt64 statusCode;
  final String contentType;
  final String html;
  final PlatformInt64 bodySize;
  final PageMetadata metadata;
  final List<LinkInfo> links;
  final List<ImageInfo> images;
  final List<FeedInfo> feeds;
  final List<JsonLdEntry> jsonLd;
  final PlatformInt64 depth;
  final bool stayedOnDomain;
  final bool wasSkipped;
  final bool isPdf;
  final String? detectedCharset;
  final MarkdownResult? markdown;
  final String? extractedData;
  final ExtractionMeta? extractionMeta;
  final DownloadedDocument? downloadedDocument;

  const CrawlPageResult({
    required this.url,
    required this.normalizedUrl,
    required this.statusCode,
    required this.contentType,
    required this.html,
    required this.bodySize,
    required this.metadata,
    required this.links,
    required this.images,
    required this.feeds,
    required this.jsonLd,
    required this.depth,
    required this.stayedOnDomain,
    required this.wasSkipped,
    required this.isPdf,
    this.detectedCharset,
    this.markdown,
    this.extractedData,
    this.extractionMeta,
    this.downloadedDocument,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      normalizedUrl.hashCode ^
      statusCode.hashCode ^
      contentType.hashCode ^
      html.hashCode ^
      bodySize.hashCode ^
      metadata.hashCode ^
      links.hashCode ^
      images.hashCode ^
      feeds.hashCode ^
      jsonLd.hashCode ^
      depth.hashCode ^
      stayedOnDomain.hashCode ^
      wasSkipped.hashCode ^
      isPdf.hashCode ^
      detectedCharset.hashCode ^
      markdown.hashCode ^
      extractedData.hashCode ^
      extractionMeta.hashCode ^
      downloadedDocument.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrawlPageResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          normalizedUrl == other.normalizedUrl &&
          statusCode == other.statusCode &&
          contentType == other.contentType &&
          html == other.html &&
          bodySize == other.bodySize &&
          metadata == other.metadata &&
          links == other.links &&
          images == other.images &&
          feeds == other.feeds &&
          jsonLd == other.jsonLd &&
          depth == other.depth &&
          stayedOnDomain == other.stayedOnDomain &&
          wasSkipped == other.wasSkipped &&
          isPdf == other.isPdf &&
          detectedCharset == other.detectedCharset &&
          markdown == other.markdown &&
          extractedData == other.extractedData &&
          extractionMeta == other.extractionMeta &&
          downloadedDocument == other.downloadedDocument;
}

class CrawlResult {
  final List<CrawlPageResult> pages;
  final String finalUrl;
  final PlatformInt64 redirectCount;
  final bool wasSkipped;
  final String? error;
  final List<CookieInfo> cookies;
  final List<String> normalizedUrls;

  const CrawlResult({
    required this.pages,
    required this.finalUrl,
    required this.redirectCount,
    required this.wasSkipped,
    this.error,
    required this.cookies,
    required this.normalizedUrls,
  });

  @override
  int get hashCode =>
      pages.hashCode ^
      finalUrl.hashCode ^
      redirectCount.hashCode ^
      wasSkipped.hashCode ^
      error.hashCode ^
      cookies.hashCode ^
      normalizedUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrawlResult &&
          runtimeType == other.runtimeType &&
          pages == other.pages &&
          finalUrl == other.finalUrl &&
          redirectCount == other.redirectCount &&
          wasSkipped == other.wasSkipped &&
          error == other.error &&
          cookies == other.cookies &&
          normalizedUrls == other.normalizedUrls;
}

class DownloadedAsset {
  final String url;
  final String contentHash;
  final String? mimeType;
  final PlatformInt64 size;
  final AssetCategory assetCategory;
  final String? htmlTag;

  const DownloadedAsset({
    required this.url,
    required this.contentHash,
    this.mimeType,
    required this.size,
    required this.assetCategory,
    this.htmlTag,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      contentHash.hashCode ^
      mimeType.hashCode ^
      size.hashCode ^
      assetCategory.hashCode ^
      htmlTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedAsset &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          contentHash == other.contentHash &&
          mimeType == other.mimeType &&
          size == other.size &&
          assetCategory == other.assetCategory &&
          htmlTag == other.htmlTag;
}

class DownloadedDocument {
  final String url;
  final String mimeType;
  final PlatformInt64 size;
  final String? filename;
  final String contentHash;
  final Map<String, String> headers;

  const DownloadedDocument({
    required this.url,
    required this.mimeType,
    required this.size,
    this.filename,
    required this.contentHash,
    required this.headers,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      mimeType.hashCode ^
      size.hashCode ^
      filename.hashCode ^
      contentHash.hashCode ^
      headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedDocument &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          mimeType == other.mimeType &&
          size == other.size &&
          filename == other.filename &&
          contentHash == other.contentHash &&
          headers == other.headers;
}

class ExtractionMeta {
  final double? cost;
  final PlatformInt64? promptTokens;
  final PlatformInt64? completionTokens;
  final String? model;
  final PlatformInt64 chunksProcessed;

  const ExtractionMeta({
    this.cost,
    this.promptTokens,
    this.completionTokens,
    this.model,
    required this.chunksProcessed,
  });

  @override
  int get hashCode =>
      cost.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      model.hashCode ^
      chunksProcessed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionMeta &&
          runtimeType == other.runtimeType &&
          cost == other.cost &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          model == other.model &&
          chunksProcessed == other.chunksProcessed;
}

class FaviconInfo {
  final String url;
  final String rel;
  final String? sizes;
  final String? mimeType;

  const FaviconInfo({
    required this.url,
    required this.rel,
    this.sizes,
    this.mimeType,
  });

  @override
  int get hashCode =>
      url.hashCode ^ rel.hashCode ^ sizes.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FaviconInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          rel == other.rel &&
          sizes == other.sizes &&
          mimeType == other.mimeType;
}

class FeedInfo {
  final String url;
  final String? title;
  final FeedType feedType;

  const FeedInfo({
    required this.url,
    this.title,
    required this.feedType,
  });

  @override
  int get hashCode => url.hashCode ^ title.hashCode ^ feedType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          feedType == other.feedType;
}

enum FeedType {
  rss,
  atom,
  jsonFeed,
  ;
}

class HeadingInfo {
  final PlatformInt64 level;
  final String text;

  const HeadingInfo({
    required this.level,
    required this.text,
  });

  @override
  int get hashCode => level.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadingInfo &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          text == other.text;
}

class HreflangEntry {
  final String lang;
  final String url;

  const HreflangEntry({
    required this.lang,
    required this.url,
  });

  @override
  int get hashCode => lang.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HreflangEntry &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          url == other.url;
}

class ImageInfo {
  final String url;
  final String? alt;
  final PlatformInt64? width;
  final PlatformInt64? height;
  final ImageSource source;

  const ImageInfo({
    required this.url,
    this.alt,
    this.width,
    this.height,
    required this.source,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      alt.hashCode ^
      width.hashCode ^
      height.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          alt == other.alt &&
          width == other.width &&
          height == other.height &&
          source == other.source;
}

enum ImageSource {
  img,
  pictureSource,
  ogImage,
  twitterImage,
  ;
}

class JsonLdEntry {
  final String schemaType;
  final String? name;
  final String raw;

  const JsonLdEntry({
    required this.schemaType,
    this.name,
    required this.raw,
  });

  @override
  int get hashCode => schemaType.hashCode ^ name.hashCode ^ raw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsonLdEntry &&
          runtimeType == other.runtimeType &&
          schemaType == other.schemaType &&
          name == other.name &&
          raw == other.raw;
}

class LinkInfo {
  final String url;
  final String text;
  final LinkType linkType;
  final String? rel;
  final bool nofollow;

  const LinkInfo({
    required this.url,
    required this.text,
    required this.linkType,
    this.rel,
    required this.nofollow,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      text.hashCode ^
      linkType.hashCode ^
      rel.hashCode ^
      nofollow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          text == other.text &&
          linkType == other.linkType &&
          rel == other.rel &&
          nofollow == other.nofollow;
}

enum LinkType {
  internal,
  external_,
  anchor,
  document,
  ;
}

class MapResult {
  final List<SitemapUrl> urls;

  const MapResult({
    required this.urls,
  });

  @override
  int get hashCode => urls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapResult &&
          runtimeType == other.runtimeType &&
          urls == other.urls;
}

class MarkdownResult {
  final String content;
  final String? documentStructure;
  final List<String> tables;
  final List<String> warnings;
  final CitationResult? citations;
  final String? fitContent;

  const MarkdownResult({
    required this.content,
    this.documentStructure,
    required this.tables,
    required this.warnings,
    this.citations,
    this.fitContent,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      documentStructure.hashCode ^
      tables.hashCode ^
      warnings.hashCode ^
      citations.hashCode ^
      fitContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkdownResult &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          documentStructure == other.documentStructure &&
          tables == other.tables &&
          warnings == other.warnings &&
          citations == other.citations &&
          fitContent == other.fitContent;
}

class PageMetadata {
  final String? title;
  final String? description;
  final String? canonicalUrl;
  final String? keywords;
  final String? author;
  final String? viewport;
  final String? themeColor;
  final String? generator;
  final String? robots;
  final String? htmlLang;
  final String? htmlDir;
  final String? ogTitle;
  final String? ogType;
  final String? ogImage;
  final String? ogDescription;
  final String? ogUrl;
  final String? ogSiteName;
  final String? ogLocale;
  final String? ogVideo;
  final String? ogAudio;
  final List<String>? ogLocaleAlternates;
  final String? twitterCard;
  final String? twitterTitle;
  final String? twitterDescription;
  final String? twitterImage;
  final String? twitterSite;
  final String? twitterCreator;
  final String? dcTitle;
  final String? dcCreator;
  final String? dcSubject;
  final String? dcDescription;
  final String? dcPublisher;
  final String? dcDate;
  final String? dcType;
  final String? dcFormat;
  final String? dcIdentifier;
  final String? dcLanguage;
  final String? dcRights;
  final ArticleMetadata? article;
  final List<HreflangEntry>? hreflangs;
  final List<FaviconInfo>? favicons;
  final List<HeadingInfo>? headings;
  final PlatformInt64? wordCount;

  const PageMetadata({
    this.title,
    this.description,
    this.canonicalUrl,
    this.keywords,
    this.author,
    this.viewport,
    this.themeColor,
    this.generator,
    this.robots,
    this.htmlLang,
    this.htmlDir,
    this.ogTitle,
    this.ogType,
    this.ogImage,
    this.ogDescription,
    this.ogUrl,
    this.ogSiteName,
    this.ogLocale,
    this.ogVideo,
    this.ogAudio,
    this.ogLocaleAlternates,
    this.twitterCard,
    this.twitterTitle,
    this.twitterDescription,
    this.twitterImage,
    this.twitterSite,
    this.twitterCreator,
    this.dcTitle,
    this.dcCreator,
    this.dcSubject,
    this.dcDescription,
    this.dcPublisher,
    this.dcDate,
    this.dcType,
    this.dcFormat,
    this.dcIdentifier,
    this.dcLanguage,
    this.dcRights,
    this.article,
    this.hreflangs,
    this.favicons,
    this.headings,
    this.wordCount,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      canonicalUrl.hashCode ^
      keywords.hashCode ^
      author.hashCode ^
      viewport.hashCode ^
      themeColor.hashCode ^
      generator.hashCode ^
      robots.hashCode ^
      htmlLang.hashCode ^
      htmlDir.hashCode ^
      ogTitle.hashCode ^
      ogType.hashCode ^
      ogImage.hashCode ^
      ogDescription.hashCode ^
      ogUrl.hashCode ^
      ogSiteName.hashCode ^
      ogLocale.hashCode ^
      ogVideo.hashCode ^
      ogAudio.hashCode ^
      ogLocaleAlternates.hashCode ^
      twitterCard.hashCode ^
      twitterTitle.hashCode ^
      twitterDescription.hashCode ^
      twitterImage.hashCode ^
      twitterSite.hashCode ^
      twitterCreator.hashCode ^
      dcTitle.hashCode ^
      dcCreator.hashCode ^
      dcSubject.hashCode ^
      dcDescription.hashCode ^
      dcPublisher.hashCode ^
      dcDate.hashCode ^
      dcType.hashCode ^
      dcFormat.hashCode ^
      dcIdentifier.hashCode ^
      dcLanguage.hashCode ^
      dcRights.hashCode ^
      article.hashCode ^
      hreflangs.hashCode ^
      favicons.hashCode ^
      headings.hashCode ^
      wordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          canonicalUrl == other.canonicalUrl &&
          keywords == other.keywords &&
          author == other.author &&
          viewport == other.viewport &&
          themeColor == other.themeColor &&
          generator == other.generator &&
          robots == other.robots &&
          htmlLang == other.htmlLang &&
          htmlDir == other.htmlDir &&
          ogTitle == other.ogTitle &&
          ogType == other.ogType &&
          ogImage == other.ogImage &&
          ogDescription == other.ogDescription &&
          ogUrl == other.ogUrl &&
          ogSiteName == other.ogSiteName &&
          ogLocale == other.ogLocale &&
          ogVideo == other.ogVideo &&
          ogAudio == other.ogAudio &&
          ogLocaleAlternates == other.ogLocaleAlternates &&
          twitterCard == other.twitterCard &&
          twitterTitle == other.twitterTitle &&
          twitterDescription == other.twitterDescription &&
          twitterImage == other.twitterImage &&
          twitterSite == other.twitterSite &&
          twitterCreator == other.twitterCreator &&
          dcTitle == other.dcTitle &&
          dcCreator == other.dcCreator &&
          dcSubject == other.dcSubject &&
          dcDescription == other.dcDescription &&
          dcPublisher == other.dcPublisher &&
          dcDate == other.dcDate &&
          dcType == other.dcType &&
          dcFormat == other.dcFormat &&
          dcIdentifier == other.dcIdentifier &&
          dcLanguage == other.dcLanguage &&
          dcRights == other.dcRights &&
          article == other.article &&
          hreflangs == other.hreflangs &&
          favicons == other.favicons &&
          headings == other.headings &&
          wordCount == other.wordCount;
}

class ProxyConfig {
  final String url;
  final String? username;
  final String? password;

  const ProxyConfig({
    required this.url,
    this.username,
    this.password,
  });

  @override
  int get hashCode => url.hashCode ^ username.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyConfig &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          username == other.username &&
          password == other.password;
}

class ResponseMeta {
  final String? etag;
  final String? lastModified;
  final String? cacheControl;
  final String? server;
  final String? xPoweredBy;
  final String? contentLanguage;
  final String? contentEncoding;

  const ResponseMeta({
    this.etag,
    this.lastModified,
    this.cacheControl,
    this.server,
    this.xPoweredBy,
    this.contentLanguage,
    this.contentEncoding,
  });

  @override
  int get hashCode =>
      etag.hashCode ^
      lastModified.hashCode ^
      cacheControl.hashCode ^
      server.hashCode ^
      xPoweredBy.hashCode ^
      contentLanguage.hashCode ^
      contentEncoding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResponseMeta &&
          runtimeType == other.runtimeType &&
          etag == other.etag &&
          lastModified == other.lastModified &&
          cacheControl == other.cacheControl &&
          server == other.server &&
          xPoweredBy == other.xPoweredBy &&
          contentLanguage == other.contentLanguage &&
          contentEncoding == other.contentEncoding;
}

class ScrapeResult {
  final PlatformInt64 statusCode;
  final String contentType;
  final String html;
  final PlatformInt64 bodySize;
  final PageMetadata metadata;
  final List<LinkInfo> links;
  final List<ImageInfo> images;
  final List<FeedInfo> feeds;
  final List<JsonLdEntry> jsonLd;
  final bool isAllowed;
  final PlatformInt64? crawlDelay;
  final bool noindexDetected;
  final bool nofollowDetected;
  final String? xRobotsTag;
  final bool isPdf;
  final bool wasSkipped;
  final String? detectedCharset;
  final bool authHeaderSent;
  final ResponseMeta? responseMeta;
  final List<DownloadedAsset> assets;
  final bool jsRenderHint;
  final bool browserUsed;
  final MarkdownResult? markdown;
  final String? extractedData;
  final ExtractionMeta? extractionMeta;
  final DownloadedDocument? downloadedDocument;

  const ScrapeResult({
    required this.statusCode,
    required this.contentType,
    required this.html,
    required this.bodySize,
    required this.metadata,
    required this.links,
    required this.images,
    required this.feeds,
    required this.jsonLd,
    required this.isAllowed,
    this.crawlDelay,
    required this.noindexDetected,
    required this.nofollowDetected,
    this.xRobotsTag,
    required this.isPdf,
    required this.wasSkipped,
    this.detectedCharset,
    required this.authHeaderSent,
    this.responseMeta,
    required this.assets,
    required this.jsRenderHint,
    required this.browserUsed,
    this.markdown,
    this.extractedData,
    this.extractionMeta,
    this.downloadedDocument,
  });

  @override
  int get hashCode =>
      statusCode.hashCode ^
      contentType.hashCode ^
      html.hashCode ^
      bodySize.hashCode ^
      metadata.hashCode ^
      links.hashCode ^
      images.hashCode ^
      feeds.hashCode ^
      jsonLd.hashCode ^
      isAllowed.hashCode ^
      crawlDelay.hashCode ^
      noindexDetected.hashCode ^
      nofollowDetected.hashCode ^
      xRobotsTag.hashCode ^
      isPdf.hashCode ^
      wasSkipped.hashCode ^
      detectedCharset.hashCode ^
      authHeaderSent.hashCode ^
      responseMeta.hashCode ^
      assets.hashCode ^
      jsRenderHint.hashCode ^
      browserUsed.hashCode ^
      markdown.hashCode ^
      extractedData.hashCode ^
      extractionMeta.hashCode ^
      downloadedDocument.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrapeResult &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          contentType == other.contentType &&
          html == other.html &&
          bodySize == other.bodySize &&
          metadata == other.metadata &&
          links == other.links &&
          images == other.images &&
          feeds == other.feeds &&
          jsonLd == other.jsonLd &&
          isAllowed == other.isAllowed &&
          crawlDelay == other.crawlDelay &&
          noindexDetected == other.noindexDetected &&
          nofollowDetected == other.nofollowDetected &&
          xRobotsTag == other.xRobotsTag &&
          isPdf == other.isPdf &&
          wasSkipped == other.wasSkipped &&
          detectedCharset == other.detectedCharset &&
          authHeaderSent == other.authHeaderSent &&
          responseMeta == other.responseMeta &&
          assets == other.assets &&
          jsRenderHint == other.jsRenderHint &&
          browserUsed == other.browserUsed &&
          markdown == other.markdown &&
          extractedData == other.extractedData &&
          extractionMeta == other.extractionMeta &&
          downloadedDocument == other.downloadedDocument;
}

class SitemapUrl {
  final String url;
  final String? lastmod;
  final String? changefreq;
  final String? priority;

  const SitemapUrl({
    required this.url,
    this.lastmod,
    this.changefreq,
    this.priority,
  });

  @override
  int get hashCode =>
      url.hashCode ^ lastmod.hashCode ^ changefreq.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SitemapUrl &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          lastmod == other.lastmod &&
          changefreq == other.changefreq &&
          priority == other.priority;
}
