// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc01a1c094d3c52a5b52b4a912620f9a716410d5ef08dea3520ea2a80cd328ad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;

/// <summary>
/// The result of crawling a single page during a crawl operation.
/// </summary>
public sealed record CrawlPageResult
{
    /// <summary>
    /// The original URL of the page.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; init; } = "";

    /// <summary>
    /// The normalized URL of the page.
    /// </summary>
    [JsonPropertyName("normalized_url")]
    public string NormalizedUrl { get; init; } = "";

    /// <summary>
    /// The HTTP status code of the response.
    /// </summary>
    [JsonPropertyName("status_code")]
    public ushort StatusCode { get; init; } = 0;

    /// <summary>
    /// The Content-Type header value.
    /// </summary>
    [JsonPropertyName("content_type")]
    public string ContentType { get; init; } = "";

    /// <summary>
    /// The HTML body of the response.
    /// </summary>
    [JsonPropertyName("html")]
    public string Html { get; init; } = "";

    /// <summary>
    /// The size of the response body in bytes.
    /// </summary>
    [JsonPropertyName("body_size")]
    public ulong BodySize { get; init; } = 0;

    /// <summary>
    /// Extracted metadata from the page.
    /// </summary>
    [JsonPropertyName("metadata")]
    public PageMetadata Metadata { get; init; } = default!;

    /// <summary>
    /// Links found on the page.
    /// </summary>
    [JsonPropertyName("links")]
    public List<LinkInfo> Links { get; init; } = [];

    /// <summary>
    /// Images found on the page.
    /// </summary>
    [JsonPropertyName("images")]
    public List<ImageInfo> Images { get; init; } = [];

    /// <summary>
    /// Feed links found on the page.
    /// </summary>
    [JsonPropertyName("feeds")]
    public List<FeedInfo> Feeds { get; init; } = [];

    /// <summary>
    /// JSON-LD entries found on the page.
    /// </summary>
    [JsonPropertyName("json_ld")]
    public List<JsonLdEntry> JsonLd { get; init; } = [];

    /// <summary>
    /// The depth of this page from the start URL.
    /// </summary>
    [JsonPropertyName("depth")]
    public ulong Depth { get; init; } = 0;

    /// <summary>
    /// Whether this page is on the same domain as the start URL.
    /// </summary>
    [JsonPropertyName("stayed_on_domain")]
    public bool StayedOnDomain { get; init; } = false;

    /// <summary>
    /// Whether this page was skipped (binary or PDF content).
    /// </summary>
    [JsonPropertyName("was_skipped")]
    public bool WasSkipped { get; init; } = false;

    /// <summary>
    /// Whether the content is a PDF.
    /// </summary>
    [JsonPropertyName("is_pdf")]
    public bool IsPdf { get; init; } = false;

    /// <summary>
    /// The detected character set encoding.
    /// </summary>
    [JsonPropertyName("detected_charset")]
    public string? DetectedCharset { get; init; } = null;

    /// <summary>
    /// Markdown conversion of the page content.
    /// </summary>
    [JsonPropertyName("markdown")]
    public MarkdownResult? Markdown { get; init; } = null;

    /// <summary>
    /// Structured data extracted by LLM. Populated when extraction is configured.
    /// </summary>
    [JsonPropertyName("extracted_data")]
    public JsonElement? ExtractedData { get; init; } = null;

    /// <summary>
    /// Metadata about the LLM extraction pass (cost, tokens, model).
    /// </summary>
    [JsonPropertyName("extraction_meta")]
    public ExtractionMeta? ExtractionMeta { get; init; } = null;

    /// <summary>
    /// Downloaded non-HTML document (PDF, DOCX, image, code, etc.).
    /// </summary>
    [JsonPropertyName("downloaded_document")]
    public DownloadedDocument? DownloadedDocument { get; init; } = null;

    /// <summary>
    /// Whether the browser fallback was used to fetch this page.
    /// </summary>
    [JsonPropertyName("browser_used")]
    public bool BrowserUsed { get; init; } = false;


    /// <summary>
    /// Parse a <see cref="CrawlPageResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="CrawlbergException">When the JSON cannot be deserialised.</exception>
    public static CrawlPageResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CrawlPageResult>(json, JsonOptions)
                ?? throw new CrawlbergException($"Failed to parse CrawlPageResult from JSON: deserializer returned null");
        }
        catch (CrawlbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new CrawlbergException($"Failed to parse CrawlPageResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
