// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7db82d763cd344ffc74fa180dfd1cbbd7f469728ffa6991f10ad5f87946b1c75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzcrawl
import RustBridge

/// E2e tests for category: auth.
final class AuthTests: XCTestCase {
    func testAuthBasicHttp() async throws {
        // Sends HTTP Basic authentication header
        let engineConfig = try crawlConfigFromJson("{\"auth\":{\"password\":\"testpass\",\"type\":\"basic\",\"username\":\"testuser\"},\"respect_robots_txt\":false}")
        let engineObj = try createEngine(config: engineConfig)
        let url = AlefE2EMockServer.baseURL + "/fixtures/auth_basic_http"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertEqual(result.authHeaderSent(), true)
        XCTAssertEqual(result.statusCode(), 200)
    }

    func testAuthBearerToken() async throws {
        // Sends Bearer token in Authorization header
        let engineConfig = try crawlConfigFromJson("{\"auth\":{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test\",\"type\":\"bearer\"},\"respect_robots_txt\":false}")
        let engineObj = try createEngine(config: engineConfig)
        let url = AlefE2EMockServer.baseURL + "/fixtures/auth_bearer_token"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertEqual(result.authHeaderSent(), true)
        XCTAssertEqual(result.statusCode(), 200)
    }

    func testAuthCustomHeader() async throws {
        // Sends authentication via custom header (X-API-Key)
        let engineConfig = try crawlConfigFromJson("{\"auth\":{\"name\":\"X-API-Key\",\"type\":\"header\",\"value\":\"sk-test-key-12345\"},\"respect_robots_txt\":false}")
        let engineObj = try createEngine(config: engineConfig)
        let url = AlefE2EMockServer.baseURL + "/fixtures/auth_custom_header"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertEqual(result.authHeaderSent(), true)
        XCTAssertEqual(result.statusCode(), 200)
    }

}
