// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77f1a61ba13dc75c45fe807b3ad2b81ea95bf692b455bad7bdaede41684dbdee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzcrawl
import RustBridge

/// E2e tests for category: browser.
final class BrowserTests: XCTestCase {
    func testBrowserConfigAutoNoFeature() async throws {
        // Browser mode 'auto' without browser feature enabled does not use browser
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"auto\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_config_auto_no_feature"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserConfigNeverMode() async throws {
        // Browser mode 'never' prevents browser fallback even for SPA shell content
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"never\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_config_never_mode"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserCrawlModeAlways() async throws {
        // Crawl with browser mode 'always' follows links using browser rendering
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"always\"},\"max_depth\":1,\"respect_robots_txt\":false}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_crawl_mode_always"
        let result = try await scrape(engineObj, url)
        // skipped: field 'pages.length' not available on result type
        XCTAssertEqual(result.browser().browser_used(), true)
    }

    func testBrowserCrawlWafFallback() async throws {
        // Crawl with browser mode 'auto' falls back to browser when encountering WAF 403
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"auto\"},\"max_depth\":1,\"respect_robots_txt\":false}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_crawl_waf_fallback"
        let result = try await scrape(engineObj, url)
        // skipped: field 'pages.length' not available on result type
    }

    func testBrowserDetectMinimalPage() async throws {
        // Does NOT flag a short but real content page as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_minimal_page"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), false)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectNextEmpty() async throws {
        // Detects Next.js page with __NEXT_DATA__ but no rendered content as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_next_empty"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectNextRendered() async throws {
        // Does NOT flag Next.js page with full SSR content as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_next_rendered"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
        XCTAssertEqual(result.browser().js_render_hint(), false)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectNormalPage() async throws {
        // Does NOT flag a normal server-rendered page as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_normal_page"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), false)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectNuxtShell() async throws {
        // Detects Nuxt SPA shell with empty #__nuxt div as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_nuxt_shell"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectReactShell() async throws {
        // Detects React SPA shell with empty #root div as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_react_shell"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserDetectVueShell() async throws {
        // Detects Vue SPA shell with empty #app div as needing JS rendering
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_detect_vue_shell"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), false)
    }

    func testBrowserExtraWait() async throws {
        // Browser extra_wait adds additional time after network_idle to ensure all async operations complete
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"extra_wait\":200,\"mode\":\"always\",\"wait\":\"network_idle\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_extra_wait"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
    }

    func testBrowserFallbackSpaRender() async throws {
        // Browser auto re-fetches SPA shell when JS rendering is detected
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"auto\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_fallback_spa_render"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().js_render_hint(), true)
        XCTAssertEqual(result.browser().browser_used(), true)
    }

    func testBrowserFallbackWafBlocked() async throws {
        // Browser fallback triggers when WAF blocks the HTTP request (Cloudflare 403)
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"auto\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_fallback_waf_blocked"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
    }

    func testBrowserModeAlways() async throws {
        // Browser mode 'always' uses browser even for normal server-rendered pages
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"always\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_mode_always"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
    }

    func testBrowserProfileBasic() async throws {
        // Browser profile configuration persists and reuses browser state across crawl sessions
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"always\"},\"browser_profile\":\"test-profile\"}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_profile_basic"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
        XCTAssertEqual(result.status_code(), 200)
    }

    func testBrowserWaitFixed() async throws {
        // Browser wait strategy 'fixed' waits for a specific duration after page navigation
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"extra_wait\":100,\"mode\":\"always\",\"wait\":\"fixed\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_wait_fixed"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
        XCTAssertEqual(result.status_code(), 200)
    }

    func testBrowserWaitSelector() async throws {
        // Browser wait strategy 'selector' waits for specific CSS selector before considering page loaded
        let engineConfig = try crawlConfigFromJson("{\"browser\":{\"mode\":\"always\",\"wait\":\"selector\",\"wait_selector\":\"#content\"}}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/browser_wait_selector"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.browser().browser_used(), true)
        XCTAssertEqual(result.status_code(), 200)
    }

}
