// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35d10f6bf1b6cb6bee95309ee1fa022e85bfb0fcc608fb9975504e1cad50ee18
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzcrawl

/// E2e tests for category: encoding.
final class EncodingTests: XCTestCase {
    func testEncodingDoubleEncoded() async throws {
        // Handles double-encoded URL characters (%25C3%25B6)
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENCODING_DOUBLE_ENCODED"] ?? (ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/encoding_double_encoded")
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.links().count, UInt(1))
    }

    func testEncodingMixedCharsetPage() async throws {
        // Handles charset mismatch between HTTP header and HTML meta tag
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/encoding_mixed_charset_page"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
    }

    func testEncodingPercentEncodedPath() async throws {
        // Handles percent-encoded spaces and characters in URL paths
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENCODING_PERCENT_ENCODED_PATH"] ?? (ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/encoding_percent_encoded_path")
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.links().count, UInt(2))
    }

    func testEncodingUnicodeUrl() async throws {
        // Handles Unicode characters in URLs (Hebrew, Japanese, Cyrillic)
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/encoding_unicode_url"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.html().toString().count, 0, "expected non-empty value")
    }

}
