// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9690695f591c4fcd431c87cf43bb1fc1ef52354a64ff87bcb7323a89566005d2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzcrawl
import RustBridge

/// E2e tests for category: engine.
final class EngineTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "KREUZCRAWL_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testEngineBatchBasic() async throws {
        // CrawlEngine with defaults batch scrapes like the free function
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/engine_batch_basic"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        // skipped: field 'batch.completed_count' not available on result type
        // skipped: field 'batch.total_count' not available on result type
    }

    func testEngineCrawlBasic() async throws {
        // CrawlEngine with defaults crawls multiple pages like the free function
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENGINE_CRAWL_BASIC"] ?? (AlefE2EMockServer.baseURL + "/fixtures/engine_crawl_basic")
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        // skipped: field 'crawl.pages_crawled' not available on result type
        // skipped: field 'crawl.min_pages' not available on result type
    }

    func testEngineMapBasic() async throws {
        // CrawlEngine with defaults discovers URLs like the free function
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENGINE_MAP_BASIC"] ?? (AlefE2EMockServer.baseURL + "/fixtures/engine_map_basic")
        let result = try await Kreuzcrawl.mapUrls(engine: engineObj, url: url)
        // skipped: field 'map.min_urls' not available on result type
    }

    func testEngineScrapeBasic() async throws {
        // CrawlEngine with defaults scrapes a page identically to the free function
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENGINE_SCRAPE_BASIC"] ?? (AlefE2EMockServer.baseURL + "/fixtures/engine_scrape_basic")
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertEqual(result.statusCode(), 200)
        XCTAssertEqual(result.contentType().toString().trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "text/html")
        XCTAssertEqual((result.metadata().title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Engine Test")
        XCTAssertTrue("Testing the engine".isEmpty || (result.metadata().description()?.toString() ?? "").contains("Testing the engine"), "expected to contain: \("Testing the engine")")
        XCTAssertGreaterThanOrEqual(result.links().count, 1)
        XCTAssertGreaterThanOrEqual((result.metadata().headings()?.count ?? 0), 1)
    }

    func testEngineStreamBasic() async throws {
        // CrawlEngine with defaults streams events like the free function
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_ENGINE_STREAM_BASIC"] ?? (AlefE2EMockServer.baseURL + "/fixtures/engine_stream_basic")
        let urlRequest = CrawlStreamRequest(url: url)
        let result = try await Kreuzcrawl.crawlStream(engineObj, urlRequest)
        var chunks: [Kreuzcrawl.CrawlEvent] = []
                for try await _chunk in result { chunks.append(_chunk) }
        // streaming field 'stream.event_count_min': assertion type 'greater_than_or_equal' not rendered
    }

}
