// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8de9ecdcfa2a96fe203ccc4c086b6d0517047b314a4ea634abbbd69a0122c498
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzcrawl
import RustBridge

/// E2e tests for category: rate_limit.
final class RateLimitTests: XCTestCase {
    func testRateLimitAdaptiveBackoff() async throws {
        // Exponential backoff retry succeeds after 429 Too Many Requests
        let engineConfig = try crawlConfigFromJson("{\"respect_robots_txt\":false,\"retry_codes\":[429],\"retry_count\":2}")
        let engineObj = try createEngine(config: engineConfig)
        let url = AlefE2EMockServer.baseURL + "/fixtures/rate_limit_adaptive_backoff"
        let result = try await Kreuzcrawl.scrape(engine: engineObj, url: url)
        XCTAssertEqual(result.statusCode(), 200)
    }

    func testRateLimitBasicDelay() async throws {
        // Rate limiter adds delay between requests to the same domain
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_RATE_LIMIT_BASIC_DELAY"] ?? (AlefE2EMockServer.baseURL + "/fixtures/rate_limit_basic_delay")
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        XCTAssertEqual(result.pages().count, 3)
        // skipped: field 'rate_limit.min_duration_ms' not available on result type
    }

    func testRateLimitPerDomain() async throws {
        // Per-domain rate limiting applies delay between requests to same domain
        let engineConfig = try crawlConfigFromJson("{\"max_concurrent\":1,\"max_depth\":1}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_RATE_LIMIT_PER_DOMAIN"] ?? (AlefE2EMockServer.baseURL + "/fixtures/rate_limit_per_domain")
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        XCTAssertGreaterThanOrEqual(result.pages().count, 2)
        let _vec_pages_equals_29fea8bb = result.pages()
        XCTAssertEqual(_vec_pages_equals_29fea8bb[0].statusCode(), 200)
    }

    func testRateLimitRobotsCrawlDelay() async throws {
        // Respects Crawl-delay directive in robots.txt
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1,\"respect_robots_txt\":true,\"user_agent\":\"TestBot\"}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_RATE_LIMIT_ROBOTS_CRAWL_DELAY"] ?? (AlefE2EMockServer.baseURL + "/fixtures/rate_limit_robots_crawl_delay")
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        XCTAssertGreaterThanOrEqual(result.pages().count, 1)
        let _vec_pages_equals_29fea8bb = result.pages()
        XCTAssertEqual(_vec_pages_equals_29fea8bb[0].statusCode(), 200)
    }

    func testRateLimitZeroNoDelay() async throws {
        // Rate limiter with zero delay does not slow crawling
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":1}")
        let engineObj = try createEngine(config: engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_RATE_LIMIT_ZERO_NO_DELAY"] ?? (AlefE2EMockServer.baseURL + "/fixtures/rate_limit_zero_no_delay")
        let result = try await Kreuzcrawl.crawl(engine: engineObj, url: url)
        XCTAssertEqual(result.pages().count, 2)
    }

}
