// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdebfebf7f3212dd369fbd7b87a0af7c12cf1b457e39e7a633f50c00f5466673
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzcrawl = @import("kreuzcrawl");

// E2e tests for category: concurrent

test "concurrent_basic" {
    // Concurrent crawling fetches all pages with max_concurrent workers
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_CONCURRENT_BASIC")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/concurrent_basic", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try kreuzcrawl.crawl("{\"max_concurrent\":3,\"max_depth\":1}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(6, result.object.get("pages").?.array.items.len);
    try testing.expect(result.object.get("pages").?.array.items.len >= 6);
}

test "concurrent_depth_two_fan_out" {
    // Concurrent depth=2 crawl correctly fans out and deduplicates across levels
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_CONCURRENT_DEPTH_TWO_FAN_OUT")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/concurrent_depth_two_fan_out", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try kreuzcrawl.crawl("{\"max_concurrent\":3,\"max_depth\":2}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(4, result.object.get("pages").?.array.items.len);
}

test "concurrent_max_pages_exact" {
    // Concurrent crawling does not exceed max_pages limit even with high concurrency
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_CONCURRENT_MAX_PAGES_EXACT")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/concurrent_max_pages_exact", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try kreuzcrawl.crawl("{\"max_concurrent\":5,\"max_depth\":1,\"max_pages\":3}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(result.object.get("pages").?.array.items.len <= 3);
}

test "concurrent_partial_errors" {
    // Concurrent crawl handles partial failures gracefully
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_CONCURRENT_PARTIAL_ERRORS")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/concurrent_partial_errors", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try kreuzcrawl.crawl("{\"max_concurrent\":3,\"max_depth\":1}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(result.object.get("pages").?.array.items.len >= 2);
}

test "concurrent_respects_max_pages" {
    // Concurrent crawling respects max_pages limit
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_CONCURRENT_RESPECTS_MAX_PAGES")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/concurrent_respects_max_pages", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try kreuzcrawl.crawl("{\"max_concurrent\":2,\"max_depth\":1,\"max_pages\":3}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(result.object.get("pages").?.array.items.len <= 3);
}
