// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:57feec74582e5e21b13fb7454459b861e50529c1cf030ff2b6a447177656fa75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import { scrape, crawl, createEngine } from "@kreuzberg/kreuzcrawl";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
  if (fm == null) return "";
  if (typeof fm !== "object") return String(fm);
  const record = fm as Record<string, unknown>;
  const formatType = record.format_type;

  // FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
  // Extract the display string based on the variant type
  if (formatType === "image" && typeof record.image === "object") {
    const imageData = record.image as Record<string, unknown>;
    if (typeof imageData.format === "string") return imageData.format;
  }

  // Fallback: return format_type variant name
  if (typeof record.format_type === "string") return record.format_type;
  return "";
}

describe("concurrent", () => {
  it("concurrent_basic: Concurrent crawling fetches all pages with max_concurrent workers", async () => {
    const engineConfig = { maxConcurrent: 3, maxDepth: 1 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CONCURRENT_BASIC ??
      `${process.env.MOCK_SERVER_URL}/fixtures/concurrent_basic`;
    const result = await crawl(engine, url);
    expect(result.pages.length).toBe(6);
    expect(result.pages.length).toBeGreaterThanOrEqual(6);
  }, 30000);
  it("concurrent_depth_two_fan_out: Concurrent depth=2 crawl correctly fans out and deduplicates across levels", async () => {
    const engineConfig = { maxConcurrent: 3, maxDepth: 2 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CONCURRENT_DEPTH_TWO_FAN_OUT ??
      `${process.env.MOCK_SERVER_URL}/fixtures/concurrent_depth_two_fan_out`;
    const result = await crawl(engine, url);
    expect(result.pages.length).toBe(4);
  }, 30000);
  it("concurrent_max_pages_exact: Concurrent crawling does not exceed max_pages limit even with high concurrency", async () => {
    const engineConfig = { maxConcurrent: 5, maxDepth: 1, maxPages: 3 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CONCURRENT_MAX_PAGES_EXACT ??
      `${process.env.MOCK_SERVER_URL}/fixtures/concurrent_max_pages_exact`;
    const result = await crawl(engine, url);
    expect(result.pages.length).toBeLessThanOrEqual(3);
  }, 30000);
  it("concurrent_partial_errors: Concurrent crawl handles partial failures gracefully", async () => {
    const engineConfig = { maxConcurrent: 3, maxDepth: 1 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CONCURRENT_PARTIAL_ERRORS ??
      `${process.env.MOCK_SERVER_URL}/fixtures/concurrent_partial_errors`;
    const result = await crawl(engine, url);
    expect(result.pages.length).toBeGreaterThanOrEqual(2);
  }, 30000);
  it("concurrent_respects_max_pages: Concurrent crawling respects max_pages limit", async () => {
    const engineConfig = { maxConcurrent: 2, maxDepth: 1, maxPages: 3 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CONCURRENT_RESPECTS_MAX_PAGES ??
      `${process.env.MOCK_SERVER_URL}/fixtures/concurrent_respects_max_pages`;
    const result = await crawl(engine, url);
    expect(result.pages.length).toBeLessThanOrEqual(3);
  }, 30000);
});
