// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f44586682b0fc2fbd6041f30d9133ee78900dafb10ba458670117f0301ecbbfd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import { scrape, batchCrawlStream, crawlStream, createEngine } from "@kreuzberg/kreuzcrawl";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
  if (fm == null) return "";
  if (typeof fm !== "object") return String(fm);
  const record = fm as Record<string, unknown>;
  const formatType = record.format_type;

  // FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
  // Extract the display string based on the variant type
  if (formatType === "image" && typeof record.image === "object") {
    const imageData = record.image as Record<string, unknown>;
    if (typeof imageData.format === "string") return imageData.format;
  }

  // Fallback: return format_type variant name
  if (typeof record.format_type === "string") return record.format_type;
  return "";
}

describe("stream", () => {
  it("batch_crawl_stream_events: Batch crawl stream produces expected Page and Complete events", async () => {
    const engineConfig = { maxConcurrent: 2 };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/batch_crawl_stream_events`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.length).toBeGreaterThanOrEqual(4);
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("batch_crawl_stream_partial_failure: Batch crawl stream emits both Page and Error events for mixed success/failure URLs", async () => {
    const engineConfig = { maxConcurrent: 1 };
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/batch_crawl_stream_partial_failure`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "error")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("crawl_stream_events: Crawl stream produces page and complete events", async () => {
    const engineConfig = { maxDepth: 1, respectRobotsTxt: false };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_CRAWL_STREAM_EVENTS ??
      `${process.env.MOCK_SERVER_URL}/fixtures/crawl_stream_events`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.length).toBeGreaterThanOrEqual(4);
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("stream_depth_crawl: Stream produces events for multi-depth crawl with link following", async () => {
    const engineConfig = { maxConcurrent: 1, maxDepth: 2 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_STREAM_DEPTH_CRAWL ??
      `${process.env.MOCK_SERVER_URL}/fixtures/stream_depth_crawl`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.length).toBeGreaterThanOrEqual(5);
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("stream_error_event_mid_crawl: Stream emits error event when a page fails mid-crawl, but other pages succeed", async () => {
    const engineConfig = { maxConcurrent: 1, maxDepth: 1, respectRobotsTxt: false };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_STREAM_ERROR_EVENT_MID_CRAWL ??
      `${process.env.MOCK_SERVER_URL}/fixtures/stream_error_event_mid_crawl`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "error")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("stream_event_ordering: Stream ensures complete event arrives after all page events", async () => {
    const engineConfig = { maxConcurrent: 1, maxDepth: 1, respectRobotsTxt: false };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_STREAM_EVENT_ORDERING ??
      `${process.env.MOCK_SERVER_URL}/fixtures/stream_event_ordering`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.length).toBeGreaterThanOrEqual(3);
  });
  it("stream_large_crawl: Stream handles crawl of 5+ pages with multiple events", async () => {
    const engineConfig = { maxDepth: 1, respectRobotsTxt: false };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_STREAM_LARGE_CRAWL ??
      `${process.env.MOCK_SERVER_URL}/fixtures/stream_large_crawl`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.length).toBeGreaterThanOrEqual(6);
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
  });
  it("stream_with_error_event: Stream emits page and complete events even when some pages fail", async () => {
    const engineConfig = { maxConcurrent: 1, maxDepth: 1 };
    const engine = createEngine(engineConfig);
    const url =
      process.env.MOCK_SERVER_STREAM_WITH_ERROR_EVENT ??
      `${process.env.MOCK_SERVER_URL}/fixtures/stream_with_error_event`;
    const stream = await crawlStream(engine, url);
    const chunks: any[] = [];
    for await (const _chunk of stream) {
      chunks.push(_chunk);
    }
    expect(chunks.some((e: any) => e?.type === "page")).toBe(true);
    expect(chunks.some((e: any) => e?.type === "complete")).toBe(true);
    expect(chunks.length).toBeGreaterThanOrEqual(2);
  });
});
