// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0eab3539dd01cb6d0df8fba44f697d2d6be190216721ace0203cec2be3c98844
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The source of an image reference.
 */
@SuppressWarnings("PMD")
public enum ImageSource {
  /**
   * An {@code &lt;img&gt;} tag.
   */
  Img("img"),
  /**
   * A {@code &lt;source&gt;} tag inside {@code &lt;picture&gt;}.
   */
  PictureSource("picture_source"),
  /**
   * An {@code og:image} meta tag.
   */
  OgImage("og:image"),
  /**
   * A {@code twitter:image} meta tag.
   */
  TwitterImage("twitter:image");

  /** The string value. */
  private final String value;

  ImageSource(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ImageSource fromValue(final String value) {
    for (ImageSource e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ImageSource value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
