// Generated by alef — intentionally empty.
// alef:hash:fc914c28abe3a106c0a659306be7c739d76eca1afdd9b46838a60ee8f5ed0fb3
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
