# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3a10ec84c96fbbc537842874775fecb006c9301c7cc20764679f80d954a78fd3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

"""E2e tests for category: cookies."""

import os
import pytest  # noqa: F401
from kreuzcrawl import crawl, create_engine, CrawlConfig


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_cookies_per_domain() -> None:
    """Isolates cookies per domain during crawl."""
    engine_config = CrawlConfig(
        cookies_enabled=True, max_depth=1, respect_robots_txt=False
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_COOKIES_PER_DOMAIN")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/cookies_per_domain"
    )

    result = await crawl(engine, url)
    assert len(result.cookies) == 1  # noqa: S101
    assert any(
        "domain_cookie" in text
        for item in result.cookies
        for text in _alef_e2e_item_texts(item)
    )  # noqa: S101


@pytest.mark.asyncio
async def test_cookies_persistence() -> None:
    """Maintains cookies across multiple crawl requests."""
    engine_config = CrawlConfig(
        cookies_enabled=True, max_depth=1, respect_robots_txt=False
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_COOKIES_PERSISTENCE")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/cookies_persistence"
    )

    result = await crawl(engine, url)
    assert any(
        "session" in text
        for item in result.cookies
        for text in _alef_e2e_item_texts(item)
    )  # noqa: S101


@pytest.mark.asyncio
async def test_cookies_set_cookie_response() -> None:
    """Respects Set-Cookie header from server responses."""
    engine_config = CrawlConfig(
        cookies_enabled=True, max_depth=1, respect_robots_txt=False
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_COOKIES_SET_COOKIE_RESPONSE")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/cookies_set_cookie_response"
    )

    result = await crawl(engine, url)
    assert any(
        "tracking" in text
        for item in result.cookies
        for text in _alef_e2e_item_texts(item)
    )  # noqa: S101
