# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: validation."""
import os

import pytest
from kreuzcrawl import scrape, create_engine, CrawlConfig


@pytest.mark.asyncio
async def test_validation_invalid_exclude_regex() -> None:
    """Invalid regex in exclude_paths is rejected."""
    engine_config = CrawlConfig(exclude_paths=["(unclosed"])
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_invalid_exclude_regex'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "exclude_path" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_validation_invalid_include_regex() -> None:
    """Invalid regex in include_paths is rejected."""
    engine_config = CrawlConfig(include_paths=["[invalid"])
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_invalid_include_regex'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "include_path" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_validation_invalid_retry_code() -> None:
    """Retry code outside 100-599 is rejected."""
    engine_config = CrawlConfig(retry_codes=[999])
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_invalid_retry_code'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "retry code" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_validation_max_pages_zero() -> None:
    """max_pages=0 is rejected as invalid config."""
    engine_config = CrawlConfig(max_pages=0)
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_max_pages_zero'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "max_pages" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_validation_max_redirects_too_high() -> None:
    """max_redirects > 100 is rejected as invalid config."""
    engine_config = CrawlConfig(max_redirects=200)
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_max_redirects_too_high'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "max_redirects" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_validation_timeout_zero() -> None:
    """Zero request timeout is rejected as invalid config."""
    engine_config = CrawlConfig(request_timeout=0)
    engine = create_engine(engine_config)
    url = os.environ['MOCK_SERVER_URL'] + '/fixtures/validation_timeout_zero'
    with pytest.raises(Exception) as exc_info:
        await scrape(engine=engine, url=url)
    assert "request_timeout" in str(exc_info.value)  # noqa: S101

