# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:209189f862622638cbb1c767fb80d93569df1b4f69344cd027ee17ba1270ebb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

"""E2e tests for category: browser."""

import os
import pytest  # noqa: F401
from kreuzcrawl import scrape, crawl, create_engine, CrawlConfig, BrowserConfig


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_browser_config_auto_no_feature() -> None:
    """Browser mode 'auto' without browser feature enabled does not use browser."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="auto"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_config_auto_no_feature"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_config_never_mode() -> None:
    """Browser mode 'never' prevents browser fallback even for SPA shell content."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="never"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_config_never_mode"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_crawl_mode_always() -> None:
    """Crawl with browser mode 'always' follows links using browser rendering."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(mode="always"), max_depth=1, respect_robots_txt=False
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_BROWSER_CRAWL_MODE_ALWAYS")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_crawl_mode_always"
    )

    result = await crawl(engine, url)
    assert len(result.pages) >= 2  # noqa: S101
    # skipped: field 'browser_used' not available on result type


@pytest.mark.asyncio
async def test_browser_crawl_waf_fallback() -> None:
    """Crawl with browser mode 'auto' falls back to browser when encountering WAF 403."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(mode="auto"), max_depth=1, respect_robots_txt=False
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_BROWSER_CRAWL_WAF_FALLBACK")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_crawl_waf_fallback"
    )

    result = await crawl(engine, url)
    assert len(result.pages) >= 1  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_minimal_page() -> None:
    """Does NOT flag a short but real content page as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_minimal_page"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is False  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_next_empty() -> None:
    """Detects Next.js page with __NEXT_DATA__ but no rendered content as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_next_empty"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_next_rendered() -> None:
    """Does NOT flag Next.js page with full SSR content as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_next_rendered"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.html  # noqa: S101
    assert result.js_render_hint is False  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_normal_page() -> None:
    """Does NOT flag a normal server-rendered page as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_normal_page"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is False  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_nuxt_shell() -> None:
    """Detects Nuxt SPA shell with empty #__nuxt div as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_nuxt_shell"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_react_shell() -> None:
    """Detects React SPA shell with empty #root div as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_react_shell"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.html  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_detect_vue_shell() -> None:
    """Detects Vue SPA shell with empty #app div as needing JS rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_detect_vue_shell"

    result = await scrape(engine, url)
    assert result.status_code == 200  # noqa: S101
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is False  # noqa: S101


@pytest.mark.asyncio
async def test_browser_extra_wait() -> None:
    """Browser extra_wait adds additional time after network_idle to ensure all async operations complete."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(extra_wait=200, mode="always", wait="network_idle")
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_extra_wait"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101


@pytest.mark.asyncio
async def test_browser_fallback_spa_render() -> None:
    """Browser auto re-fetches SPA shell when JS rendering is detected."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="auto"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_fallback_spa_render"

    result = await scrape(engine, url)
    assert result.js_render_hint is True  # noqa: S101
    assert result.browser_used is True  # noqa: S101


@pytest.mark.asyncio
async def test_browser_fallback_waf_blocked() -> None:
    """Browser fallback is used when browser mode is always, simulating WAF-blocked scenario."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_fallback_waf_blocked"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101


@pytest.mark.asyncio
async def test_browser_mode_always() -> None:
    """Browser mode 'always' uses browser even for normal server-rendered pages."""
    engine_config = CrawlConfig(browser=BrowserConfig(mode="always"))
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_mode_always"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101


@pytest.mark.asyncio
async def test_browser_profile_basic() -> None:
    """Browser profile configuration persists and reuses browser state across crawl sessions."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(mode="always"), browser_profile="test-profile"
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_profile_basic"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101


@pytest.mark.asyncio
async def test_browser_wait_fixed() -> None:
    """Browser wait strategy 'fixed' waits for a specific duration after page navigation."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(extra_wait=100, mode="always", wait="fixed")
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_wait_fixed"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101


@pytest.mark.asyncio
async def test_browser_wait_selector() -> None:
    """Browser wait strategy 'selector' waits for specific CSS selector before considering page loaded."""
    engine_config = CrawlConfig(
        browser=BrowserConfig(mode="always", wait="selector", wait_selector="#content")
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/browser_wait_selector"

    result = await scrape(engine, url)
    assert result.browser_used is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101
