// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8a6ed63c611c991db270353de0034f6504528304ce2ab28a19c039e396521bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzcrawl/kreuzcrawl.dart';
import 'package:kreuzcrawl/src/kreuzcrawl_bridge_generated/frb_generated.dart'
    show RustLib;

// E2e tests for category: metadata
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test(
    'Extracts article:published_time, modified_time, author, section, and tags',
    () async {
      final engine = await KreuzcrawlBridge.createEngine();
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_article_times";
      final result = await KreuzcrawlBridge.scrape(engine, url);
      expect(result.statusCode, equals(200));
      // skipped: field 'article.published_time' not available on dart result type
      // skipped: field 'article.modified_time' not available on dart result type
      // skipped: field 'article.author' not available on dart result type
      // skipped: field 'article.section' not available on dart result type
      // skipped: field 'article.tags.length' not available on dart result type
    },
  );

  test('Extracts favicon link tags including apple-touch-icon', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_favicons";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    expect(result.statusCode, equals(200));
    // skipped: field 'favicons.length' not available on dart result type
    // skipped: field 'favicons[].apple_touch' not available on dart result type
  });

  test('Extracts heading hierarchy (h1-h6) from HTML page', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_headings";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    expect(result.statusCode, equals(200));
    // skipped: field 'headings.h1.length' not available on dart result type
    // skipped: field 'headings.h1[0].text' not available on dart result type
    // skipped: field 'headings.length' not available on dart result type
  });

  test('Extracts hreflang alternate link tags', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_hreflang";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    expect(result.statusCode, equals(200));
    // skipped: field 'hreflang.length' not available on dart result type
    // skipped: field 'hreflang[].lang' not available on dart result type
  });

  test(
    'Extracts keywords, author, viewport, generator, theme-color, robots, lang, dir metadata',
    () async {
      final engine = await KreuzcrawlBridge.createEngine();
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_keywords_author";
      final result = await KreuzcrawlBridge.scrape(engine, url);
      expect(result.statusCode, equals(200));
      expect(
        result.metadata.title.toString().trim(),
        equals('Comprehensive Metadata Test Page'.toString().trim()),
      );
      expect(result.metadata.canonicalUrl, isNotNull);
      expect(result.metadata.keywords, isNotNull);
      expect(result.metadata.keywords, contains('rust'));
      expect(
        result.metadata.author.toString().trim(),
        equals('Jane Developer'.toString().trim()),
      );
      expect(result.metadata.viewport, isNotNull);
      expect(
        result.metadata.generator.toString().trim(),
        equals('kreuzcrawl/1.0'.toString().trim()),
      );
      expect(
        result.metadata.themeColor.toString().trim(),
        equals('#ff6600'.toString().trim()),
      );
      expect(
        result.metadata.robots.toString().trim(),
        equals('index, follow'.toString().trim()),
      );
      expect(
        result.metadata.htmlLang.toString().trim(),
        equals('en'.toString().trim()),
      );
      expect(
        result.metadata.htmlDir.toString().trim(),
        equals('ltr'.toString().trim()),
      );
    },
  );

  test('Extracts og:video, og:audio, and og:locale:alternate metadata', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_og_video_audio";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    expect(result.statusCode, equals(200));
    expect(
      result.metadata.ogVideo.toString().trim(),
      equals('https://example.com/video.mp4'.toString().trim()),
    );
    expect(
      result.metadata.ogAudio.toString().trim(),
      equals('https://example.com/audio.mp3'.toString().trim()),
    );
    // skipped: field 'og.locale_alternate.length' not available on dart result type
  });

  test(
    'Extracts response metadata from HTTP headers (etag, server, content-language)',
    () async {
      final engine = await KreuzcrawlBridge.createEngine();
      final url =
          "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_response_headers";
      final result = await KreuzcrawlBridge.scrape(engine, url);
      expect(result.statusCode, equals(200));
      // skipped: field 'response_headers.etag' not available on dart result type
      // skipped: field 'response_headers.last_modified' not available on dart result type
      // skipped: field 'response_headers.server' not available on dart result type
      // skipped: field 'response_headers.content_language' not available on dart result type
    },
  );

  test('Computes word count from visible page text', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/metadata_word_count";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    expect(result.statusCode, equals(200));
    // skipped: field 'computed.word_count' not available on dart result type
    // skipped: field 'computed.word_count' not available on dart result type
  });
}
