// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9690695f591c4fcd431c87cf43bb1fc1ef52354a64ff87bcb7323a89566005d2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.kreuzcrawl.android.Kreuzcrawl

/** E2e tests for category: links. */
class LinksTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("kcrawl_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load kcrawl_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testLinksAnchorFragment() = runBlocking {
        // Identifies fragment-only links as anchor type
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getProperty("mockServer.links_anchor_fragment", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_anchor_fragment")
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.first().linkType.name.lowercase().contains("anchor"), "expected to contain: " + "anchor")
    }

    @Test
    fun testLinksBaseTag() = runBlocking {
        // Resolves relative URLs using base tag href
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_base_tag"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 2, "expected > 2")
        assertTrue(result.links.first().url.contains("example.com"), "expected to contain: " + "example.com")
    }

    @Test
    fun testLinksDocumentTypes() = runBlocking {
        // Detects PDF, DOCX, XLSX links as document type
        val engine = Kreuzcrawl.createEngine(null)
        val url = System.getProperty("mockServer.links_document_types", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_document_types")
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.first().linkType.name.lowercase().contains("document"), "expected to contain: " + "document")
    }

    @Test
    fun testLinksEmptyHref() = runBlocking {
        // Handles empty href attributes without errors
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_empty_href"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 0, "expected > 0")
        assertTrue(result.links.first().url.contains("/valid"), "expected to contain: " + "/valid")
    }

    @Test
    fun testLinksInternalExternalClassification() = runBlocking {
        // Correctly classifies internal vs external links by domain
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_internal_external_classification"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 4, "expected > 4")
        assertFalse(result.links.first().url.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testLinksMailtoJavascriptSkip() = runBlocking {
        // Skips mailto:, javascript:, and tel: scheme links
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_mailto_javascript_skip"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 0, "expected > 0")
        assertFalse(result.links.first().url.contains("mailto:"), "expected NOT to contain: " + "mailto:")
    }

    @Test
    fun testLinksProtocolRelative() = runBlocking {
        // Handles protocol-relative URLs (//example.com) correctly
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_protocol_relative"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 1, "expected > 1")
        assertTrue(result.links.first().url.contains("//"), "expected to contain: " + "//")
    }

    @Test
    fun testLinksRelAttributes() = runBlocking {
        // Preserves rel=nofollow and rel=canonical attributes
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_rel_attributes"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 0, "expected > 0")
    }

    @Test
    fun testLinksRelativeParent() = runBlocking {
        // Resolves ../ and ./ relative parent path links correctly
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/links_relative_parent"
        val result = Kreuzcrawl.scrape(engine, url)
        assertTrue(result.links.size > 3, "expected > 3")
    }

}
