// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1dae80dec968fb99d1b7b43dfca11bb89983c23bba3fd199d417e01a76145f00
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.kreuzcrawl.e2e;

import static org.junit.jupiter.api.Assertions.*;

import dev.kreuzberg.kreuzcrawl.Kreuzcrawl;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/** E2e tests for category: encoding. */
public class EncodingTest {
  @BeforeAll
  static void initEnv() {
    if (System.getProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK") == null) {
      System.setProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK", "true");
    }
  }

  @Test
  void testEncodingDoubleEncoded() throws Exception {
    // Handles double-encoded URL characters (%25C3%25B6)
    var engine = Kreuzcrawl.createEngine(null);
    String url = System.getProperty(
        "mockServer.encoding_double_encoded",
        System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
            + "/fixtures/encoding_double_encoded");
    var result = Kreuzcrawl.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
    assertTrue(result.links().size() >= 1, "expected >= 1");
  }

  @Test
  void testEncodingMixedCharsetPage() throws Exception {
    // Handles charset mismatch between HTTP header and HTML meta tag
    var engine = Kreuzcrawl.createEngine(null);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/encoding_mixed_charset_page";
    var result = Kreuzcrawl.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
  }

  @Test
  void testEncodingPercentEncodedPath() throws Exception {
    // Handles percent-encoded spaces and characters in URL paths
    var engine = Kreuzcrawl.createEngine(null);
    String url = System.getProperty(
        "mockServer.encoding_percent_encoded_path",
        System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
            + "/fixtures/encoding_percent_encoded_path");
    var result = Kreuzcrawl.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
    assertTrue(result.links().size() >= 2, "expected >= 2");
  }

  @Test
  void testEncodingUnicodeUrl() throws Exception {
    // Handles Unicode characters in URLs (Hebrew, Japanese, Cyrillic)
    var engine = Kreuzcrawl.createEngine(null);
    String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL"))
        + "/fixtures/encoding_unicode_url";
    var result = Kreuzcrawl.scrape(engine, url);
    assertFalse(result.html().isEmpty(), "expected non-empty value");
  }
}
