// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd828f2ea2cac3713ec3c284a7d639e0de0f3d69531a7257b737a7bba09a03e5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.kreuzcrawl.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.kreuzcrawl.Kreuzcrawl;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.kreuzcrawl.CrawlConfig;
import dev.kreuzberg.kreuzcrawl.CrawlConfig;
import java.util.Optional;
import dev.kreuzberg.kreuzcrawl.JsonUtil;

/** E2e tests for category: map. */
class MapTest {
    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE);

    @Test
    void testMapDiscoverUrls() throws Exception {
        // Discovers all URLs on a site without fetching full content
        var engineConfig = MAPPER.readValue("{\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServer.map_discover_urls", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_discover_urls");
        var result = Kreuzcrawl.mapUrls(engine, url);
assertTrue(result.urls().size() >= 3, "expected >= 3");
    }


    @Test
    void testMapExcludePatterns() throws Exception {
        // Excludes URLs matching patterns from URL map
        var engineConfig = MAPPER.readValue("{\"exclude_paths\":[\"/private/.*\",\"/api/.*\"],\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServer.map_exclude_patterns", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_exclude_patterns");
        var result = Kreuzcrawl.mapUrls(engine, url);
assertEquals(1, result.urls().size());
    }


    @Test
    void testMapIncludeSubdomains() throws Exception {
        // Includes subdomain URLs in URL map discovery; page has 1 local and 1 subdomain link
        var engineConfig = MAPPER.readValue("{\"allow_subdomains\":true,\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServer.map_include_subdomains", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_include_subdomains");
        var result = Kreuzcrawl.mapUrls(engine, url);
assertTrue(result.urls().size() >= 2, "expected >= 2");
    }


    @Test
    void testMapLargeSitemap() throws Exception {
        // Handles large sitemap with 100+ URLs
        var engineConfig = MAPPER.readValue("{\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_large_sitemap";
        var result = Kreuzcrawl.mapUrls(engine, url);
assertTrue(result.urls().size() >= 100, "expected >= 100");
    }


    @Test
    void testMapLimitPagination() throws Exception {
        // Limits map result count to specified maximum
        var engineConfig = MAPPER.readValue("{\"map_limit\":5,\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServer.map_limit_pagination", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_limit_pagination");
        var result = Kreuzcrawl.mapUrls(engine, url);
assertTrue(result.urls().size() <= 5, "expected <= 5");
    }


    @Test
    void testMapSearchFilter() throws Exception {
        // Filters map results by search keyword; 4 links in page but only 2 match 'blog'
        var engineConfig = MAPPER.readValue("{\"map_search\":\"blog\",\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Kreuzcrawl.createEngine(engineConfig);
        String url = System.getProperty("mockServer.map_search_filter", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/map_search_filter");
        var result = Kreuzcrawl.mapUrls(engine, url);
assertTrue(result.urls().size() >= 2, "expected >= 2");assertTrue(result.urls().size() <= 2, "expected <= 2");
    }

}
