// Generated by alef. Do not edit by hand.
// alef:hash:72558e3430fe432c0d196559cdd4f37d88e83d0ce5f9df21ac48756b891a02cb

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
