# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb11f9f81861f6fa24850d728f97432a8b5850355e96cc743a3b15633e409b3a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("kreuzcrawl")
    assert module is not None
