// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3c7e1843b2abeb8c041b6973931bb4a80cee6606b67967355eb1adddf197deeb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzcrawl
import RustBridge

/// E2e tests for category: scrape.
final class ScrapeTests: XCTestCase {
    func testScrapeAssetDedup() async throws {
        // Same asset linked twice results in one download with one unique hash
        let engineConfig = try crawlConfigFromJson("{\"download_assets\":true}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_asset_dedup"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.assets().count, 2)
        XCTAssertTrue(result.assets().contains(where: { !$0.content_hash().toString().isEmpty }), "expected non-empty value")
    }

    func testScrapeAssetMaxSize() async throws {
        // Skips assets exceeding max_asset_size limit
        let engineConfig = try crawlConfigFromJson("{\"download_assets\":true,\"max_asset_size\":150}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_asset_max_size"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.assets().count, 2)
    }

    func testScrapeAssetTypeFilter() async throws {
        // Only downloads image assets when asset_types filter is set
        let engineConfig = try crawlConfigFromJson("{\"asset_types\":[\"image\"],\"download_assets\":true}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_asset_type_filter"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.assets().count, 1)
        XCTAssertTrue(result.assets().contains(where: { $0.asset_category().toString().contains("image") }), "expected to contain: \("image")")
    }

    func testScrapeBasicHtmlPage() async throws {
        // Scrapes a simple HTML page and extracts title, description, and links
        let engineConfig = try crawlConfigFromJson("{\"max_depth\":0,\"respect_robots_txt\":false}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_basic_html_page"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertEqual(result.content_type().toString().trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "text/html")
        XCTAssertGreaterThan(result.html().len(), 0, "expected non-empty value")
        XCTAssertEqual((result.metadata().title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Example Domain")
        XCTAssertTrue((result.metadata().description()?.toString() ?? "").contains("illustrative examples"), "expected to contain: \("illustrative examples")")
        XCTAssertNotNil(result.metadata().canonical_url(), "expected non-nil value")
        XCTAssertGreaterThan(result.links().count, 0)
        let _vec_links_contains_all_56891867 = result.links()
        XCTAssertTrue(result.links().contains(where: { $0.link_type().toString().contains("external") }), "expected to contain: \("external")")
        XCTAssertEqual(result.images().count, 0)
        XCTAssertNil(result.metadata().og_title(), "expected nil value")
    }

    func testScrapeComplexLinks() async throws {
        // Classifies links by type: internal, external, anchor, document, image
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_complex_links"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.links().count, 9)
        XCTAssertTrue(result.links().contains(where: { !$0.url().toString().isEmpty }), "expected non-empty value")
    }

    func testScrapeDownloadAssets() async throws {
        // Downloads CSS, JS, and image assets from page
        let engineConfig = try crawlConfigFromJson("{\"download_assets\":true}")
        let engineObj = try createEngine(engineConfig)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_download_assets"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.assets().count, 2)
    }

    func testScrapeDublinCore() async throws {
        // Extracts Dublin Core metadata from a page
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_dublin_core"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertNotNil(result.metadata().dc_title(), "expected non-nil value")
        XCTAssertEqual((result.metadata().dc_title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Effects of Climate Change on Marine Biodiversity")
        XCTAssertEqual((result.metadata().dc_creator()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Dr. Jane Smith")
    }

    func testScrapeEmptyPage() async throws {
        // Handles an empty HTML document without errors
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_empty_page"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.links().count, -1)
        XCTAssertEqual(result.images().count, 0)
    }

    func testScrapeFeedDiscovery() async throws {
        // Discovers RSS, Atom, and JSON feed links
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_feed_discovery"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThanOrEqual(result.feeds().count, 3)
    }

    func testScrapeImageSources() async throws {
        // Extracts images from img, picture, og:image, twitter:image
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_image_sources"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.images().count, 4)
        XCTAssertEqual((result.metadata().og_image()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "https://example.com/images/og-hero.jpg")
    }

    func testScrapeJsHeavySpa() async throws {
        // Handles SPA page with JavaScript-only content (no server-rendered HTML)
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_js_heavy_spa"
        let result = try await scrape(engineObj, url)
        XCTAssertGreaterThan(result.html().len(), 0, "expected non-empty value")
    }

    func testScrapeJsonLd() async throws {
        // Extracts JSON-LD structured data from a page
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_json_ld"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertFalse(result.json_ld().isEmpty, "expected non-empty value")
        let _vec_json_ld_equals_820d23a5 = result.json_ld()
        XCTAssertEqual(_vec_json_ld_equals_820d23a5[0].schema_type().toString().trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Recipe")
        let _vec_json_ld_equals_986cbb1c = result.json_ld()
        XCTAssertEqual((_vec_json_ld_equals_986cbb1c[0].name()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Best Chocolate Cake")
    }

    func testScrapeMalformedHtml() async throws {
        // Gracefully handles broken HTML without crashing
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_malformed_html"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertGreaterThan(result.html().len(), 0, "expected non-empty value")
        XCTAssertTrue((result.metadata().description()?.toString() ?? "").contains("broken HTML"), "expected to contain: \("broken HTML")")
    }

    func testScrapeOgMetadata() async throws {
        // Extracts full Open Graph metadata from a page
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_og_metadata"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertNotNil(result.metadata().og_title(), "expected non-nil value")
        XCTAssertEqual((result.metadata().og_title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Article Title")
        XCTAssertEqual((result.metadata().og_type()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "article")
        XCTAssertEqual((result.metadata().og_image()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "https://example.com/images/article-hero.jpg")
        XCTAssertNotNil(result.metadata().og_description(), "expected non-nil value")
        XCTAssertEqual((result.metadata().title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Article Title - Example Blog")
    }

    func testScrapeTwitterCard() async throws {
        // Extracts Twitter Card metadata from a page
        let engineObj = try createEngine(nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/scrape_twitter_card"
        let result = try await scrape(engineObj, url)
        XCTAssertEqual(result.status_code(), 200)
        XCTAssertNotNil(result.metadata().twitter_card(), "expected non-nil value")
        XCTAssertEqual((result.metadata().twitter_card()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "summary_large_image")
        XCTAssertEqual((result.metadata().twitter_title()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "New Product Launch")
    }

}
