// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:00a7d659706dd57aa254e26f96d488a7dd679e900162de6ebb14711084637e40
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  scrape,
  createEngine,
  WasmCrawlConfig,
  WasmAuthConfig,
  WasmBrowserConfig,
  WasmContentConfig,
  WasmProxyConfig,
} from "kreuzcrawl";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("browser", () => {
  it("browser_config_auto_no_feature: Browser mode 'auto' without browser feature enabled does not use browser", async () => {
    const engineConfig = WasmCrawlConfig.default();
    engineConfig.browser = (() => {
      const _u = WasmBrowserConfig.default();
      _u.mode = "auto";
      return _u;
    })();
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_config_auto_no_feature`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_config_never_mode: Browser mode 'never' prevents browser fallback even for SPA shell content", async () => {
    const engineConfig = WasmCrawlConfig.default();
    engineConfig.browser = (() => {
      const _u = WasmBrowserConfig.default();
      _u.mode = "never";
      return _u;
    })();
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_config_never_mode`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_minimal_page: Does NOT flag a short but real content page as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_minimal_page`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(false);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_next_empty: Detects Next.js page with __NEXT_DATA__ but no rendered content as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_next_empty`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_next_rendered: Does NOT flag Next.js page with full SSR content as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_next_rendered`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    {
      const _v = result.html;
      if (typeof _v === "string" || Array.isArray(_v)) {
        expect(_v.length).toBeGreaterThan(0);
      } else {
        expect(_v).toBeDefined();
        expect(_v).not.toBeNull();
      }
    }
    expect(result.browser.jsRenderHint).toBe(false);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_normal_page: Does NOT flag a normal server-rendered page as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_normal_page`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(false);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_nuxt_shell: Detects Nuxt SPA shell with empty #__nuxt div as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_nuxt_shell`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_react_shell: Detects React SPA shell with empty #root div as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_react_shell`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    {
      const _v = result.html;
      if (typeof _v === "string" || Array.isArray(_v)) {
        expect(_v.length).toBeGreaterThan(0);
      } else {
        expect(_v).toBeDefined();
        expect(_v).not.toBeNull();
      }
    }
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_detect_vue_shell: Detects Vue SPA shell with empty #app div as needing JS rendering", async () => {
    const engine = createEngine(null);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_detect_vue_shell`;
    const result = await scrape(engine, url);
    expect(Number(result.statusCode)).toBe(200);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(false);
  });
  it("browser_fallback_spa_render: Browser auto re-fetches SPA shell when JS rendering is detected", async () => {
    const engineConfig = WasmCrawlConfig.default();
    engineConfig.browser = (() => {
      const _u = WasmBrowserConfig.default();
      _u.mode = "auto";
      return _u;
    })();
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_fallback_spa_render`;
    const result = await scrape(engine, url);
    expect(result.browser.jsRenderHint).toBe(true);
    expect(result.browser.browserUsed).toBe(true);
  });
  it("browser_fallback_waf_blocked: Browser fallback triggers when WAF blocks the HTTP request (Cloudflare 403)", async () => {
    const engineConfig = WasmCrawlConfig.default();
    engineConfig.browser = (() => {
      const _u = WasmBrowserConfig.default();
      _u.mode = "auto";
      return _u;
    })();
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_fallback_waf_blocked`;
    const result = await scrape(engine, url);
    expect(result.browser.browserUsed).toBe(true);
  });
  it("browser_mode_always: Browser mode 'always' uses browser even for normal server-rendered pages", async () => {
    const engineConfig = WasmCrawlConfig.default();
    engineConfig.browser = (() => {
      const _u = WasmBrowserConfig.default();
      _u.mode = "always";
      return _u;
    })();
    const engine = createEngine(engineConfig);
    const url = `${process.env.MOCK_SERVER_URL}/fixtures/browser_mode_always`;
    const result = await scrape(engine, url);
    expect(result.browser.browserUsed).toBe(true);
  });
});
