// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a51ab2ff8c1572afa532410ae5910674adf22744a2540d453879b03abff63781
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

import { describe, expect, it } from "vitest";
import {
	scrape,
	crawl,
	createEngine,
	WasmCrawlConfig,
	WasmAuthConfig,
	WasmBrowserConfig,
	WasmContentConfig,
	WasmProxyConfig,
	WasmSsrfPolicy,
} from "@kreuzberg/kreuzcrawl-wasm";

process.env.KREUZCRAWL_ALLOW_PRIVATE_NETWORK ??= "true";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [
		_alefE2eText(item),
		_alefE2eText(record.kind),
		_alefE2eText(record.name),
		_alefE2eText(record.source),
		_alefE2eText(record.alias),
		_alefE2eText(record.text),
		_alefE2eText(record.signature),
		itemsText,
	];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}

describe("redirect", () => {
	it("redirect_301_permanent: Follows 301 permanent redirect and returns final page content", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_301_PERMANENT ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_301_permanent`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/target");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_302_found: Follows 302 Found redirect correctly", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_302_FOUND ?? `${process.env.MOCK_SERVER_URL}/fixtures/redirect_302_found`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/found-target");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_303_see_other: Follows 303 See Other redirect (method changes to GET)", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_303_SEE_OTHER ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_303_see_other`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/see-other");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_307_temporary: Follows 307 Temporary Redirect (preserves method)", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_307_TEMPORARY ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_307_temporary`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/temp-target");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_308_permanent: Follows 308 Permanent Redirect (preserves method)", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_308_PERMANENT ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_308_permanent`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/perm-target");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_cross_domain: Reports cross-domain redirect target without following to external domain", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_CROSS_DOMAIN ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_cross_domain`;
		const result = await crawl(engine, url);
		expect(result.finalUrl).toContain("/external-redirect");
		expect(Number(result.redirectCount)).toBe(1);
	}, 30000);
	it("redirect_loop: Detects redirect loop (A -> B -> A) and returns error", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = process.env.MOCK_SERVER_REDIRECT_LOOP ?? `${process.env.MOCK_SERVER_URL}/fixtures/redirect_loop`;
		await crawl(engine, url);
		// skipped: field 'is_error' not available on result type
	}, 30000);
	it("redirect_max_exceeded: Aborts when redirect count exceeds max_redirects limit", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.maxRedirects = 2;
		engineConfig.respectRobotsTxt = false;
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url =
			process.env.MOCK_SERVER_REDIRECT_MAX_EXCEEDED ??
			`${process.env.MOCK_SERVER_URL}/fixtures/redirect_max_exceeded`;
		await crawl(engine, url);
		// skipped: field 'is_error' not available on result type
	}, 30000);
});
