# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52bf6d1e0d703031d0cfef0917c237d3d03d86d7f050ce9eec8f9b0d48b48262
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzcrawl'
require 'json'
require 'spec_helper'

RSpec.describe 'content' do
  it 'content_204_no_content: Handles 204 No Content response gracefully' do
    engine = Kreuzcrawl.create_engine(nil)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_204_no_content"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.status_code).to eq(204)
    expect(result.html.nil? || result.html.empty?).to be(true)
  end

  it 'content_charset_iso8859: Handles ISO-8859-1 encoded page correctly' do
    engine_config = { 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_charset_iso8859"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.detected_charset.to_s.strip).to eq('iso-8859-1'.strip)
  end

  it 'content_empty_body: Handles 200 response with empty body gracefully' do
    engine_config = { 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_empty_body"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.status_code).to eq(200)
  end

  it 'content_gzip_compressed: Handles response with Accept-Encoding gzip negotiation' do
    engine_config = { 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_gzip_compressed"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
    expect(result.status_code).to eq(200)
  end

  it 'content_large_page_limit: Respects max body size limit and truncates or skips oversized pages' do
    engine_config = { 'max_body_size' => 1024, 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_large_page_limit"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.body_size).to be < 1025
  end

  it 'content_main_only: Extracts content with aggressive preprocessing, excluding nav, sidebar, footer' do
    skip 'Fixture has no assertions to validate'
  end

  it 'content_pdf_no_extension: Detects PDF content by Content-Type header when URL has no .pdf extension' do
    engine_config = { 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_pdf_no_extension"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.is_pdf).to be(true)
  end

  it 'content_remove_tags: Removes specified HTML elements by CSS selector before processing' do
    engine_config = { 'remove_tags' => %w[nav aside footer], 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_remove_tags"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
  end

  it 'content_utf8_bom: Handles UTF-8 content with BOM marker correctly' do
    engine_config = { 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/content_utf8_bom"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.detected_charset.to_s.strip).to eq('utf-8'.strip)
    expect(result.html.to_s).not_to be_empty
  end
end
