# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0a9bbdc36cd117c004241226df1dd9b7f2895777a60a7e29532d466af6629786
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzcrawl'
require 'json'
require 'spec_helper'

RSpec.describe 'encoding' do
  it 'encoding_double_encoded: Handles double-encoded URL characters (%25C3%25B6)' do
    engine = Kreuzcrawl.create_engine(nil)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/encoding_double_encoded"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
    expect(result.links.length).to be >= 1
  end

  it 'encoding_mixed_charset_page: Handles charset mismatch between HTTP header and HTML meta tag' do
    engine = Kreuzcrawl.create_engine(nil)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/encoding_mixed_charset_page"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
  end

  it 'encoding_percent_encoded_path: Handles percent-encoded spaces and characters in URL paths' do
    engine = Kreuzcrawl.create_engine(nil)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/encoding_percent_encoded_path"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
    expect(result.links.length).to be >= 2
  end

  it 'encoding_unicode_url: Handles Unicode characters in URLs (Hebrew, Japanese, Cyrillic)' do
    engine = Kreuzcrawl.create_engine(nil)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/encoding_unicode_url"
    result = Kreuzcrawl.scrape_async(engine, url)
    expect(result.html.to_s).not_to be_empty
  end
end
