# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f05ebafb58530de3b8e6d2c999d937800381d758f8dfed06eb8cc8b3f6192e4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzcrawl'
require 'json'
require 'spec_helper'

RSpec.describe 'error' do
  it 'error_401_unauthorized: Handles 401 Unauthorized response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_401_unauthorized"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_403_forbidden: Handles 403 Forbidden response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_403_forbidden"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_404_page: Handles 404 response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_404_page"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_408_request_timeout: Handles 408 Request Timeout response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_408_request_timeout"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_410_gone: Handles 410 Gone response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_410_gone"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_500_server: Handles 500 server error' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_500_server"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_502_bad_gateway: Handles 502 Bad Gateway response correctly' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_502_bad_gateway"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_connection_refused: Handles connection refused error gracefully' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_connection_refused"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_dns_resolution: Handles DNS resolution failure gracefully' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_dns_resolution"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_empty_response: Handles 200 with completely empty body gracefully' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end

  it 'error_invalid_proxy: Proxy pointing to unreachable address causes connection error during scrape' do
    expect do
      engine_config = { 'proxy' => { 'url' => 'http://127.0.0.1:1' } }
      engine = Kreuzcrawl.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_invalid_proxy"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_partial_response: Handles incomplete or truncated HTTP response' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_partial_response"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_rate_limited: Handles 429 rate limiting with Retry-After' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_rate_limited"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_retry_503: Retries request on 503 Service Unavailable response' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_retry_503"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_retry_backoff: Implements exponential backoff when retrying failed requests' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_retry_backoff"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_ssl_invalid_cert: Handles SSL certificate validation error' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_ssl_invalid_cert"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_timeout: Mock server delays response longer than request_timeout, surfacing a timeout error' do
    expect do
      engine_config = { 'request_timeout' => 500 }
      engine = Kreuzcrawl.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_timeout"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_waf_akamai: Akamai WAF detection returns WafBlocked error' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_waf_akamai"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_waf_false_403: Detects WAF/bot protection false 403 (Cloudflare challenge page)' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_waf_false_403"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end

  it 'error_waf_imperva: Imperva/Incapsula WAF detection' do
    expect do
      engine = Kreuzcrawl.create_engine(nil)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/error_waf_imperva"
      Kreuzcrawl.scrape_async(engine, url)
    end.to raise_error
  end
end
