# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b715a92d8f7e00abc0f5ad99eb17c63cda2ab5b6932f99af1336aae814ba6df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzcrawl'
require 'json'
require 'spec_helper'

RSpec.describe 'proxy' do
  it 'proxy_authenticated: Proxy with username and password credentials authenticates successfully' do
    engine_config = { 'proxy' => { 'password' => 'proxypass', 'url' => 'http://127.0.0.1:8889', 'username' => 'proxyuser' }, 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/proxy_authenticated"
    result = Kreuzcrawl.crawl_async(engine, url)
    expect(result.pages.length).to eq(0)

  end

  it 'proxy_basic_success: Configure proxy URL and successfully crawl through it' do
    engine_config = { 'proxy' => { 'url' => 'http://127.0.0.1:8888' }, 'respect_robots_txt' => false }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/proxy_basic_success"
    result = Kreuzcrawl.crawl_async(engine, url)
    expect(result.pages.length).to eq(0)

  end
end
