# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4a7ee13a4704d794ac931a9082c0e65ba8635cbaac284ebcfa47f64add9f65d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzcrawl'
require 'json'
require 'spec_helper'

RSpec.describe 'warc' do
  it 'warc_basic_output: Scrape single page with WARC output enabled writes to file' do
    engine_config = { 'respect_robots_txt' => false, 'warc_output' => '/tmp/kreuzcrawl_test.warc' }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/warc_basic_output"
    result = Kreuzcrawl.crawl_async(engine, url)
    expect(result.pages[0].status_code).to eq(200)
    expect(result.pages.length).to eq(1)

  end

  it 'warc_multi_page_crawl: Crawl multiple pages with depth=1 and WARC output enabled' do
    engine_config = { 'max_depth' => 1, 'respect_robots_txt' => false, 'warc_output' => '/tmp/kreuzcrawl_crawl.warc' }
    engine = Kreuzcrawl.create_engine(engine_config.to_json)
    url = ENV.fetch('MOCK_SERVER_WARC_MULTI_PAGE_CRAWL', nil) || "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/warc_multi_page_crawl"
    result = Kreuzcrawl.crawl_async(engine, url)
    expect(result.pages.length).to be >= 2
    expect(result.stayed_on_domain).to be(true)

  end
end
