# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec959bcb383f8a5edf16e083192358c3d69fe097c0e7d316a8f145d8e96ff380
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzcrawl
  VERSION = '0.3.0.pre.rc.20'
end
