// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cb6ae885303cb07069b510a0291ba2eef4b9ae7f8e7c2c763e709eaf908e5821
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Authentication configuration.
/// </summary>
[JsonConverter(typeof(AuthConfigJsonConverter))]
public abstract record AuthConfig
{
    /// <summary>
    /// HTTP Basic authentication.
    /// </summary>
    public sealed record Basic(
        [property: JsonPropertyName("username")] string Username,
        [property: JsonPropertyName("password")] string Password
    ) : AuthConfig;

    /// <summary>
    /// Bearer token authentication.
    /// </summary>
    public sealed record Bearer(
        [property: JsonPropertyName("token")] string Token
    ) : AuthConfig;

    /// <summary>
    /// Custom authentication header.
    /// </summary>
    public sealed record Header(
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("value")] string Value
    ) : AuthConfig;

}

/// <summary>Custom JSON converter for <see cref="AuthConfig"/> that reads the "type" discriminator from any position.</summary>
internal sealed class AuthConfigJsonConverter : JsonConverter<AuthConfig>
{
    public override AuthConfig Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("type", out var tagEl))
            throw new JsonException("AuthConfig: missing \"type\" discriminator");
        var tag = tagEl.GetString();
        var json = root.GetRawText();
        return tag switch
        {
            "basic" => JsonSerializer.Deserialize<AuthConfig.Basic>(json, options)!
                ?? throw new JsonException("Failed to deserialize AuthConfig.Basic"),
            "bearer" => JsonSerializer.Deserialize<AuthConfig.Bearer>(json, options)!
                ?? throw new JsonException("Failed to deserialize AuthConfig.Bearer"),
            "header" => JsonSerializer.Deserialize<AuthConfig.Header>(json, options)!
                ?? throw new JsonException("Failed to deserialize AuthConfig.Header"),
            _ => throw new JsonException($"Unknown AuthConfig discriminator: {tag}")
        };
    }

    public override void Write(Utf8JsonWriter writer, AuthConfig value, JsonSerializerOptions options)
    {
        // Serialize the concrete type, then inject the discriminator
        switch (value)
        {
            case AuthConfig.Basic v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "basic");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            case AuthConfig.Bearer v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "bearer");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            case AuthConfig.Header v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "header");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            default: throw new JsonException($"Unknown AuthConfig subtype: {value.GetType().Name}");
        }
    }
}
