// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f105593938a094dc7aa1d0e3990eaeae1492d92efccc2a4e141b4199a6b02dfe
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A bad gateway error occurred (HTTP 502).
/// </summary>
public class BadGatewayException : CrawlErrorException
{
    public BadGatewayException(string message) : base(message) { }

    public BadGatewayException(string message, Exception innerException) : base(message, innerException) { }
}
