// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9290297fa354ac4a3d07b0efa778bd4083e44c2738d0b8952fca5fdb3906c8a0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Result from a single URL in a batch crawl operation.
/// </summary>
public sealed class BatchCrawlResult
{
    /// <summary>
    /// The seed URL that was crawled.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    /// <summary>
    /// The crawl result, if successful.
    /// </summary>
    [JsonPropertyName("result")]
    public CrawlResult? Result { get; set; } = null;

    /// <summary>
    /// The error message, if the crawl failed.
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; set; } = null;

}
