// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f58999911990d26df01d6ce39d80f875d2ff8ecf9bd7b07e9435ba12042fe07f
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException
{
    public BrowserErrorException(string message) : base(message) { }

    public BrowserErrorException(string message, Exception innerException) : base(message, innerException) { }
}
