// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4a7ee13a4704d794ac931a9082c0e65ba8635cbaac284ebcfa47f64add9f65d
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException
{
    public BrowserTimeoutException(string message) : base(message) { }

    public BrowserTimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
