// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23c84442ae557837828b4343c24b25156e8ffd9da63797487ec5b8e7343a9ce6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Result of citation conversion.
/// </summary>
public sealed class CitationResult
{
    /// <summary>
    /// Markdown with links replaced by numbered citations.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    /// <summary>
    /// Numbered reference list: (index, url, text).
    /// </summary>
    [JsonPropertyName("references")]
    public List<CitationReference> References { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="CitationResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static CitationResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CitationResult>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse CitationResult from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse CitationResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
