// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:201177ab1fb2fdec3556e24178fc176a8245e0c8a6a32a882f4cc3ded3e5ac8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Result of citation conversion.
/// </summary>
public sealed record CitationResult
{
    /// <summary>
    /// Markdown with links replaced by numbered citations.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; init; } = "";

    /// <summary>
    /// Numbered reference list: (index, url, text).
    /// </summary>
    [JsonPropertyName("references")]
    public List<CitationReference> References { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="CitationResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static CitationResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CitationResult>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse CitationResult from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse CitationResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
