// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:937368c39951441cae9fbd56b3e8c73b2bfab0310bfbeea92ece032a8ce7519c
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A connection error occurred.
/// </summary>
public class ConnectionException : CrawlErrorException
{
    public ConnectionException(string message) : base(message) { }

    public ConnectionException(string message, Exception innerException) : base(message, innerException) { }
}
