// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1dae80dec968fb99d1b7b43dfca11bb89983c23bba3fd199d417e01a76145f00
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// Data was lost or truncated during transfer.
/// </summary>
public class DataLossException : CrawlErrorException
{
    public DataLossException(string message) : base(message) { }

    public DataLossException(string message, Exception innerException) : base(message, innerException) { }
}
