// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba38af1cb8741e4f3841dd66c2861e4cdd146c375d4b87359f97f44b3a8d2438
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// Information about a favicon or icon link.
/// </summary>
public sealed record FaviconInfo
{
    /// <summary>
    /// The icon URL.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; init; } = "";

    /// <summary>
    /// The `rel` attribute (e.g., "icon", "apple-touch-icon").
    /// </summary>
    [JsonPropertyName("rel")]
    public string Rel { get; init; } = "";

    /// <summary>
    /// The `sizes` attribute, if present.
    /// </summary>
    [JsonPropertyName("sizes")]
    public string? Sizes { get; init; } = null;

    /// <summary>
    /// The MIME type, if present.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="FaviconInfo"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static FaviconInfo FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<FaviconInfo>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse FaviconInfo from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse FaviconInfo from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
