// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73f4581bd0ea492f56fb33c2b28385e33b9b811cb4a6e702cf38e2913b63ff1a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// A heading element extracted from the page.
/// </summary>
public sealed class HeadingInfo
{
    /// <summary>
    /// The heading level (1-6).
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// The heading text content.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
