// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1c8974711ef2a834d9ad49ee4d3c33e732ee7745e918209c0a36af5318b0a3cb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;

/// <summary>
/// An hreflang alternate link entry.
/// </summary>
public sealed record HreflangEntry
{
    /// <summary>
    /// The language code (e.g., "en", "fr", "x-default").
    /// </summary>
    [JsonPropertyName("lang")]
    public string Lang { get; init; } = "";

    /// <summary>
    /// The URL for this language variant.
    /// </summary>
    [JsonPropertyName("url")]
    public string URL { get; init; } = "";


    /// <summary>
    /// Parse a <see cref="HreflangEntry"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzcrawlException">When the JSON cannot be deserialised.</exception>
    public static HreflangEntry FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HreflangEntry>(json, JsonOptions)
                ?? throw new KreuzcrawlException($"Failed to parse HreflangEntry from JSON: deserializer returned null");
        }
        catch (KreuzcrawlException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzcrawlException($"Failed to parse HreflangEntry from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
