// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7964cf6dcfea7e797e850c61af91ae709d9cecde3534978485047b389479c168
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzcrawl;
/// <summary>/// The classification of a link./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{/// <summary>    /// A link to the same domain.    /// </summary>
    [JsonPropertyName("internal")]
    Internal,/// <summary>    /// A link to a different domain.    /// </summary>
    [JsonPropertyName("external")]
    External,/// <summary>    /// A fragment-only link (e.g., `#section`).    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,/// <summary>    /// A link to a downloadable document (PDF, DOC, etc.).    /// </summary>
    [JsonPropertyName("document")]
    Document,
}
