// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b715a92d8f7e00abc0f5ad99eb17c63cda2ab5b6932f99af1336aae814ba6df
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
