// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:39298f35fb5e6c9c2aa54d79d8c179abeb77246655eeea5dd78f55bac19c86a6
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
