// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:79552f1a5cac8dc93f4a3d58f3d2dd4a14377879d604ee6f5c5af9ee0e576a20
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
