// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba973d45f5df12e25835c635f88a7a619ccc039e2096b87a078d5f51e9910622
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
