// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bb11f9f81861f6fa24850d728f97432a8b5850355e96cc743a3b15633e409b3a
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// An SSL/TLS error occurred.
/// </summary>
public class SslException : CrawlErrorException
{
    public SslException(string message) : base(message) { }

    public SslException(string message, Exception innerException) : base(message, innerException) { }
}
