// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0f5b2d9dfe69d9a7e6550743dec4cd5c91648ad3d68bfb97fc0409f241c56eee
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request timed out.
/// </summary>
public class TimeoutException : CrawlErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
