// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:05192e8d03f7217b1e9c6aac224f14d834eb440af4139452518eec54873ea90d
#nullable enable

using System;

namespace Kreuzcrawl;

/// <summary>
/// The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
/// </summary>
public class WafBlockedException : CrawlErrorException
{
    public WafBlockedException(string message) : base(message) { }

    public WafBlockedException(string message, Exception innerException) : base(message, innerException) { }
}
