// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:72558e3430fe432c0d196559cdd4f37d88e83d0ce5f9df21ac48756b891a02cb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.kreuzcrawl.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.kreuzcrawl.android.Kreuzcrawl
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import dev.kreuzberg.kreuzcrawl.android.CrawlConfig

/** E2e tests for category: scrape. */
class ScrapeTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("KREUZCRAWL_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("kcrawl_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load kcrawl_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testScrapeAssetDedup() = runBlocking {
        // Same asset linked twice results in one download with one unique hash
        val engineConfig = MAPPER.readValue("{\"download_assets\":true}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServer.scrape_asset_dedup", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_asset_dedup"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertEquals(2, result.assets.size)
        assertFalse(result.assets.first().contentHash.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testScrapeAssetMaxSize() = runBlocking {
        // Skips assets exceeding max_asset_size limit
        val engineConfig = MAPPER.readValue("{\"download_assets\":true,\"max_asset_size\":150}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServer.scrape_asset_max_size", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_asset_max_size"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertEquals(2, result.assets.size)
    }

    @Test
    fun testScrapeAssetTypeFilter() = runBlocking {
        // Only downloads image assets when asset_types filter is set
        val engineConfig = MAPPER.readValue("{\"asset_types\":[\"image\"],\"download_assets\":true}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServer.scrape_asset_type_filter", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_asset_type_filter"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertEquals(1, result.assets.size)
        assertTrue(result.assets.first().assetCategory.name.lowercase().contains("image"), "expected to contain: " + "image")
    }

    @Test
    fun testScrapeBasicHtmlPage() = runBlocking {
        // Scrapes a simple HTML page and extracts title, description, and links
        val engineConfig = MAPPER.readValue("{\"max_depth\":0,\"respect_robots_txt\":false}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_basic_html_page"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertEquals("text/html", result.contentType.trim())
        assertFalse(result.html.isEmpty(), "expected non-empty value")
        assertEquals("Example Domain", result.metadata.title.orEmpty().trim())
        assertTrue(result.metadata.description.orEmpty().contains("illustrative examples"), "expected to contain: " + "illustrative examples")
        assertTrue(result.metadata.canonicalUrl != null, "expected non-empty value")
        assertTrue(result.links.size > 0, "expected > 0")
        assertTrue(result.links.first().linkType.name.lowercase().contains("external"), "expected to contain: " + "external")
        assertEquals(0, result.images.size)
        assertTrue(result.metadata.ogTitle == null, "expected empty value")
    }

    @Test
    fun testScrapeComplexLinks() = runBlocking {
        // Classifies links by type: internal, external, anchor, document, image
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_complex_links"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.links.size > 9, "expected > 9")
        assertFalse(result.links.first().url.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testScrapeDownloadAssets() = runBlocking {
        // Downloads CSS, JS, and image assets from page
        val engineConfig = MAPPER.readValue("{\"download_assets\":true}", CrawlConfig::class.java)
        val engine = Kreuzcrawl.createEngine(engineConfig)
        val url = System.getProperty("mockServer.scrape_download_assets", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_download_assets"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.assets.size > 2, "expected > 2")
    }

    @Test
    fun testScrapeDublinCore() = runBlocking {
        // Extracts Dublin Core metadata from a page
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_dublin_core"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.metadata.dcTitle != null, "expected non-empty value")
        assertEquals("Effects of Climate Change on Marine Biodiversity", result.metadata.dcTitle.orEmpty().trim())
        assertEquals("Dr. Jane Smith", result.metadata.dcCreator.orEmpty().trim())
    }

    @Test
    fun testScrapeEmptyPage() = runBlocking {
        // Handles an empty HTML document without errors
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_empty_page"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.links.size > -1, "expected > -1")
        assertEquals(0, result.images.size)
    }

    @Test
    fun testScrapeFeedDiscovery() = runBlocking {
        // Discovers RSS, Atom, and JSON feed links
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_feed_discovery"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.feeds.size >= 3, "expected >= 3")
    }

    @Test
    fun testScrapeImageSources() = runBlocking {
        // Extracts images from img, picture, og:image, twitter:image
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_image_sources"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.images.size > 4, "expected > 4")
        assertEquals("https://example.com/images/og-hero.jpg", result.metadata.ogImage.orEmpty().trim())
    }

    @Test
    fun testScrapeJsHeavySpa() = runBlocking {
        // Handles SPA page with JavaScript-only content (no server-rendered HTML)
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_js_heavy_spa"
        val result = Kreuzcrawl.scrape(engine, url)
        assertFalse(result.html.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testScrapeJsonLd() = runBlocking {
        // Extracts JSON-LD structured data from a page
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_json_ld"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertFalse(result.jsonLd.isEmpty(), "expected non-empty value")
        assertEquals("Recipe", result.jsonLd.first().schemaType.trim())
        assertEquals("Best Chocolate Cake", result.jsonLd.first().name.orEmpty().trim())
    }

    @Test
    fun testScrapeMalformedHtml() = runBlocking {
        // Gracefully handles broken HTML without crashing
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_malformed_html"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertFalse(result.html.isEmpty(), "expected non-empty value")
        assertTrue(result.metadata.description.orEmpty().contains("broken HTML"), "expected to contain: " + "broken HTML")
    }

    @Test
    fun testScrapeOgMetadata() = runBlocking {
        // Extracts full Open Graph metadata from a page
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_og_metadata"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.metadata.ogTitle != null, "expected non-empty value")
        assertEquals("Article Title", result.metadata.ogTitle.orEmpty().trim())
        assertEquals("article", result.metadata.ogType.orEmpty().trim())
        assertEquals("https://example.com/images/article-hero.jpg", result.metadata.ogImage.orEmpty().trim())
        assertTrue(result.metadata.ogDescription != null, "expected non-empty value")
        assertEquals("Article Title - Example Blog", result.metadata.title.orEmpty().trim())
    }

    @Test
    fun testScrapeTwitterCard() = runBlocking {
        // Extracts Twitter Card metadata from a page
        val engine = Kreuzcrawl.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/scrape_twitter_card"
        val result = Kreuzcrawl.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.metadata.twitterCard != null, "expected non-empty value")
        assertEquals("summary_large_image", result.metadata.twitterCard.orEmpty().trim())
        assertEquals("New Product Launch", result.metadata.twitterTitle.orEmpty().trim())
    }

}
