// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc4744ea9a670f4d4591aec9f18a6dbbe4e206aa52748665203561dcddad7332
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzcrawl/kreuzcrawl.dart';
import 'package:kreuzcrawl/src/kreuzcrawl_bridge_generated/frb_generated.dart'
    show RustLib;

// E2e tests for category: sitemap
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Parses a standard urlset sitemap', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_basic";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
    // skipped: field 'has_lastmod' not available on dart result type
  });

  test('Parses a gzip-compressed sitemap file', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_compressed_gzip";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
  });

  test('Handles empty sitemap gracefully', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_empty";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
  });

  test('Discovers sitemap via robots.txt Sitemap directive', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"respect_robots_txt":true}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        Platform.environment["MOCK_SERVER_SITEMAP_FROM_ROBOTS_TXT"] ??
        (Platform.environment["MOCK_SERVER_URL"]! +
            "/fixtures/sitemap_from_robots_txt");
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
  });

  test('Follows sitemap index to discover child sitemaps', () async {
    final engine = await KreuzcrawlBridge.createEngine();
    final url =
        Platform.environment["MOCK_SERVER_SITEMAP_INDEX"] ??
        (Platform.environment["MOCK_SERVER_URL"]! + "/fixtures/sitemap_index");
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
  });

  test('Filters sitemap URLs by lastmod date', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_lastmod_filter";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
    // skipped: field 'has_lastmod' not available on dart result type
  });

  test('Uses sitemap URLs exclusively without following page links', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_only_mode";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
  });

  test('Parses sitemap with XHTML namespace alternate links', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/sitemap_xhtml_links";
    final result = await KreuzcrawlBridge.scrape(engine, url);
    // skipped: field 'urls.length' not available on dart result type
    // skipped: field 'has_lastmod' not available on dart result type
  });
}
