// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:29372743a11d24ac6dc293b519d632f677f61373dd132e462cbf02e5c819d6ae
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzcrawl/kreuzcrawl.dart';
import 'package:kreuzcrawl/src/kreuzcrawl_bridge_generated/frb_generated.dart'
    show RustLib;

// E2e tests for category: strategy

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

PageAction _parsePageAction(Map<String, dynamic> json) {
  final actionType = json['type'] as String?;
  switch (actionType) {
    case 'click':
      return PageAction.click(selector: json['selector'] as String);
    case 'type_text':
      return PageAction.typeText(
        selector: json['selector'] as String,
        text: json['text'] as String,
      );
    case 'press_key':
      return PageAction.press(key: json['key'] as String);
    case 'scroll_down':
      return PageAction.scroll(
        direction: ScrollDirection.down,
        selector: json['selector'] as String? ?? '',
        amount: json['amount'] as int? ?? 0,
      );
    case 'wait_selector':
      return PageAction.wait(
        milliseconds: json['timeout_ms'] as int? ?? 0,
        selector: json['selector'] as String,
      );
    case 'screenshot':
      return PageAction.screenshot(
        fullPage: json['full_page'] as bool? ?? false,
      );
    case 'execute_js':
      return PageAction.executeJs(script: json['script'] as String);
    case 'scrape':
      return const PageAction.scrape();
    default:
      throw UnsupportedError('Unknown PageAction type: $actionType');
  }
}

void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test(
    'Adaptive strategy stops early when encountering saturation (duplicate content)',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"max_concurrent":1,"max_depth":2,"respect_robots_txt":false}',
      );
      final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
      final url =
          Platform.environment["MOCK_SERVER_STRATEGY_ADAPTIVE_SATURATION"] ??
          (Platform.environment["MOCK_SERVER_URL"]! +
              "/fixtures/strategy_adaptive_saturation");
      final result = await KreuzcrawlBridge.crawl(engine, url);
      expect(result.pages.length, greaterThanOrEqualTo(1));
    },
  );

  test('Adaptive strategy crawls more pages when content is diverse', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":1,"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        Platform.environment["MOCK_SERVER_STRATEGY_ADAPTIVE_WINDOW"] ??
        (Platform.environment["MOCK_SERVER_URL"]! +
            "/fixtures/strategy_adaptive_window");
    final result = await KreuzcrawlBridge.crawl(engine, url);
    expect(result.pages.length, greaterThanOrEqualTo(3));
  });

  test('BestFirst strategy always processes the seed URL first', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":1,"max_depth":1}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        Platform.environment["MOCK_SERVER_STRATEGY_BEST_FIRST_SEED"] ??
        (Platform.environment["MOCK_SERVER_URL"]! +
            "/fixtures/strategy_best_first_seed");
    final result = await KreuzcrawlBridge.crawl(engine, url);
    expect(result.pages.length, equals(3));
    // skipped: field 'strategy.first_page_url_contains' not available on dart result type
  });

  test('BFS strategy visits pages in breadth-first order', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":1,"max_depth":2}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        Platform.environment["MOCK_SERVER_STRATEGY_BFS_DEFAULT_ORDER"] ??
        (Platform.environment["MOCK_SERVER_URL"]! +
            "/fixtures/strategy_bfs_default_order");
    final result = await KreuzcrawlBridge.crawl(engine, url);
    expect(result.pages.length, equals(5));
    // skipped: field 'strategy.crawl_order' not available on dart result type
  });

  test('DFS strategy visits pages in depth-first order', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":1,"max_depth":2}',
    );
    final engine = await KreuzcrawlBridge.createEngine(config: engineConfig);
    final url =
        Platform.environment["MOCK_SERVER_STRATEGY_DFS_DEPTH_FIRST"] ??
        (Platform.environment["MOCK_SERVER_URL"]! +
            "/fixtures/strategy_dfs_depth_first");
    final result = await KreuzcrawlBridge.crawl(engine, url);
    expect(result.pages.length, equals(5));
    // skipped: field 'strategy.crawl_order' not available on dart result type
  });
}
