#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4b0d8810077217b7172e13cead159734da8fcb8bee1be6c51057421b97bbdef9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: robots
set -euo pipefail

test_robots_allow_all() {
  # Permissive robots.txt allows all paths
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_ALLOW_ALL:-${MOCK_SERVER_URL}/fixtures/robots_allow_all}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_allow_override() {
  # Allow directive overrides Disallow for specific paths
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_ALLOW_OVERRIDE:-${MOCK_SERVER_URL}/fixtures/robots_allow_override}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_comments_handling() {
  # Correctly parses robots.txt with inline and line comments
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_COMMENTS_HANDLING:-${MOCK_SERVER_URL}/fixtures/robots_comments_handling}" --config '{"respect_robots_txt":true,"user_agent":"kreuzcrawl"}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_crawl_delay() {
  # Respects crawl-delay directive from robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_CRAWL_DELAY:-${MOCK_SERVER_URL}/fixtures/robots_crawl_delay}" --config '{"respect_robots_txt":true,"user_agent":"kreuzcrawl"}' --format json --browser-mode never)

  local val_robots_crawl_delay
  val_robots_crawl_delay=$(echo "$output" | jq -r '.crawl_delay')
  assert_equals "$val_robots_crawl_delay" '2' 'robots.crawl_delay'
}

test_robots_disallow_path() {
  # Robots.txt disallows specific paths
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_DISALLOW_PATH:-${MOCK_SERVER_URL}/fixtures/robots_disallow_path}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'false' 'robots.is_allowed'
}

test_robots_meta_nofollow() {
  # Detects nofollow meta robots tag and skips link extraction
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_META_NOFOLLOW:-${MOCK_SERVER_URL}/fixtures/robots_meta_nofollow}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_nofollow_detected
  val_robots_nofollow_detected=$(echo "$output" | jq -r '.nofollow_detected')
  assert_equals "$val_robots_nofollow_detected" 'true' 'robots.nofollow_detected'
}

test_robots_meta_noindex() {
  # Detects noindex meta robots tag in HTML page
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_META_NOINDEX:-${MOCK_SERVER_URL}/fixtures/robots_meta_noindex}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_noindex_detected
  val_robots_noindex_detected=$(echo "$output" | jq -r '.noindex_detected')
  assert_equals "$val_robots_noindex_detected" 'true' 'robots.noindex_detected'
}

test_robots_missing_404() {
  # Missing robots.txt (404) allows all crawling
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_MISSING_404:-${MOCK_SERVER_URL}/fixtures/robots_missing_404}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_multiple_user_agents() {
  # Picks the most specific user-agent block from robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_MULTIPLE_USER_AGENTS:-${MOCK_SERVER_URL}/fixtures/robots_multiple_user_agents}" --config '{"respect_robots_txt":true,"user_agent":"SpecificBot"}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_request_rate() {
  # Parses request-rate directive from robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_REQUEST_RATE:-${MOCK_SERVER_URL}/fixtures/robots_request_rate}" --config '{"respect_robots_txt":true,"user_agent":"kreuzcrawl"}' --format json --browser-mode never)

  local val_robots_crawl_delay
  val_robots_crawl_delay=$(echo "$output" | jq -r '.crawl_delay')
  assert_equals "$val_robots_crawl_delay" '5' 'robots.crawl_delay'
  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_sitemap_directive() {
  # Discovers sitemap URL from Sitemap directive in robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_SITEMAP_DIRECTIVE:-${MOCK_SERVER_URL}/fixtures/robots_sitemap_directive}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'true' 'robots.is_allowed'
}

test_robots_user_agent_specific() {
  # Matches user-agent specific rules in robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_USER_AGENT_SPECIFIC:-${MOCK_SERVER_URL}/fixtures/robots_user_agent_specific}" --config '{"respect_robots_txt":true,"user_agent":"KreuzcrawlBot"}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'false' 'robots.is_allowed'
}

test_robots_wildcard_paths() {
  # Handles wildcard Disallow patterns in robots.txt
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_WILDCARD_PATHS:-${MOCK_SERVER_URL}/fixtures/robots_wildcard_paths}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_is_allowed
  val_robots_is_allowed=$(echo "$output" | jq -r '.is_allowed')
  assert_equals "$val_robots_is_allowed" 'false' 'robots.is_allowed'
}

test_robots_x_robots_tag() {
  # Respects X-Robots-Tag HTTP header directives
  local output
  output=$(kreuzcrawl scrape "${MOCK_SERVER_ROBOTS_X_ROBOTS_TAG:-${MOCK_SERVER_URL}/fixtures/robots_x_robots_tag}" --config '{"respect_robots_txt":true}' --format json --browser-mode never)

  local val_robots_x_robots_tag
  val_robots_x_robots_tag=$(echo "$output" | jq -r '.x_robots_tag')
  assert_equals "$val_robots_x_robots_tag" 'noindex, nofollow' 'robots.x_robots_tag'
  local val_robots_noindex_detected
  val_robots_noindex_detected=$(echo "$output" | jq -r '.noindex_detected')
  assert_equals "$val_robots_noindex_detected" 'true' 'robots.noindex_detected'
  local val_robots_nofollow_detected
  val_robots_nofollow_detected=$(echo "$output" | jq -r '.nofollow_detected')
  assert_equals "$val_robots_nofollow_detected" 'true' 'robots.nofollow_detected'
}

run_tests_robots() {
  run_test test_robots_allow_all
  run_test test_robots_allow_override
  run_test test_robots_comments_handling
  run_test test_robots_crawl_delay
  run_test test_robots_disallow_path
  run_test test_robots_meta_nofollow
  run_test test_robots_meta_noindex
  run_test test_robots_missing_404
  run_test test_robots_multiple_user_agents
  run_test test_robots_request_rate
  run_test test_robots_sitemap_directive
  run_test test_robots_user_agent_specific
  run_test test_robots_wildcard_paths
  run_test test_robots_x_robots_tag
}
